### PR TITLE
Fix C# sending empty payloads with gzip compression

### LINKED ISSUE #18753: Random native grpc_csharp_ext.x64.dll crash while running C# VSTest unit tests
### What version of gRPC and what language are you using?
`1.19.1` in C#, taken from the official NuGet repository for Windows
 
### What operating system (Linux, Windows,...) and version?
 Windows 10 Pro, version `10.0.17134.648`
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Downloaded compiled binaries and assemblies from NuGet repository, version `1.19.1`
 
### What did you do?
The issue happens randomly when the code executes under Microsoft VSTest unit tests environment. Some tests fail from time to time with error `"The agent process was stopped while the test was running."` (similar to [this](https://stackoverflow.com/questions/2810012/vs-2010-test-runner-error-the-agent-process-was-stopped-while-the-test-was-runn)).
Digging into this problem, I found the error described below in the `Application` event log (Event 1000, `Application Error`). It appears the crash happened in the native gRPC code of the C# assembly (exception `0xc0000409` in offset `0x21b84d`). I don't know what was the base address of the loaded module, and I don't have the `pdb` symbols to investigate.
 
### What did you expect to see?
 ... no crash ...
 
### What did you see instead?

> Faulting application name: QTAgent_40.exe, version: 14.0.23107.0, time stamp: 0x559b7ab8
Faulting module name: grpc_csharp_ext.x64.dll, version: 0.0.0.0, time stamp: 0x5c757b11
Exception code: 0xc0000409
Fault offset: 0x000000000021b84d
Faulting process id: 0x2f2c
Faulting application start time: 0x01d4f29695d8f46a
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\QTAgent_40.exe
Faulting module path: c:\jenkins\workspace\...\grpc_csharp_ext.x64.dll
Report Id: 53964039-befa-4b6b-be5d-218788a76d3c
Faulting package full name: 

### Anything else we should know about your project / environment?
We use `VSTest` installed as part of `Visual Studio 14` ecosystem. It loads the tests `dll` which contains dozens of tests. For each test, we start a new instances of gRPC servers (on different ports, over and over again), and connect gRPC clients which run on different threads of that process. In the end of each test, everything is (allegedly) cleaned up.

### PR DESCRIPTION
**Pull request by jtattermusch**
Fixes #18753 

The problem is that C-core's "send_message" operation expects that the send buffer is not empty (= contains at least on slice, even if it's an empty slice) when compression is on.

Fix is to make sure that C# always provides a send buffer that has at least one slice (only a consideration in the case where the buffer is empty obviously).
Also adding extra tests to cover this case (I was able to reproduce reliably without the fix).

See https://github.com/grpc/grpc/pull/21118#issuecomment-557068042 for additional details.

### CODE REVIEW

**Comment by jtattermusch** [comment]
@hcaseyal an alternative fix would be to  make sure that C-core accepts an empty buffer with slice_count = 0 in all cases (not just for uncompressed traffic). This requirement on having at least one slice in the slice_buffer is actually undocumented, so it would also be a reasonable fix to increase C-core's robustness.

File: src/csharp/ext/grpc_csharp_ext.c [hunk 1]
```diff
@@ -1244,7 +1244,9 @@ GPR_EXPORT void* GPR_CALLTYPE grpcsharp_slice_buffer_adjust_tail_space(
   }
 
   if (buffer->count == 0) {
-    return NULL;
+    // when sending messages, C-core requires that there
+    // is at least on slice, even for empty payload.
+    grpc_slice_buffer_add_indexed(buffer, grpc_empty_slice());
```
Comment (apolcyn) [inline src/csharp/ext/grpc_csharp_ext.c]: LGTM, but I do think it would be preferable to fix this in the core API. Can we file a bug to handle this in C-core (after which we should be able to remove this line) ?

File: src/csharp/ext/grpc_csharp_ext.c [hunk 2]
```diff
@@ -1244,7 +1244,9 @@ GPR_EXPORT void* GPR_CALLTYPE grpcsharp_slice_buffer_adjust_tail_space(
   }
 
   if (buffer->count == 0) {
-    return NULL;
+    // when sending messages, C-core requires that there
+    // is at least on slice, even for empty payload.
```
Comment (hcaseyal) [inline src/csharp/ext/grpc_csharp_ext.c]: Nit: on -> one

**Comment by hcaseyal** [comment]
@jtattermusch I'm looking into a C-core fix now

File: src/csharp/ext/grpc_csharp_ext.c (hunk 2 above)
Comment (jtattermusch) [reply src/csharp/ext/grpc_csharp_ext.c]: done.

File: src/csharp/ext/grpc_csharp_ext.c (hunk 1 above)
Comment (jtattermusch) [reply src/csharp/ext/grpc_csharp_ext.c]: Filed https://github.com/grpc/grpc/issues/21299 and added a comment.

**Comment by jtattermusch** [comment]
Known failures: https://github.com/grpc/grpc/issues/21297

**Comment by jtattermusch** [comment]
I'm going to merge now and I can revert the C#-specific fix once this is fixed in C-core (tracking issue https://github.com/grpc/grpc/issues/21299)
