### PR TITLE
PHP: composer install could be flaky

### LINKED ISSUE #19437: PHP Interop Docker Image Fails to Build
```
+ php -d extension=ext/grpc/modules/grpc.so /usr/local/bin/composer install
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies (including require-dev)
  [Composer\Downloader\TransportException]
  The "https://packagist.org/p/provider-2015%2418c42deccda75e24d7425d30ec42196c69f9ad7e0550902d126809c4f4fd276c.json" file could not be downloaded (HTTP/1.1 404 Not Found)
install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...
2019-06-21 14:15:01,894 FAILED: build_docker_php [ret=1, pid=11976, time=650.8sec]
```

[Test run.](https://source.cloud.google.com/results/invocations/ff7b01b3-0259-452c-879a-dcb5fe23adb1/log)

### PR DESCRIPTION
**Pull request by stanley-cheung**
Attempt to fix #19437

### CODE REVIEW

File: tools/dockerfile/interoptest/grpc_interop_php/build_interop.sh [hunk 1]
```diff
@@ -36,6 +36,12 @@ make -j4 install_c plugins
...
 (cd third_party/protobuf && make -j4 install)
 
-(cd src/php && php -d extension=ext/grpc/modules/grpc.so /usr/local/bin/composer install)
+cd src/php
 
-(cd src/php && ./bin/generate_proto_php.sh)
+set +e
+php -d extension=ext/grpc/modules/grpc.so /usr/local/bin/composer install
+while [ $? -ne 0 ]; do
+  php -d extension=ext/grpc/modules/grpc.so /usr/local/bin/composer install
```
Comment (apolcyn) [inline tools/dockerfile/interoptest/grpc_interop_php/build_interop.sh]: I'm a little worried about this while loop causing an infinite retry

Can we limit the retries with something like:

```
set -ex
DONE=0
for ((i=0;i<10;i++)); do
  php -d extension=ext/grpc/modules/grpc.so /usr/local/bin/composer install && DONE=1
  [[ "$DONE" == 1 ]] && break
done
[[ "$DONE" != 1 ]] && echo "Failed to install" && exit 1
```

or 

```
php -d extension=ext/grpc/modules/grpc.so /usr/local/bin/composer install || php -d extension=ext/grpc/modules/grpc.so /usr/local/bin/composer install || php -d extension=ext/grpc/modules/grpc.so /usr/local/bin/composer install
```

?
