### PR TITLE
[ObjC] require osx version > 10.12 for cf event engine

### LINKED ISSUE #34049: event_engine build failure: cfstream_endpoint.cc: error: 'CFErrorDomain' was not declared in this scope; did you mean 'CFErrorGetDomain'?
```
[ 11%] Building CXX object CMakeFiles/grpc_authorization_provider.dir/src/core/lib/event_engine/default_event_engine_factory.cc.o
/opt/local/bin/g++-mp-12 -DGPR_BACKWARDS_COMPATIBILITY_MODE -DPROTOBUF_USE_DLLS -Dgrpc_authorization_provider_EXPORTS -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_grpc/grpc/work/grpc-1.57.0/include -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_grpc/grpc/work/grpc-1.57.0 -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_grpc/grpc/work/grpc-1.57.0/third_party/address_sorting/include -I/opt/local/libexec/openssl3/include -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_grpc/grpc/work/grpc-1.57.0/src/core/ext/upb-generated -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_grpc/grpc/work/grpc-1.57.0/src/core/ext/upbdefs-generated -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_grpc/grpc/work/grpc-1.57.0/third_party/upb -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_grpc/grpc/work/grpc-1.57.0/third_party/utf8_range -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_grpc/grpc/work/grpc-1.57.0/third_party/xxhash -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_grpc/grpc/work/build/gens -isystem /opt/local/include -pipe -I/opt/local/libexec/openssl3/include -Os -I/opt/local/libexec/protobuf3-cpp-upstream/include -DNDEBUG -I/opt/local/libexec/openssl3/include -isystem/opt/local/include/LegacySupport -isystem/opt/local/include -D__STDC_FORMAT_MACROS -D_GLIBCXX_USE_CXX11_ABI=0  -std=gnu++14 -arch ppc -mmacosx-version-min=10.6 -fPIC -MD -MT CMakeFiles/grpc_authorization_provider.dir/src/core/lib/event_engine/default_event_engine_factory.cc.o -MF CMakeFiles/grpc_authorization_provider.dir/src/core/lib/event_engine/default_event_engine_factory.cc.o.d -o CMakeFiles/grpc_authorization_provider.dir/src/core/lib/event_engine/default_event_engine_factory.cc.o -c /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_grpc/grpc/work/grpc-1.57.0/src/core/lib/event_engine/default_event_engine_factory.cc
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_grpc/grpc/work/grpc-1.57.0/src/core/lib/event_engine/cf_engine/cfstream_endpoint.cc: In function 'absl::lts_20230125::Status grpc_event_engine::experimental::{anonymous}::CFErrorToStatus(grpc_event_engine::experimental::CFTypeUniqueRef<__CFError*>)':
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_grpc/grpc/work/grpc-1.57.0/src/core/lib/event_engine/cf_engine/cfstream_endpoint.cc:34:3: error: 'CFErrorDomain' was not declared in this scope; did you mean 'CFErrorGetDomain'?
   34 |   CFErrorDomain cf_domain = CFErrorGetDomain((cf_error));
      |   ^~~~~~~~~~~~~
      |   CFErrorGetDomain
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_grpc/grpc/work/grpc-1.57.0/src/core/lib/event_engine/cf_engine/cfstream_endpoint.cc:39:22: error: 'cf_domain' was not declared in this scope
   39 |   CFStringGetCString(cf_domain, domain_buf, 256, kCFStringEncodingUTF8);
      |                      ^~~~~~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_grpc/grpc/work/grpc-1.57.0/src/core/lib/event_engine/cf_engine/cfstream_endpoint.cc: In member function 'void grpc_event_engine::experimental::CFStreamEndpointImpl::Connect(absl::lts_20230125::AnyInvocable<void(absl::lts_20230125::Status)>, grpc_event_engine::experimental::EventEngine::ResolvedAddress)':
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_grpc/grpc/work/grpc-1.57.0/src/core/lib/event_engine/cf_engine/cfstream_endpoint.cc:117:58: error: 'QOS_CLASS_DEFAULT' was not declared in this scope
  117 |                                dispatch_get_global_queue(QOS_CLASS_DEFAULT, 0));
      |                                                          ^~~~~~~~~~~~~~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_grpc/grpc/work/grpc-1.57.0/src/core/lib/event_engine/cf_engine/cfstream_endpoint.cc:117:32: error: 'dispatch_get_global_queue' was not declared in this scope
  117 |                                dispatch_get_global_queue(QOS_CLASS_DEFAULT, 0));
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_grpc/grpc/work/grpc-1.57.0/src/core/lib/event_engine/cf_engine/cfstream_endpoint.cc:116:3: error: 'CFReadStreamSetDispatchQueue' was not declared in this scope
  116 |   CFReadStreamSetDispatchQueue(cf_read_stream_,
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 11%] Building CXX object CMakeFiles/grpc.dir/src/core/ext/filters/client_channel/client_channel_factory.cc.o
/opt/local/bin/g++-mp-12 -DGPR_BACKWARDS_COMPATIBILITY_MODE -Dgrpc_EXPORTS -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_grpc/grpc/work/grpc-1.57.0/include -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_grpc/grpc/work/grpc-1.57.0 -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_grpc/grpc/work/grpc-1.57.0/third_party/address_sorting/include -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_grpc/grpc/work/grpc-1.57.0/src/core/ext/upb-generated -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_grpc/grpc/work/grpc-1.57.0/src/core/ext/upbdefs-generated -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_grpc/grpc/work/grpc-1.57.0/third_party/upb -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_grpc/grpc/work/grpc-1.57.0/third_party/utf8_range -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_grpc/grpc/work/grpc-1.57.0/third_party/xxhash -isystem /opt/local/libexec/openssl3/include -isystem /opt/local/include -pipe -I/opt/local/libexec/openssl3/include -Os -I/opt/local/libexec/protobuf3-cpp-upstream/include -DNDEBUG -I/opt/local/libexec/openssl3/include -isystem/opt/local/include/LegacySupport -isystem/opt/local/include -D__STDC_FORMAT_MACROS -D_GLIBCXX_USE_CXX11_ABI=0  -std=gnu++14 -arch ppc -mmacosx-version-min=10.6 -fPIC -MD -MT CMakeFiles/grpc.dir/src/core/ext/filters/client_channel/client_channel_factory.cc.o -MF CMakeFiles/grpc.dir/src/core/ext/filters/client_channel/client_channel_factory.cc.o.d -o CMakeFiles/grpc.dir/src/core/ext/filters/client_channel/client_channel_factory.cc.o -c /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_grpc/grpc/work/grpc-1.57.0/src/core/ext/filters/client_channel/client_channel_factory.cc
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_grpc/grpc/work/grpc-1.57.0/src/core/lib/event_engine/cf_engine/cfstream_endpoint.cc:118:3: error: 'CFWriteStreamSetDispatchQueue' was not declared in this scope
  118 |   CFWriteStreamSetDispatchQueue(
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/grpc_authorization_provider.dir/src/core/lib/event_engine/cf_engine/cfstream_endpoint.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```
What is going wrong here?

P. S. Unfortunately, I may some somewhat late with reporting the bug, since the last version I built was 1.54.2, so I am not sure when exactly this has been introduced.

### PR DESCRIPTION
**Pull request by HannahShiSFB**
fixes #34049

### CODE REVIEW

File: src/core/lib/event_engine/cf_engine/cf_engine.cc [hunk 1]
```diff
@@ -15,6 +15,7 @@
 #include <grpc/support/port_platform.h>
 
 #ifdef GPR_APPLE
+#if __MAC_OS_X_VERSION_MIN_REQUIRED > __MAC_10_12
```
Comment (barracuda156) [inline src/core/lib/event_engine/cf_engine/cf_engine.cc:18]: @HannahShiSFB Do `grpc` headers define `__MAC_10_12`? (If not, then this will not work correctly.)

**Comment by barracuda156** [comment]
@HannahShiSFB I also suspect that it is safer to use `MAC_OS_X_VERSION_MIN_REQUIRED` rather than `__MAC_OS_X_VERSION_MIN_REQUIRED`: the latter seems not to be supported with some older Clang versions. See: https://github.com/AcademySoftwareFoundation/openexr/pull/1416

**Comment by barracuda156** [comment]
@HannahShiSFB Comparisons look good now: numerical macros always work.

However `TARGET_OS_OSX` will not be defined on some Apple systems (unless gRPC adds it locally in its headers), so this part is likely to cause a failure. (I am on a mobile now, can verify once back to the desktop.)

https://github.com/catchorg/Catch2/issues/2139

https://github.com/libusb/libusb/issues/1097

**Comment by barracuda156** [comment]
Looks like `AVAILABLE_MAC_OS_X_VERSION_10_12_AND_LATER` gonna work!

**Review by sampajano — APPROVED** [review]
Thanks!! 😃

**Comment by HannahShiSFB** [comment]
@barracuda156 Can you help verify if this works in your environment?
