### PR TITLE
fix Cannot send compressed message large than 1024B in cronet_transport

### LINKED ISSUE #23210: Can not send message large than 1024B in cronet_transport
### What version of gRPC and what language are you using?
the newest version

### What operating system (Linux, Windows,...) and version?
ALL

### What runtime / compiler are you using (e.g. python version or version of gcc)
iOS with Cornet 

### What did you expect to see?
send message correctly

### What did you see instead?
in **cronet_transport.h**, send message only use first slice (grpc_slice_buffer_take_first)
`grpc_slice slice = grpc_slice_buffer_take_first(write_slice_buffer);  
 size_t length = GRPC_SLICE_LENGTH(slice);  
*p_write_buffer_size = length + GRPC_HEADER_SIZE_IN_BYTES;`

but in **message_compress.h**, compressed message large than 1024B will be many slices 
`grpc_slice_buffer_add_indexed(output, outbuf);    
 outbuf = GRPC_SLICE_MALLOC(OUTPUT_BLOCK_SIZE);   
 GPR_ASSERT(GRPC_SLICE_LENGTH(outbuf) <= uint_max);`
and **OUTPUT_BLOCK_SIZE 1024**

### PR DESCRIPTION
**Pull request by zhungxd**
Fixes #23210 

Change cronet transport to be able to handle send_message ops composed of more than one slice.

### CODE REVIEW

**Comment by markdroth** [comment]
You'll need to sign the CLA before we can look at this code.

**Comment by markdroth** [comment]
Oh, sorry -- looks like the problem is not that you didn't sign it, but rather that one of your commits is missing the user ID.  See above for details.

**Comment by zhungxd** [comment]
> Oh, sorry -- looks like the problem is not that you didn't sign it, but rather that one of your commits is missing the user ID. See above for details.

thanks
EasyCLA check passed now

File: src/core/lib/transport/byte_stream.cc [hunk 1]
```diff
@@ -55,8 +55,11 @@ void SliceBufferByteStream::Orphan() {
 
 bool SliceBufferByteStream::Next(size_t /*max_size_hint*/,
                                  grpc_closure* /*on_complete*/) {
-  GPR_DEBUG_ASSERT(backing_buffer_.count > 0);
-  return true;
+  if (cursor_ < backing_buffer_.count) {
```
Comment (markdroth) [inline src/core/lib/transport/byte_stream.cc:58]: This change doesn't look right to me.  A `SliceBufferByteStream` should always return true from `Next()`, because the bytes are always available.

As I mentioned elsewhere, `ByteStream::Next()` should never be called when there is no data left on the stream to read (which is what happens when you read the last slice out of the slice buffer), so there should be no case where this returns false.

I think that if you change the cronet code as I suggested, then the change in this file will not be necessary.

File: src/core/ext/transport/cronet/transport/cronet_transport.cc [hunk 2]
```diff
@@ -1090,22 +1094,21 @@ static enum e_op_result execute_stream_op(struct op_and_state* oas) {
...
       grpc_slice slice;
       grpc_slice_buffer_init(&write_slice_buffer);
-      if (1 != stream_op->payload->send_message.send_message->Next(
-                   stream_op->payload->send_message.send_message->length(),
-                   nullptr)) {
-        /* Should never reach here */
-        GPR_ASSERT(false);
-      }
-      if (GRPC_ERROR_NONE !=
+      while (1 == stream_op->payload->send_message.send_message->Next(
```
Comment (markdroth) [inline src/core/ext/transport/cronet/transport/cronet_transport.cc:1097]: The contract for `ByteStream::Next()` is that it should not be called once all bytes have been read from the stream:

https://github.com/grpc/grpc/blob/5c715f2696a5144daf664020ee372db4d2eaf0f0/src/core/lib/transport/byte_stream.h#L48

So instead of checking the result of `Next()` here, this should check to see if there are more bytes still to be read, using something like this:

```
while (write_slice_buffer.length < stream_op->payload->send_message.send_message->length()) {
```

You can then call `Next()` within the body of the loop.

Comment (markdroth) [reply src/core/ext/transport/cronet/transport/cronet_transport.cc:1097]: BTW, when you do call next, you can assert that it returns true, because currently all send_message ByteStreams have the data synchronously available.  But please add the following comment:

TODO(roth): When we add support for incremental sending, this code will need to be changed to support asynchronous delivery of the send_message payload.

Comment (muxi) [inline src/core/ext/transport/cronet/transport/cronet_transport.cc:1097]: The definition of `ByteStream::Next` is that the return value indicates whether the next slice is immediately available (and can be pulled synchronously; if not, it will need to be pulled asynchronously. The current code assumed that the stream will contain exactly 1 slice, and that slice will always be immediately available and does not support otherwise.

So while it makes sense to fetch more than 1 slice from the byte stream, we need to decide to either continue support only the immediately available case (and assert if it is not the case), or to support async pull. For the former case, if the return value of `Next()` is false, we should assert "should never reach here". For the later case, we should have code for async read. The change here seems doing neither right now. Could you make some changes here? The former option would be much easier to implement and I will be fine of it for now given we're already doing that.

File: src/core/lib/transport/byte_stream.cc (hunk 1 above)
Comment (muxi) [reply src/core/lib/transport/byte_stream.cc:58]: Missed this file in my review. Yea I agree with Mark that I don't think it is right to change the behavior of the `Next()` function.

Comment (zhungxd) [reply src/core/lib/transport/byte_stream.cc]: done

File: src/core/ext/transport/cronet/transport/cronet_transport.cc (hunk 2 above)
Comment (zhungxd) [reply src/core/ext/transport/cronet/transport/cronet_transport.cc]: done

Comment (zhungxd) [reply src/core/ext/transport/cronet/transport/cronet_transport.cc]: done

**Comment by zhungxd** [comment]
I hope it's fixed now! If there are still issues, please let me know.

File: src/core/ext/transport/cronet/transport/cronet_transport.cc [hunk 3]
```diff
@@ -1096,16 +1100,24 @@ static enum e_op_result execute_stream_op(struct op_and_state* oas) {
...
       }
-      if (GRPC_ERROR_NONE !=
+      while (write_slice_buffer.length <
+             stream_op->payload->send_message.send_message->length()) {
+        /*
+          TODO(roth): When we add support for incremental sending,
+          this code will need to be changed to support asynchronous delivery
+          of the send_message payload.
+        */
+        if (GRPC_ERROR_NONE !=
```
Comment (markdroth) [inline src/core/ext/transport/cronet/transport/cronet_transport.cc:1110]: The call to `Next()` should be moved inside of this loop.  There should be one call to `Next()` before each call to `Pull()`.

**Comment by zhungxd** [comment]
> Also, please run tools/distrib/clang_format_code.sh.

done

File: src/core/ext/transport/cronet/transport/cronet_transport.cc (hunk 3 above)
Comment (zhungxd) [reply src/core/ext/transport/cronet/transport/cronet_transport.cc:1109]: done

File: src/core/ext/transport/cronet/transport/cronet_transport.cc [hunk 4]
```diff
@@ -1090,22 +1093,30 @@ static enum e_op_result execute_stream_op(struct op_and_state* oas) {
...
+      while (write_slice_buffer.length <
+             stream_op->payload->send_message.send_message->length()) {
+        if (1 != stream_op->payload->send_message.send_message->Next(
+                     stream_op->payload->send_message.send_message->length(),
+                     nullptr)) {
+          /* Should never reach here */
+          GPR_ASSERT(false);
+        }
+        /*
+          TODO(roth): When we add support for incremental sending,this code will
```
Comment (markdroth) [inline src/core/ext/transport/cronet/transport/cronet_transport.cc:1105]: Please move this comment up above the call to `Next()`.

Also, please use C++-style comment syntax.

Comment (zhungxd) [reply src/core/ext/transport/cronet/transport/cronet_transport.cc]: done

File: src/core/ext/transport/cronet/transport/cronet_transport.cc [hunk 5]
```diff
@@ -1090,22 +1093,28 @@ static enum e_op_result execute_stream_op(struct op_and_state* oas) {
...
-      if (GRPC_ERROR_NONE !=
-          stream_op->payload->send_message.send_message->Pull(&slice)) {
-        /* Should never reach here */
-        GPR_ASSERT(false);
+      while (write_slice_buffer.length <
+             stream_op->payload->send_message.send_message->length()) {
+        /* TODO(roth): When we add support for incremental sending,this code
+         * will need to be changed to support asynchronous delivery of the
+         * send_message payload. */
+        if (1 != stream_op->payload->send_message.send_message->Next(
```
Comment (muxi) [inline src/core/ext/transport/cronet/transport/cronet_transport.cc:1101]: nit:  the return type of `Next()` is `bool`, so the `1 != ` part can be simply `!`

Comment (zhungxd) [reply src/core/ext/transport/cronet/transport/cronet_transport.cc]: done

**Comment by zhungxd** [comment]
Mon Jun 22 11:43:59 PDT 2020 - E0622 11:43:05.995406000 123145335746560 cronet_transport.cc:1116]     Empty request is not supported
Mon Jun 22 11:43:59 PDT 2020 - E0622 11:43:05.995695000 123145335746560 cronet_transport.cc:1117]     assertion failed: write_slice_buffer.count >= 1

**Comment by zhungxd** [comment]
Mon Jun 22 11:43:59 PDT 2020 - E0622 11:43:05.995406000 123145335746560 cronet_transport.cc:1116]     Empty request is not supported
Mon Jun 22 11:43:59 PDT 2020 - E0622 11:43:05.995695000 123145335746560 cronet_transport.cc:1117]     assertion failed: write_slice_buffer.count >= 1

**Comment by zhungxd** [comment]
testEmptyUnaryRPC test failed.
fixed.

**Comment by zhungxd** [comment]
@muxi add kokoro:run again？

**Comment by muxi** [comment]
Could you point me to the latest change? Seems like squashed already :(

**Comment by zhungxd** [comment]
> Could you point me to the latest change? Seems like squashed already and I'm not sure if I caught all the differences :(

`do {
        stream_op->payload->send_message.send_message->length()
        ...
        ...
        ...
        grpc_slice_buffer_add(&write_slice_buffer, slice);
      } while (write_slice_buffer.length <
               stream_op->payload->send_message.send_message->length());`

**Comment by muxi** [comment]
Ok thanks.

File: src/core/ext/transport/cronet/transport/cronet_transport.cc [hunk 6]
```diff
@@ -1090,22 +1093,28 @@ static enum e_op_result execute_stream_op(struct op_and_state* oas) {
...
-        GPR_ASSERT(false);
-      }
-      if (GRPC_ERROR_NONE !=
-          stream_op->payload->send_message.send_message->Pull(&slice)) {
-        /* Should never reach here */
-        GPR_ASSERT(false);
-      }
-      grpc_slice_buffer_add(&write_slice_buffer, slice);
-      if (GPR_UNLIKELY(write_slice_buffer.count != 1)) {
+      do {
```
Comment (muxi) [inline src/core/ext/transport/cronet/transport/cronet_transport.cc:1096]: I suspect that even though this works for now, it may not be ideal and might not work in the future if, e.g., the byte stream in `stream_op->payload->send_message.send_message` changed type. 

The reason is that the `ByteStream` interface does not guarantee that there'll always be an empty slice in an empty byte stream. Particularly, the interface [said](https://github.com/grpc/grpc/blob/88af358f9ec9b2a84f82b3f4e795df62c920c29b/src/core/lib/transport/byte_stream.h#L48) the Next() method "should not be called if there is no data left on the stream". That means the `while` loop in the previous revision was actually the right thing to do. We need to take care of the assert in `write_slice_buffer.count < 1` branch instead.

The limitation of `write_slice_buffer.count >= 1` comes from Cronet IIUC, so we probably can't directly eliminate it (or even if we can, it probably goes to another PR). So I would suggest an alternative workaround: if `write_slice_buffer` is empty after the while loop, add a zero length slice to it (replacing the original `write_slice_buffer.count < 1` branch).

Comment (zhungxd) [reply src/core/ext/transport/cronet/transport/cronet_transport.cc]: done. thanks for reviews.

Comment (zhungxd) [reply src/core/ext/transport/cronet/transport/cronet_transport.cc]: i removed "write_slice_buffer.count == 1" assert. The reason is ** create_grpc_frame** always return 5 byte gRPC header (even _write_slice_buffer_ is **empty**)

**Comment by zhungxd** [comment]
And some test are failed。but seems unrelate to this PR.
