### PR TITLE
Clear SSL error stacks before performing SSL I/O.

### LINKED ISSUE #23144: Decryption error: TSI_DATA_CORRUPTED
# What version of gRPC and what language are you using?
grpc-node 1.24.2

### What operating system (Linux, Windows,...) and version?
```
  Operating System: Debian GNU/Linux 10 (buster)
            Kernel: Linux 5.4.42-v8+
      Architecture: arm64

openssl:arm64/buster 1.1.1d-0+deb10u3 uptodate
```

### What runtime / compiler are you using (e.g. python version or version of gcc)
node

### What did you do?
As GRPC-Client, connecting to a Server using Server-Side SSL encryption. Using duplex streaming.

### What did you expect to see?
A stable connection.

### What did you see instead?
recurring disconnects:
```
ssl_transport_security.cc:483] Corruption detected.
ssl_transport_security.cc:459] error:14187180:SSL routines:ssl_do_config:bad value
secure_endpoint.cc:208]     Decryption error: TSI_DATA_CORRUPTED
```

### Anything else we should know about your project / environment?

This seems to be related to the environment. I can reproduce this on a Raspberry Pi 3 having Debian 10 (arm64) installed. When using Ubuntu 18 (arm64) instead on the same device, the problem does not occur.

Therefore my question: 
_What system libraries (or certs) are used by the C++ layer? And which version of this library would you recommend to use?_

Additional info:
Seems like unary calls are working, just (duplex) streaming is affected.

I have seen this decryption error was already mentioned in other tickets / environments, but seems like they never got fixed: #12642 #15506

### PR DESCRIPTION
**Pull request by bdhess**
In OpenSSL, if there happens to be an error on the stack before
the read begins, that error can cause the read to fail.

"The current thread's error queue must be empty before the TLS/SSL I/O
operation is attempted, or SSL_get_error() will not work reliably."
  -- https://www.openssl.org/docs/man1.1.1/man3/SSL_get_error.html

These manifest as difficult-to-debug application errors; handle these
more gracefully and improve the logging around what's going on.

Hopefully fixes #23144 and #24865.

@drfloob

### CODE REVIEW

**Comment by drfloob** [comment]
Hi @bdhess . You'll need to sign the CLA before we can take a look at this.

File: src/core/tsi/ssl_transport_security.cc [hunk 1]
```diff
@@ -490,21 +490,35 @@ static tsi_result peer_from_x509(X509* cert, int include_certificate_type,
...
-static void log_ssl_error_stack(void) {
-  unsigned long err;
-  while ((err = ERR_get_error()) != 0) {
-    char details[256];
-    ERR_error_string_n(static_cast<uint32_t>(err), details, sizeof(details));
-    gpr_log(GPR_ERROR, "%s", details);
+/* Retrieves the SSL error stack as a string. */
+static std::string ssl_error_stack_to_string(void) {
+  BIO* bio = BIO_new(BIO_s_mem());
+  ERR_print_errors(bio);
```
Comment (ZhenLian) [inline src/core/tsi/ssl_transport_security.cc:496]: In order to keep a consistent logging story for gRPC, we probably want to use `gpr_log()` here.
Can we keep the original loop for clearing error queue?

File: src/core/tsi/ssl_transport_security.cc [hunk 2]
```diff
@@ -1925,8 +1939,8 @@ tsi_result tsi_create_ssl_client_handshaker_factory_with_options(
   ssl_context = SSL_CTX_new(TLSv1_2_method());
 #endif
   if (ssl_context == nullptr) {
-    log_ssl_error_stack();
-    gpr_log(GPR_ERROR, "Could not create ssl context.");
+    gpr_log(GPR_ERROR, "Could not create ssl context: %s",
+            ssl_error_stack_to_string().c_str());
```
Comment (ZhenLian) [inline src/core/tsi/ssl_transport_security.cc:1943]: Is the behavior changed for this line? IIUC, the original `log_ssl_error_stack` will clear the error queue. Will the queue be cleared if using the new `ssl_error_stack_to_string()` function?

**Review by ZhenLian — CHANGES_REQUESTED** [review]
Thanks for making this change! The pull requests overall look good to me. I left some comments. Feel free to let me know if you have any questions/concerns. Thanks!

**Comment by ZhenLian** [comment]
@davidben Hi David, can you please also take a look and advise on how to log OpenSSL errors, if possible? Thanks in advance!

File: src/core/tsi/ssl_transport_security.cc (hunk 1 above)
Comment (bdhess) [reply src/core/tsi/ssl_transport_security.cc:496]: I found the current setup sort of unfortunate for two reasons:

* ERR_error_string (_n) truncates the error messages.

* The root cause is printed in a separate log statement from the "corruption detected" message.  As an example, it doesn't really make any sense that failure adding a directory full of X.509 trust anchors could lead to "corruption":
```
W20210729 23:07:00.135056 23154688 ssl_transport_security.cc:510] Corruption detected.
W20210729 23:07:00.135092 23154688 ssl_transport_security.cc:486] error:0B064071:x509 certificate routines:add_cert_dir:invalid directory
```

IMO this issue would've been much easier to debug if these had been compacted into a single statement.

File: src/core/tsi/ssl_transport_security.cc (hunk 2 above)
Comment (bdhess) [reply src/core/tsi/ssl_transport_security.cc:1943]: Ah, no.  The `ERR_clear_error()` call is redundant.  I'll remove that.

File: src/core/tsi/ssl_transport_security.cc [hunk 3]
```diff
@@ -490,21 +490,35 @@ static tsi_result peer_from_x509(X509* cert, int include_certificate_type,
...
+/* Retrieves the SSL error stack as a string. */
+static std::string ssl_error_stack_to_string(void) {
+  BIO* bio = BIO_new(BIO_s_mem());
+  ERR_print_errors(bio);
+
+  const uint8_t* buf;
+  size_t buf_len;
+  std::string result;
+  if (!BIO_mem_contents(bio, &buf, &buf_len) || buf_len == 0) {
+    result = "(error could not be retrieved from the SSL stack)";
```
[the remark this answers is not in the document]
Comment (bdhess) [reply src/core/tsi/ssl_transport_security.cc]: done

File: src/core/tsi/ssl_transport_security.cc [hunk 4]
```diff
@@ -490,21 +490,35 @@ static tsi_result peer_from_x509(X509* cert, int include_certificate_type,
...
 
 /* Performs an SSL_read and handle errors. */
 static tsi_result do_ssl_read(SSL* ssl, unsigned char* unprotected_bytes,
                               size_t* unprotected_bytes_size) {
-  int read_from_ssl;
   GPR_ASSERT(*unprotected_bytes_size <= INT_MAX);
+  // Gracefully handle the case where some other part of the application left
+  // an error on the stack.
+  if (ERR_peek_error() != 0) {
+    gpr_log(GPR_INFO, "do_ssl_read invoked with a dirty SSL error stack: %s",
```
[the remark this answers is not in the document]
Comment (bdhess) [reply src/core/tsi/ssl_transport_security.cc]: done

File: src/core/tsi/ssl_transport_security.cc (hunk 2 above)
Comment (bdhess) [reply src/core/tsi/ssl_transport_security.cc:1942]: Done, and updated method docstring.

File: src/core/tsi/ssl_transport_security.cc (hunk 1 above)
Comment (ZhenLian) [reply src/core/tsi/ssl_transport_security.cc:496]: Is it possible to concatenate all the error messages into one line using a for-loop, and then log them all in once by using `gpr_log()`? Or alternatively, is it possible to read all the characters from bio, and we then log it through `gpr_log()`?
I could see there is a need for changing the way we log. But is there a way we can avoid using OpenSSL's built-in logging methods?

**Review by ZhenLian — CHANGES_REQUESTED** [review]

File: src/core/tsi/ssl_transport_security.cc (hunk 1 above)
Comment (bdhess) [reply src/core/tsi/ssl_transport_security.cc:496]: [ERR_print_errors](https://commondatastorage.googleapis.com/chromium-boringssl-docs/bio.h.html#ERR_print_errors) prints to the BIO, not to stderr or stdout.  In this case, we created the BIO with [BIO_s_mem](https://commondatastorage.googleapis.com/chromium-boringssl-docs/bio.h.html#BIO_s_mem), so it refers to an in-memory buffer.  Which is then copied to a `std::string` for subsequent logging with `gpr_log()`.

Comment (ZhenLian) [reply src/core/tsi/ssl_transport_security.cc:496]: Ah I see, that would be perfect. Thanks for the explanation!

**Review by ZhenLian — APPROVED** [review]

File: src/core/tsi/ssl_transport_security.cc [hunk 5]
```diff
@@ -490,21 +490,34 @@ static tsi_result peer_from_x509(X509* cert, int include_certificate_type,
...
 }
 
-/* Logs the SSL error stack. */
-static void log_ssl_error_stack(void) {
-  unsigned long err;
-  while ((err = ERR_get_error()) != 0) {
-    char details[256];
-    ERR_error_string_n(static_cast<uint32_t>(err), details, sizeof(details));
-    gpr_log(GPR_ERROR, "%s", details);
+/* Clears all SSL errors from the stack, and returns them as a string. */
```
Comment (davidben) [inline src/core/tsi/ssl_transport_security.cc:493]: Nit: It's a queue, not a stack.

File: src/core/tsi/ssl_transport_security.cc [hunk 6]
```diff
@@ -490,21 +490,34 @@ static tsi_result peer_from_x509(X509* cert, int include_certificate_type,
...
 /* Performs an SSL_read and handle errors. */
 static tsi_result do_ssl_read(SSL* ssl, unsigned char* unprotected_bytes,
                               size_t* unprotected_bytes_size) {
-  int read_from_ssl;
   GPR_ASSERT(*unprotected_bytes_size <= INT_MAX);
+  // Gracefully handle the case where some other part of the application left
+  // an error on the stack.
+  if (ERR_peek_error() != 0) {
+    gpr_log(GPR_ERROR, "do_ssl_read invoked with a dirty SSL error stack: %s",
+            ssl_error_stack_to_string().c_str());
```
Comment (davidben) [inline src/core/tsi/ssl_transport_security.cc:518]: So adding a warning here only makes sense if gRPC believes it is a bug to for other code to handle an OpenSSL error without consuming the error queue. Otherwise you'll end up causing a lot of noise.

It is true that leaving the error queue dirty will result in some weirdness down the line. At the same time, I think this is a lot of fuss. It's also a little odd to have `ssl_error_stack_to_string` return a string with newlines. I suggest either:

Option 1: say that leaving things in the error queue isn't a bug worth warning on and just replace all these `if (ERR_peek_error() ...) { ... }` blocks with a single `ERR_clear_error()` call.

Option 2: say we want to warn about leaving things in the error queue. In that case, let's just call the log function twice like this:

```
static void ensure_empty_error_queue(const char* function) {
  if (ERR_peek_error() != 0) {
    gpr_log(GPR_ERROR, "%s invoked with a dirty OpenSSL error queue.", function);
    log_ssl_error_queue();
  }
}
```

Reason for the helper function is...

File: src/core/tsi/ssl_transport_security.cc [hunk 7]
```diff
@@ -490,21 +490,34 @@ static tsi_result peer_from_x509(X509* cert, int include_certificate_type,
...
+  }
+  int read_from_ssl;
   read_from_ssl = SSL_read(ssl, unprotected_bytes,
```
Comment (davidben) [inline src/core/tsi/ssl_transport_security.cc:521]: There are many more places in this file than `SSL_read` which are paired with `SSL_get_error`. If we want to do this in gRPC, we should do it in front of the other ones too. Hence helper function above.

**Review by davidben — COMMENTED** [review]
It is true that `SSL_get_error` is obnoxiously error-queue-sensitive. BoringSSL will clear the error queue at the start of all the `SSL_get_error` operations, largely because of this issue. I don't know off-hand whether OpenSSL does. There's certainly no harm in handling it, and I guess OpenSSL makes this the caller's responsibility.

File: src/core/tsi/ssl_transport_security.cc (hunk 6 above)
Comment (bdhess) [reply src/core/tsi/ssl_transport_security.cc:518]: I think you've convinced me that I'm being too fussy and (1.) is correct.  Handling the other cases as well.

**Review by davidben — APPROVED** [review]

**Comment by ZhenLian** [comment]
Thanks for making the change so far! The code looks much concise now.
Passing to @yihuazhang for a final review. Hi YIhua, could you please take a final look on this, please?

**Comment by yihuazhang** [comment]
LGTM

**Review by yihuazhang — APPROVED** [review]

**Comment by ZhenLian** [comment]
@bdhess It seems the portability test fails: https://source.cloud.google.com/results/invocations/f92d91cc-eeb7-4d11-8230-a5dd78af7954/targets, and the failure seems relevant to this PR.
Would you mind taking a look? Thank you!

**Comment by bdhess** [comment]
@ZhenLian I think I should've explicitly included another OpenSSL header for 1.0.2 backwards compatibility, but I don't have an easy way to test that change besides just kicking off the CI.  Hope this fixes it. :)

**Comment by ZhenLian** [comment]
All test passed, except "import/copybara" is pending. Merging now...

**Comment by ZhenLian** [comment]
@bdhess Thanks again for your contributing!
