### PR TITLE
Fix Copy and Unref Bug

### LINKED ISSUE #10127: Core tsan-reported data race in copy_error_and_unref
@ncteisen - the arena optimization in error.c needs to be tuned slightly. The `memcpy` is reading the refcount values as well using ordinary loads even though the refs are expected to be processed using only atomic operations (which are happening in parallel at other threads). This can be seen at https://grpc-testing.appspot.com/job/gRPC_pull_requests_tsan_cpp/2747/consoleFull . Ping me if you'd like to discuss.

### PR DESCRIPTION
**Pull request by ncteisen**
Fixes #10127.

Changed the error struct so that the atomics are at the top, and now I only memcpy the non-protected variables. Will run the tsan tests repeatedly on my machine to ensure this works.

### CODE REVIEW

File: src/core/lib/iomgr/error_internal.h [hunk 1]
```diff
@@ -48,12 +48,12 @@ struct grpc_linked_error {
 
 struct grpc_error {
   gpr_refcount refs;
+  gpr_atm error_string;
```
Comment (vjpai) [inline src/core/lib/iomgr/error_internal.h]: I would suggest one of two alternatives here:
1. Put the atomics in a struct within a struct (there would be no runtime overhead of doing so) and then just incrementing by the size of that inner struct. That way there's no problem in maintaining this line in the future if you realize you need to add more atomics there. But that would make this CL substantially uglier since every reference to refs or error_string would need to be changed to error_atomic_struct.{refs,error_string} . This is optional and I could see going either way on that one.

2. Put a comment in the struct clearly identifying that any atomic variables need to go at the top since the rest will be copied in bulk by raw memcpy. This is mandatory since this will not be easy to follow otherwise.

Comment (ncteisen) [inline src/core/lib/iomgr/error_internal.h]: I chose to do 1, I agree that that is cleaner, and seemed worth the bigger modification of the code. I also took this opportunity to be a bit less terse with my comments :)

File: src/core/lib/iomgr/error.c [hunk 2]
```diff
@@ -191,15 +192,16 @@ void grpc_error_unref(grpc_error *err, const char *file, int line,
                       const char *func) {
   if (grpc_error_is_special(err)) return;
   gpr_log(GPR_DEBUG, "%p: %" PRIdPTR " -> %" PRIdPTR " [%s:%d %s]", err,
-          err->refs.count, err->refs.count - 1, file, line, func);
-  if (gpr_unref(&err->refs)) {
+          err->atomics.refs.count, err->atomics.refs.count - 1, file, line,
```
Comment (ctiller) [inline src/core/lib/iomgr/error.c]: `s/err->atomics.refs.count/gpr_atm_no_barrier_load(&err->atomics.refs.count)/g`

Comment (ncteisen) [inline src/core/lib/iomgr/error.c]: Done. I called it on both parameters of the gpr_log call as I figure saving it as a temp variable defeats the purpose of the atomic load.

**Comment by ncteisen** [comment]
Last run showed an asan issue in append_chr that didn't look unrelated... Which is confusing bc I don't see how this change could have caused that. Will see what the tests say as they run again.

**Comment by ncteisen** [comment]
So the asan bug was fixed by changing the order of steps. Apparently this ordering causes a double free on memory realloc-ed in append_chr:
* initialize atomics (refs and error_string)
* bulk memcpy the rest

However, flipping the ordering fixes this issue. My homework tonight will be to try to wrap my head around why.

Going to merge this in once Jenkins goes green again (I forgot to clang format...)

**Comment by ncteisen** [comment]
Only failures are #9550. Merging
