### PR TITLE
Fixed local cloning of grpc/grpc submodules on docker

### LINKED ISSUE #8145: git clone --recursive in dockerized tests fetches submodules from github
Ideally, the submodules would be fetched from the clone that is already in Jenkins workspace (as it is done for the grpc/grpc repo itself).

We have plenty of places where this problem occurs:
https://github.com/grpc/grpc/search?utf8=%E2%9C%93&q=git+clone+--recursive

We should really fix it at least in the matrix jobs that run unit tests and portability tests (each cell now seems to be fetching all submodules from github from scratch and that is too much).
https://github.com/grpc/grpc/blob/ebf66403aabf03d519c9f7307149720faf6e1d47/tools/run_tests/dockerize/docker_run_tests.sh#L45

### PR DESCRIPTION
**Pull request by matt-kwong**
Fixes #8145

### CODE REVIEW

File: tools/run_tests/dockerize/docker_run_tests.sh [hunk 1]
```diff
@@ -42,7 +42,11 @@ export PATH=$PATH:/usr/bin/llvm-symbolizer
 chown $(whoami) $XDG_CACHE_HOME
 
 mkdir -p /var/local/git
-git clone --recursive /var/local/jenkins/grpc /var/local/git/grpc
+git clone /var/local/jenkins/grpc /var/local/git/grpc
+
+# clone gRPC submodules
```
Comment (jtattermusch) [inline tools/run_tests/dockerize/docker_run_tests.sh]: I think adding an explanatory comment would be useful for future generations.
`# clone gRPC submodules, use data from locally cloned submodules where possible'

File: tools/run_tests/dockerize/docker_run_tests.sh [hunk 2]
```diff
@@ -42,7 +42,11 @@ export PATH=$PATH:/usr/bin/llvm-symbolizer
...
+(cd /var/local/git/grpc/ && exec git submodule | awk '{ system("git submodule \
```
Comment (jtattermusch) [inline tools/run_tests/dockerize/docker_run_tests.sh]: What's here seems to be working but there seems to be some unnecessary complexity (the exec command), awk system, etc. I see they are there for a reason but it makes me wonder  - and others will probably wonder too, especially if they don't know what the idea behind this command is
how about
```
# clone each submodule using a local reference repo to avoid downloading entire submodules from github each time
git submodule foreach 'cd /var/local/jenkins/grpc && git submodule update --init --reference ../../jenkins/grpc/${name} ${name}'
```

Comment (jtattermusch) [inline tools/run_tests/dockerize/docker_run_tests.sh]: actually --reference /var/local/jenkins/grpc/${name} might be the most readable.

File: test/distrib/cpp/run_distrib_test.sh [hunk 3]
```diff
@@ -30,9 +30,13 @@
 
 set -ex
 
-git clone --recursive $EXTERNAL_GIT_ROOT
+git clone $EXTERNAL_GIT_ROOT
 cd grpc
 
+# clone submodules
+git submodule | awk -v EXTERNAL_GIT_ROOT=$EXTERNAL_GIT_ROOT/ '{ system("git \
```
Comment (jtattermusch) [inline test/distrib/cpp/run_distrib_test.sh]: please take a look at the git submodule foreach suggestion below and decide which one is more readable. Also elaborate the comment a bit.

**Comment by matt-kwong** [comment]
I definitely agree with expanding on comments and checking to make sure that gRPC submodules were succesfully cloned. As for checking whether they are cloned locally vs via network, I think checking Jenkins logs with timestamps enabled will show which method was used. 

In regards to reducing complexity: I did more research and testing, and I believe that "git submodule foreach" does nothing unless the submodules are already cloned. My idea to reduce complexity is to create an external repo for just submodules and to reference this when cloning submodules. This way, it is much more obvious what is happening in the scripts. Let me know what you think.

File: test/distrib/cpp/run_distrib_test.sh [hunk 4]
```diff
@@ -30,9 +30,14 @@
 
 set -ex
 
-git clone --recursive $EXTERNAL_GIT_ROOT
+git clone $EXTERNAL_GIT_ROOT
 cd grpc
 
+# clone gRPC submodules, use data from locally cloned submodules where possible
+git submodule update --init --recursive --reference $EXTERNAL_GIT_SUBMODULES_ROOT
+# if local gRPC submodules clone fails, clone via network
```
Comment (jtattermusch) [inline test/distrib/cpp/run_distrib_test.sh]: if local submodules clone fails, wouldn't that terminate the script because of `set -ex` above?

Comment (jtattermusch) [inline test/distrib/cpp/run_distrib_test.sh]: Btw, we don't really need the --recursive I think. (I knew we originally had --recursive but I believe it was for simplicity)

File: test/distrib/cpp/run_distrib_test.sh [hunk 5]
```diff
@@ -30,9 +30,14 @@
...
+git submodule update --init --recursive
```
Comment (jtattermusch) [inline test/distrib/cpp/run_distrib_test.sh]: Actually, I don't see why the previous command could fail (git should fallback by itself, right?).

File: tools/dockerfile/grpc_scan_build/Dockerfile [hunk 6]
```diff
@@ -41,6 +41,19 @@ RUN git clone --recursive https://github.com/grpc/grpc.git
 EXPOSE 8181
 
 CMD \
+  # creating a repository for gRPC submodules for local cloning
+  # this list should be updated when the list of submodules for gRPC changes
+  mkdir grpc-submodules && cd grpc-submodules && \
```
Comment (jtattermusch) [inline tools/dockerfile/grpc_scan_build/Dockerfile]: This would only populate the reference repo for grpc_scan_build Dockerfile, but we have 50 other docker images. What's up with the reference repo of all the other Dockerfiles.

Comment (jtattermusch) [inline tools/dockerfile/grpc_scan_build/Dockerfile]: Also, the submodules only get fetched once you build the Dockerfile. The built docker image can be cached on our Jenkins workers for months, which also means the reference repo will be months old.

Comment (jtattermusch) [inline tools/dockerfile/grpc_scan_build/Dockerfile]: Another problem is you are manually listing all the submodules here. The day we add a new submodule, there's a very high chance we will forget to manually update the list.

Comment (matt-kwong) [inline tools/dockerfile/grpc_scan_build/Dockerfile]: I reverted all changes I made regarding changing the DockerFile and went with your suggested foreach solution. I'll check PR test logs to see if anything breaks.

**Comment by matt-kwong** [comment]
test this please.

File: test/distrib/cpp/run_distrib_test.sh [hunk 7]
```diff
@@ -30,7 +30,13 @@
 
 set -ex
 
-git clone --recursive $EXTERNAL_GIT_ROOT
+git clone $EXTERNAL_GIT_ROOT
```
Comment (jtattermusch) [inline test/distrib/cpp/run_distrib_test.sh]: when $EXTERNAL_GIT_ROOT is used as the source repo, you need to use it (instead of /var/local/jenkins/grpc)

File: tools/dockerfile/interoptest/grpc_interop_php7/build_interop.sh [hunk 8]
```diff
@@ -32,12 +32,17 @@
...
+# clone gRPC submodules, use data from locally cloned submodules where possible
+(cd /var/local/jenkins/grpc / && git submodule foreach 'cd /var/local/git/grpc \
+&& git submodule update --init --reference /var/local/jenkins/grpc/${name} \
+${name}')
 
 # copy service account keys if available
 cp -r /var/local/jenkins/service_account $HOME || true
 
 cd /var/local/git/grpc
+
```
Comment (jtattermusch) [inline tools/dockerfile/interoptest/grpc_interop_php7/build_interop.sh]: nit: remove this line

File: tools/dockerfile/stress_test/grpc_interop_stress_php/build_interop_stress.sh [hunk 9]
```diff
@@ -32,12 +32,17 @@
 set -ex
 
 mkdir -p /var/local/git
-git clone --recursive /var/local/jenkins/grpc /var/local/git/grpc
+git clone /var/local/jenkins/grpc /var/local/git/grpc
+# clone gRPC submodules, use data from locally cloned submodules where possible
+(cd /var/local/jenkins/grpc / && git submodule foreach 'cd /var/local/git/grpc \
```
Comment (jtattermusch) [inline tools/dockerfile/stress_test/grpc_interop_stress_php/build_interop_stress.sh]: extra space after `grpc /`

File: test/distrib/cpp/run_distrib_test.sh [hunk 10]
```diff
@@ -30,7 +30,13 @@
...
+# clone gRPC submodules, use data from locally cloned submodules where possible
+(cd /var/local/jenkins/grpc / && git submodule foreach 'cd /var/local/git/grpc \
```
Comment (jtattermusch) [inline test/distrib/cpp/run_distrib_test.sh]: extra space in `grpc /`. also below (many times).

File: tools/run_tests/dockerize/docker_run.sh [hunk 11]
```diff
@@ -36,7 +36,11 @@ set -ex
 if [ "$RELATIVE_COPY_PATH" == "" ]
 then
   mkdir -p /var/local/git
-  git clone --recursive "$EXTERNAL_GIT_ROOT" /var/local/git/grpc
+  git clone "$EXTERNAL_GIT_ROOT" /var/local/git/grpc
+  # clone gRPC submodules, use data from locally cloned submodules where possible
+  (cd /var/local/jenkins/grpc / && git submodule foreach 'cd /var/local/git/grpc \
```
Comment (jtattermusch) [inline tools/run_tests/dockerize/docker_run.sh]: you need to honor $EXTERNAL_GIT_ROOT in submodule cloning.

**Comment by matt-kwong** [comment]
The comments I left about files being in /var/local/jenkins/grpc/third_party/boringssl were issues I had when testing locally on my machine because of Docker caching, so this should be ok.

I do think that /var/local/jenkins/grpc is not set up with submodules in one of the Docker setups, causing issues with using this directory as a reference. I am currently investigating this.

File: tools/run_tests/dockerize/docker_run_tests.sh [hunk 12]
```diff
@@ -42,7 +42,21 @@ export PATH=$PATH:/usr/bin/llvm-symbolizer
 chown $(whoami) $XDG_CACHE_HOME
 
 mkdir -p /var/local/git
-git clone --recursive /var/local/jenkins/grpc /var/local/git/grpc
+git clone /var/local/jenkins/grpc /var/local/git/grpc
+
+# (todo (mattkwong): the /var/local/jenkins/grpc has no submodules and boringssl
```
Comment (jtattermusch) [inline tools/run_tests/dockerize/docker_run_tests.sh]: where did you see "has no submodules and boringssl has non-submodule files in it"?

Action for cloning submodules can be set in Jenkins UI (separately for each job), but docker_run_tests.sh is used for running run_tests.py and I'd be surprised if we didn't setup the submodule cloning for some of the jobs. In any case, if it happens, it's jenkins job specific I think.

Comment (matt-kwong) [inline tools/run_tests/dockerize/docker_run_tests.sh]: > where did you see "has no submodules and boringssl has non-submodule files in it"?

This was an issue when I was testing locally on my machine, but I have fixed it - should be unrelated to Jenkins.

The issues I saw with Jenkins that I was investigating was a portability test from a couple days ago: [https://grpc-testing.appspot.com/job/gppr/7281/](https://grpc-testing.appspot.com/job/gppr/7281/). The issue with the 4 failing gcc tests is:

Cloning into '/var/local/git/grpc'...
done.
Entering 'third_party/boringssl'
Submodule 'third_party/boringssl' (https://github.com/google/boringssl.git) registered for path 'third_party/boringssl'
fatal: reference repository '/var/local/jenkins/grpc/third_party/boringssl' is not a local directory.
Cloning into 'third_party/boringssl'...
Clone of 'https://github.com/google/boringssl.git' into submodule path 'third_party/boringssl' failed
Stopping at 'third_party/boringssl'; script returned non-zero status.

I'm currently trying to replicate this in Jenkins, if it will let me, so I can fix it.

**Comment by matt-kwong** [comment]
The issue with submodule cloning with those 4 gcc tests was because the Docker image for those tests used an outdated version of Git that did not support submodule cloning. I changed the Dockerfile for Wheezy to get a newer version.

File: tools/dockerfile/test/cxx_wheezy_x64/Dockerfile [hunk 13]
```diff
@@ -63,6 +63,13 @@ RUN apt-get update && apt-get install -y \
 # Build profiling
 RUN apt-get update && apt-get install -y time && apt-get clean
 
+#================
+# Add backport to Debian sources.list and update git to version > 1.7
+RUN echo "deb http://http.debian.net/debian wheezy-backports main" \
+  >/etc/apt/sources.list.d/wheezy-backports.list
+RUN apt-get update -qq
+RUN apt-get -t wheezy-backports install -y -qq git mercurial
```
Comment (jtattermusch) [inline tools/dockerfile/test/cxx_wheezy_x64/Dockerfile]: Sg, but this file is actually generated from a template.
You need to update the template under /templates and then run `tools/buildgen/generate_projects.sh`  (otherwise you'll break sanity test).

Also, do you really need mercurial?
