### PR TITLE
Make event order consistent, and make 'end' and 'error' mutually exclusive

### LINKED ISSUE #7705: grpc-node doesn't surface error from bidirectional stream.
My code is set up as follows below and after sending a bad request on a bidi stream, the stream ends, but I'm not notified of the error in any way (there's no 'error' or 'status' event; just an 'end' event).  If you need more details, please contact me directly (mikelehen@google.com).

```
var grpc = require('grpc');

var proto = grpc.load({root:"...", file: "..."})

var service = new proto.blah.Service('localhost:8080', grpc.credentials.createInsecure());
var stream = service['streamingAPI']();

stream.on('error', (error) => {
    console.log('ERROR:', error);
});

stream.on('status', (status) => {
    console.log('STATUS:', status);
});

stream.on('end', () => {
    console.log('ENDED!');
});

stream.on('data', (data) => {
    console.log('DATA:', data);
});

var BAD_REQUEST = { ... };
stream.write(BAD_REQUEST);
```

### PR DESCRIPTION
**Pull request by murgatroid99**
This PR has two different but related changes. The first makes the order in which events are emitted consistent across call types: first the `metadata` event is emitted, then later the `error` event is emitted if there is an error, and finally the `status` event is emitted. This has the effect of ensuring that the same event, `status` is consistently emitted after everything else in every call. This fixes #7705.

The second change ensures that the `end` and the `error` events are mutually exclusive. Since `error` events could already happen at any time, it was already theoretically possible to have `error` events without `end` events. But when handling completed calls that finished with non-OK status, we were always emitting both. According to #8954, some common libraries expect the former behavior, and this change ensures that that is always the case.

### CODE REVIEW

File: src/node/src/client.js [hunk 1]
```diff
@@ -184,14 +184,15 @@ function _emitStatusIfDone() {
     } else {
       status = this.received_status;
     }
-    this.emit('status', status);
-    if (status.code !== grpc.status.OK) {
+    if (status.code === grpc.status.OK) {
+      this.push(null);
```
Comment (apolcyn) [inline src/node/src/client.js]: this is causing 'end' event to be emitted?

File: src/node/src/client.js [hunk 2]
```diff
@@ -224,9 +225,11 @@ function _read(size) {
     } catch (e) {
       self._readsDone({code: grpc.status.INTERNAL,
                        details: 'Failed to parse server response'});
+      return;
```
Comment (apolcyn) [inline src/node/src/client.js]: returning here finishes to emit `error`/`status` and avoid events in future reads?

Comment (murgatroid99) [inline src/node/src/client.js]: Returning here just makes sure that we don't fall through to `self.push(deserialized)`, which we don't want because this is the case where deserialization failed.

File: src/node/src/client.js (hunk 1 above)
Comment (murgatroid99) [inline src/node/src/client.js]: Yes. Pushing `null` signifies the end of the stream, which causes the `end` event to be emitted.
