### PR TITLE
Fix race between destroying call after status and handling write failure

### LINKED ISSUE #11036: Node: Server crashed will cause Client segmentation fault in grpc 1.3.0+
I have used gRPC 1.3.0+ in NodeJS.

Server and Client communicate each other by gRPC stream.

If Server crashed, the Client cloud catch 'Endpoint read failed' error ,and then Client was segmentation fault .

After I change gRPC version to 1.0.0, there is not found this problem.

### PR DESCRIPTION
**Pull request by murgatroid99**
I recently added some code in the Node extension to destroy the core call object after it is complete to avoid memory leaks in case garbage collection doesn't run for a while. However, this caused races with code that attempted to write request messages that would be sent after the call received a status, resulting in segfaults as reported in #11036. This change forces the previous behavior of ignoring any request messages that are written after status was received.

This fixes #11036.

### CODE REVIEW

File: src/node/src/client.js [hunk 1]
```diff
@@ -119,8 +125,10 @@ function _write(chunk, encoding, callback) {
   batch[grpc.opType.SEND_MESSAGE] = message;
   this.call.startBatch(batch, function(err, event) {
     if (err) {
-      // Something has gone wrong. Stop writing by failing to call callback
-      return;
+      /* Assume that the call is complete and that writing failed because a
+         status was received. In that case, set a flag to discard all future
+         writes */
+      self.writeFailed = true;
```
Comment (apolcyn) [inline src/node/src/client.js]: should writeFailed also be set after `cancelWithStatus` in the exception above?

File: src/node/ext/call.cc [hunk 2]
```diff
@@ -721,6 +721,14 @@ NAN_METHOD(Call::StartBatch) {
   }
   Local<Function> callback_func = info[1].As<Function>();
   Call *call = ObjectWrap::Unwrap<Call>(info.This());
+  if (call->wrapped_call == NULL) {
```
Comment (apolcyn) [inline src/node/ext/call.cc]: I'm not sure about this but am wondering about one other thing:
if the `NULL` check of `call->wrapped_call` was atomic with the pending batches increment, then I think the `writeFailed` flag could be gotten rid of

**Comment by murgatroid99** [comment]
UBsan doesn't seem to run properly on 1.3.x.

**Comment by assaf-xm** [comment]
I think we have the same issue or very similar issue.
When upgrading to 1.2.0 or 1.3.2 our node.js (ubuntu 16.04) client gets segfaults when server service stops. The server is running C#. All works with older versions (GRPC v1.1.4)

We tried the v1.3.x branch latest which include this fix (commit 866190f), however this doesn't solve our issue.
Building with --debug shows the following stack trace:

Thread 1 "node" received signal SIGSEGV, Segmentation fault.
0x00007fef62cb918c in gpr_ref_non_zero (r=0x618) at ../src/core/lib/support/sync.c:105
105	  gpr_atm prior = gpr_atm_no_barrier_fetch_add(&r->count, 1);
(gdb) info frame
Stack level 0, frame at 0x7ffd38c061c0:
 rip = 0x7fef62cb918c in gpr_ref_non_zero (../src/core/lib/support/sync.c:105); saved rip = 0x7fef62c62d92
 called by frame at 0x7ffd38c061e0
 source language c.
 Arglist at 0x7ffd38c061b0, args: r=0x618
 Locals at 0x7ffd38c061b0, Previous frame's sp is 0x7ffd38c061c0
 Saved registers:
  rbp at 0x7ffd38c061b0, rip at 0x7ffd38c061b8
(gdb) bt
#0  0x00007fef62cb918c in gpr_ref_non_zero (r=0x618) at ../src/core/lib/support/sync.c:105
#1  0x00007fef62c62d92 in grpc_stream_ref (refcount=0x618) at ../src/core/lib/transport/transport.c:58
#2  0x00007fef62c50ff4 in grpc_call_internal_ref (c=0x0) at ../src/core/lib/surface/call.c:471
#3  0x00007fef62c5192d in cancel_with_error (exec_ctx=0x7ffd38c06250, c=0x0, source=STATUS_FROM_API_OVERRIDE, error=0x4) at ../src/core/lib/surface/call.c:633
#4  0x00007fef62c51610 in grpc_call_cancel (call=0x0, reserved=0x0) at ../src/core/lib/surface/call.c:570
#5  0x00007fef62c1fb37 in grpc::node::Call::Cancel (info=...) at ../src/node/ext/call.cc:797
#6  0x00007fef62c1cacc in Nan::imp::FunctionCallbackWrapper (info=...) at ../../nan/nan_callbacks_12_inl.h:174
#7  0x0000000000981681 in v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) ()
#8  0x00000000009d5b0b in v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>) ()
#9  0x00000000009d60b1 in v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) ()


Further debugging shows that 'call.cc' line 797  called:
     grpc_call_error error = grpc_call_cancel(call->wrapped_call, NULL);
when 'call->wrapped_call' is NULL.
Protecting null value there solved the crash, but is probably partial solution.
