### PR TITLE
Expose trailers-only response status through C++ callback API

### LINKED ISSUE #14467: allow gRPC-level proxies to support retries
Currently, a gRPC-level proxy written in C++ (or even directly against C-core) cannot easily support retries, because when it gets a trailers-only response from the backend, it will generate separate send_initial_metadata and send_trailing_metadata ops to return the result to the client.

The proxy code can do some extra work, such as implementing their own delay after seeing initial metadata in order to see if trailing metadata is returned shortly thereafter.  However, most proxy authors will not realize they need to do this, which means they're going to get it wrong, and there are also performance implications.  So it's not a very good solution.

We need to think about better ways to fix this problem.  One possible option is to add a piece of initial metadata that tells the transport that trailing metadata will quickly follow.

CC @dfawley, since the same problem exists in Go.

### PR DESCRIPTION
**Pull request by vjpai**
Fixes #14467.

We have a customer feature request to expose whether a C++ callback API client-side call received only a trailers-only response. We actually already had this plumbing in the core subsurface but it was not exposed to the C++ layer in any way (or the core surface, for that matter. It has only been used in the filter stack.). This PR:

* Uses the `trailing_metadata_available` field of the `transport_stream_op_batch` on every client call in `call.cc`
* Exposes this value through a subsurface core function. Note that this is not part of the core surface API so it does not need a gRFC. Of course this means that it is only exposed to the C++ layer that can directly call into core subsurface, but that's fine since that's where our feature request lives.
* Checks that value before calling `OnReadInitialMetadataDone` in the C++ callback API layer and sets `ok=false` if that is the case.
* Tests this condition in an end2end test that gets a trailers-only error response

### CODE REVIEW

**Comment by vjpai** [comment]
Looks like this broke the grpc_tool_test so I'll have to see what went wrong.

**Comment by vjpai** [comment]
And it looks like grpc_tool_test is a change detector test on echo.proto, so I'll just fix it up.

File: src/cpp/client/client_context.cc [hunk 1]
```diff
@@ -178,4 +180,10 @@ void ClientContext::SetGlobalCallbacks(GlobalCallbacks* client_callbacks) {
   g_client_callbacks = client_callbacks;
 }
 
+bool ClientContext::trailers_only() const {
+  return initial_metadata_received_ &&
+         recv_initial_metadata_.arr()->count == 0 &&
```
Comment (markdroth) [inline src/cpp/client/client_context.cc:185]: Is there actually any need to check this?  It seems like this will always inherently be true if `grpc_call_is_trailers_only()` returns true.

File: include/grpcpp/impl/codegen/client_callback.h [hunk 2]
```diff
@@ -594,7 +594,7 @@ class ClientCallbackReaderWriterImpl
     start_tag_.Set(
         call_.call(),
         [this](bool ok) {
-          reactor_->OnReadInitialMetadataDone(ok);
+          reactor_->OnReadInitialMetadataDone(ok && !context_->trailers_only());
```
Comment (markdroth) [inline include/grpcpp/impl/codegen/client_callback.h:597]: Do we need to also make this same change for `OnReadDone()`?  Or does it already get ok=false when there is no message to read?

File: src/core/lib/surface/call.h [hunk 3]
```diff
@@ -120,6 +120,9 @@ size_t grpc_call_get_initial_size_estimate();
 grpc_compression_algorithm grpc_call_compression_for_level(
     grpc_call* call, grpc_compression_level level);
 
+/* Did this client call receive a trailers-only response */
+bool grpc_call_is_trailers_only(const grpc_call* call);
```
Comment (markdroth) [inline src/core/lib/surface/call.h:124]: Reaching under the hood to an internal C-core API seems a little messy.  Is there any reason other than short-term expediency why we would want to go with this approach, rather than something like #13423 that actually exposes it in the C-core surface API?

This could be useful for wrapped languages as well; I don't think we've looked at their APIs yet to know whether they need it.  But even if it's used only by C++, it seems like it would be cleaner to go through the C-core API instead of reaching into its internals.

**Review by markdroth — COMMENTED** [review]
Thanks for doing this!

File: src/cpp/client/client_context.cc (hunk 1 above)
Comment (vjpai) [reply src/cpp/client/client_context.cc:185]: You're obviously right. My mental model was that for a 0 message, that init metadata and trailing metadata would be pressed together into the trailers, but that would obviously make any init metadata into trailing metadata. It's almost like we should have a DEBUG_ASSERT in place here to specify that if this is true that the array count had better be 0.

File: include/grpcpp/impl/codegen/client_callback.h (hunk 2 above)
Comment (vjpai) [reply include/grpcpp/impl/codegen/client_callback.h:597]: Yeah, OnReadDone already gets ok=false if there's no message available.

File: src/core/lib/surface/call.h (hunk 3 above)
Comment (vjpai) [reply src/core/lib/surface/call.h:124]: So we already reach into core internals in numerous places in the C++ API (eg closures) because we had decided that the C++ API can be de-wrapped. This function would be easy enough to implement as core surface if the need arises, but I'm gonna cite YAGNI here and suggest that it shouldn't be moved to core surface until there's a blocking feature request for it from some other language that is not de-wrappable. (And there's also the practical issue that I won't be around to write or shepherd any new gRFC for a Core API extension.)

So I'm going to ask if I can push back against this review comment. I'm accepting the other one.

Comment (vjpai) [reply src/core/lib/surface/call.h:124]: That said, thanks for the review!

Comment (markdroth) [reply src/core/lib/surface/call.h:124]: Okay, I guess we can live with this for now.  Please add a TODO about this, though.

Comment (vjpai) [reply src/core/lib/surface/call.h:126]: Done, thanks! Adding it in your name since you'll make the call when it happens.

**Review by markdroth — APPROVED** [review]
Thanks for doing this!

**Comment by vjpai** [comment]
Thanks for the detailed reviews! Need to figure out what's breaking the Android build though (Nexus 6 only so I bet debugging tools might be hard to find)

**Comment by ericgribkoff** [comment]
Android tests passed on the trial run at https://github.com/grpc/grpc/pull/26319. I am unable to reproduce the crash with a local build of the interop app, either on my machine (emulator) or by sending the apks to run on Firebase, which is what our failing CI job is doing.

I _can_ download the apks from the CI build and reproduce the crash on a local emulator, but I haven't figured out how to attach a debugger to these runs with an "external" (not locally built) apk yet.

The fact that the apks built on my machine work fine on devices with API level 21 and 22 might suggest there's some issue with the ndk toolchain that is being used on our Kokoro workers that is not present on an up-to-date install of the Android SDK/NDK. But I haven't come up with a way to test that guess yet.

**Comment by vjpai** [comment]
@ericgribkoff Thanks for all the help debugging. I think that commit f224f1a resolves the issue. It is hard to understand the source - looks more like a compiler error than anything else. Of course, there were known TLS bugs in API < 23 and this is crashing because of a TLS value acting up for API 21 and 22. So maybe that's the source of the problem. No idea why it only popped up now though.
