### PR TITLE
fix for working with compressed data. Fixes #6746.

### LINKED ISSUE #6746: Make ObjC work correctly when receiving a compressed message
See node's fix #6719.

### PR DESCRIPTION
**Pull request by makdharma**
Using correct API that gives length of uncompressed data so correct amount of memory is allocated. Derived from https://github.com/grpc/grpc/pull/6719.

### CODE REVIEW

File: src/objective-c/GRPCClient/private/NSData+GRPC.m [hunk 1]
```diff
@@ -39,17 +39,19 @@
...
   grpc_byte_buffer_reader reader;
   grpc_byte_buffer_reader_init(&reader, buffer);
-  gpr_slice next;
-  while (grpc_byte_buffer_reader_next(&reader, &next) != 0){
-    memcpy(array + offset, GPR_SLICE_START_PTR(next),
-           (size_t)GPR_SLICE_LENGTH(next));
-    offset += GPR_SLICE_LENGTH(next);
-    gpr_slice_unref(next);
+  gpr_slice slice = grpc_byte_buffer_reader_readall(&reader);
+  size_t uncompressed_length = GPR_SLICE_LENGTH(slice);
```
Comment (jcanizales) [inline src/objective-c/GRPCClient/private/NSData+GRPC.m]: Does this mean that `grpc_byte_buffer_reader_readall` is doing decompression, not just copying bytes?

Comment (makdharma) [inline src/objective-c/GRPCClient/private/NSData+GRPC.m]: Yes.

Comment (jcanizales) [inline src/objective-c/GRPCClient/private/NSData+GRPC.m]: Let's add a comment for line 46 making it explicit.

File: src/objective-c/GRPCClient/private/NSData+GRPC.m [hunk 2]
```diff
@@ -39,17 +39,20 @@
...
+                                               size_t *length, char **array) {
   grpc_byte_buffer_reader reader;
   grpc_byte_buffer_reader_init(&reader, buffer);
-  gpr_slice next;
-  while (grpc_byte_buffer_reader_next(&reader, &next) != 0){
-    memcpy(array + offset, GPR_SLICE_START_PTR(next),
-           (size_t)GPR_SLICE_LENGTH(next));
-    offset += GPR_SLICE_LENGTH(next);
-    gpr_slice_unref(next);
+  // The slice contains uncompressed data even if compressed data was received
```
Comment (dgquintas) [inline src/objective-c/GRPCClient/private/NSData+GRPC.m]: I'd add "because the reader takes care of automatically decompressing it".

**Comment by dgquintas** [comment]
LGTM other than my suggestion to expand the comment.

**Comment by jcanizales** [comment]
LGTM

**Comment by makdharma** [comment]
The C++ build failure and ObjC "opt" test failure are unrelated. Marking ready to merge.

**Comment by jcanizales** [comment]
Please wait for the Travis tests to complete.

**Comment by jcanizales** [comment]
Oh, they were rerun because you pushed a new commit; I see.

File: src/objective-c/GRPCClient/private/NSData+GRPC.m [hunk 3]
```diff
@@ -71,7 +71,7 @@ + (instancetype)grpc_dataWithByteBuffer:(grpc_byte_buffer *)buffer {
   }
   char *array;
   NSUInteger length;
-  MallocAndCopyByteBufferToCharArray(buffer, &length, &array);
+  MallocAndCopyByteBufferToCharArray(buffer, (size_t *)&length, &array);
```
Comment (jcanizales) [inline src/objective-c/GRPCClient/private/NSData+GRPC.m]: This fools `MallocAndCopyByteBufferToCharArray` into thinking it can write memory beyond what is allocated in the stack for `length` (`NSUInteger` is an `int` and `size_t` is a `long`). Because the size of the response is controlled by the server (and more so because `MallocAndCopyByteBufferToCharArray` is decompressing), it makes a server able to crash the client, which is a bug.

**Comment by makdharma** [comment]
test this please

**Comment by makdharma** [comment]
test this please

**Comment by makdharma** [comment]
test this please
