### PR TITLE
Fix possible deadlock in RemoveExternalConnectivityWatcher

### LINKED ISSUE #23366: Possible deadlock in RemoveExternalConnectivityWatcher
Internal reference - b/159559055

The issue is that inside the mutex protected critical region of RemoveExternalConnectivityWatcher, we call Cancel on the ExternalConnectivityWatcher. This Cancel call jumps into WorkSerializer which is unsafe since the lambda executed by the WorkSerializer might end up calling RemoveExternalConnectivityWatcher again leading to a deadlock.

### PR DESCRIPTION
**Pull request by yashykt**
Internal reference - b/159559055
Fix #23366

### CODE REVIEW

File: src/core/ext/filters/client_channel/client_channel.cc [hunk 1]
```diff
@@ -184,12 +184,16 @@ class ChannelData {
...
+    ExternalConnectivityWatcher* watcher = nullptr;
+    {
+      MutexLock lock(&external_watchers_mu_);
+      auto it = external_watchers_.find(on_complete);
+      if (it != external_watchers_.end()) {
+        watcher = it->second;
+        external_watchers_.erase(it);
+      }
     }
+    if (watcher != nullptr && cancel) watcher->Cancel();
```
Comment (markdroth) [inline src/core/ext/filters/client_channel/client_channel.cc:196]: Please add a comment here indicating that `Cancel()` will hop into the `WorkSerializer`, so we can't be holding the mutex when we call it.

**Comment by yashykt** [comment]
Thanks for reviewing!

File: src/core/ext/filters/client_channel/client_channel.cc (hunk 1 above)
Comment (yashykt) [reply src/core/ext/filters/client_channel/client_channel.cc:198]: added
