### PR TITLE
Write stalling fix

### LINKED ISSUE #15889: gRPC channels blocking indefinitely and not respecting deadlines on network disconnect
### What version of gRPC and what language are you using?
gRPC==1.12.1
python
 
### What operating system (Linux, Windows, …) and version?
Linux Ubuntu "14.04.5 LTS, Trusty Tahr"
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc==4:4.8.2-1ubuntu6
python==2.7
 
### What did you do?
I consistently reproduced a bug that causes gRPC channels to block indefinitely when sending to a destination that continuously times out.

I slightly modified the `greeter_client.py` from [the python helloworld example](https://github.com/grpc/grpc/tree/master/examples/python/helloworld), added an infinite while loop, added a timeout of `0.3` to the `SayHello()` grpc call and added exception handling to catch any `DEADLINE_EXCEEDED` errors.

[Modified greeter_client.py](https://gist.github.com/gaffer-93/d8b9d5d392cc20cf3364b42be981f1f9
)

Running this script and an un-modified `greeter_server.py` (on a different host listening on port 6106) I was able to observe the two communicating as expected.

To reproduce the bug in question, I add an iptables rule to the server side to drop all traffic arriving at the port in use:
`/sbin/iptables -I INPUT 1 -s xx.xxx.xxx.xxx -j DROP`

### What did you expect to see?
Adding the iptables rule results in lots of `DEADLINE_EXCEEDED` (timeout) exceptions as expected.

```
Traceback (most recent call last):
  File "greeter_client.py", line 36, in run
    response = stub.SayHello(helloworld_pb2.HelloRequest(name=msg), timeout=0.3)
  File "/root/.venvs/grpc-test/local/lib/python2.7/site-packages/grpc/_channel.py", line 500, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/root/.venvs/grpc-test/local/lib/python2.7/site-packages/grpc/_channel.py", line 434, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
_Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded)>
```

I expected to see the `greeter_client.py` continue iterating over the `while` loop, timing out in exactly 300ms on every call to `response = stub.SayHello(helloworld_pb2.HelloRequest(name=msg), timeout=0.3)`
 
### What did you see instead?
If you leave the client running with everything in this state, it eventually blocks indefinitely on the send `response = stub.SayHello(helloworld_pb2.HelloRequest(name=msg), timeout=0.3)` and never times out. This is an example of the bug we've been trying to figure out these past few weeks. After some digging we found that the blocking call here is: https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/_channel.py#L508

Once the iptables rule is removed from the server side, the client un-blocks and continues to send.

Now what's interesting is that if you raise the size of the `msg` variable here, to say... `'a' * 1000` the client breaks much _faster_ (starts to block indefinitely). 

On inspection we discovered that when we add the iptables rule to drop the traffic, the `send-q` for the socket in use by the grpc client continues to grow as the client continues to attempt to send and timeout. The `send-q` grows because grpc is buffering the request for sending but never receiving an ack so the data sits there in the queue piling up on every attempt. Until.. the `send-q` seems to reach it's maximum threshold, at which point the client exhibits the indefinite blocking behaviour. We believe the kernel refuses to add any more data to the `send-q` causing grpc to block/spin deep within the C code.

For every reproduction of this, when sending `msg='a'`, *once* the `send-q` hits `33425` the client blocks.

```
root@client-server ~ # netstat -natup | grep 6106
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp6       0  33425 xx.xxx.xxx.xxx:45048    xxx.xxx.xx.xxx:6106     ESTABLISHED 19834/python
```

For larger messages the breaking threshold rises slightly, for example sending `msg='a'*1000`, the `send-q` reaches `46278` *every time* before blocking

```
root@client-server ~ # netstat -natup | grep 6106
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp6       0  46278 xx.xxx.xxx.xxx:36000    xxx.xxx.xx.xxx:6106     ESTABLISHED 27166/python
```
 
### Anything else we should know about your project / environment?
No

### PR DESCRIPTION
**Pull request by kpayson64**
The chttp2 transport would not execute write closures until a write occurred, even if the stream was cancelled.

This PR separates the write callback closure lists based on streams, so they can be run when a cancellation comes in.

Fixes #15889

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.0%     +10 [None]                                                                               +1.31Ki  +0.0%
  +1.7%    +102 src/core/ext/transport/chttp2/transport/writing.cc                                      +102  +1.7%
       +61%    +118 grpc_chttp2_end_write                                                                   +118   +61%
      [NEW]    +117 report_stall(grpc_chttp2_transport*, grpc_chttp2_stream*, char const*) [clone .part.    +117  [NEW]
       +44%     +12 [Unmapped]                                                                               +12   +44%
  +0.3%     +80 src/core/ext/transport/chttp2/transport/chttp2_transport.cc                              +80  +0.3%
      +3.1%     +75 grpc_chttp2_cancel_stream                                                                +75  +3.1%
      +2.9%     +17 grpc_chttp2_complete_closure_step                                                        +17  +2.9%

  +0.0%    +192 TOTAL                                                                                +1.48Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.0%     +34 [None]                                                                               +1.62Ki  +0.0%
  +0.5%    +160 src/core/ext/transport/chttp2/transport/chttp2_transport.cc                             +160  +0.5%
      +8.3%     +87 grpc_chttp2_mark_stream_closed                                                           +87  +8.3%
      +3.1%     +75 grpc_chttp2_cancel_stream                                                                +75  +3.1%
      +2.9%     +17 grpc_chttp2_complete_closure_step                                                        +17  +2.9%
  +1.7%    +102 src/core/ext/transport/chttp2/transport/writing.cc                                      +102  +1.7%
       +61%    +118 grpc_chttp2_end_write                                                                   +118   +61%
      [NEW]    +117 report_stall(grpc_chttp2_transport*, grpc_chttp2_stream*, char const*) [clone .part.    +117  [NEW]
       +44%     +12 [Unmapped]                                                                               +12   +44%

  +0.0%    +296 TOTAL                                                                                +1.88Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                         atm_add_per_iteration
--------------------------------  -----------------------
BM_TransportStreamSend/134217728  -19%
BM_TransportStreamSend/16777216   -19%
BM_TransportStreamSend/2097152    -19%
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.0%     +34 [None]                                                                               +1.61Ki  +0.0%
  +0.5%    +160 src/core/ext/transport/chttp2/transport/chttp2_transport.cc                             +160  +0.5%
      +8.3%     +87 grpc_chttp2_mark_stream_closed                                                           +87  +8.3%
      +3.1%     +75 grpc_chttp2_cancel_stream                                                                +75  +3.1%
      +2.9%     +17 grpc_chttp2_complete_closure_step                                                        +17  +2.9%
  +1.7%    +102 src/core/ext/transport/chttp2/transport/writing.cc                                      +102  +1.7%
       +61%    +118 grpc_chttp2_end_write                                                                   +118   +61%
      [NEW]    +117 report_stall(grpc_chttp2_transport*, grpc_chttp2_stream*, char const*) [clone .part.    +117  [NEW]
       +44%     +12 [Unmapped]                                                                               +12   +44%

  +0.0%    +296 TOTAL                                                                                +1.87Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_chttp2_transport.BM_TransportStreamSend_2097152.counters.new: 1


[microbenchmarks] Performance differences noted:
Benchmark                         atm_add_per_iteration
--------------------------------  -----------------------
BM_TransportStreamSend/134217728  -19%
BM_TransportStreamSend/16777216   -19%
BM_TransportStreamSend/2097152    -19%
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.0%     +18 [None]                                                                               +1.67Ki  +0.0%
  +0.5%    +144 src/core/ext/transport/chttp2/transport/chttp2_transport.cc                             +144  +0.5%
      +3.1%     +75 grpc_chttp2_cancel_stream                                                                +75  +3.1%
      +6.9%     +72 grpc_chttp2_mark_stream_closed                                                           +72  +6.9%
      +2.9%     +17 grpc_chttp2_complete_closure_step                                                        +17  +2.9%
  +1.7%    +102 src/core/ext/transport/chttp2/transport/writing.cc                                      +102  +1.7%
       +61%    +118 grpc_chttp2_end_write                                                                   +118   +61%
      [NEW]    +117 report_stall(grpc_chttp2_transport*, grpc_chttp2_stream*, char const*) [clone .part.    +117  [NEW]
       +44%     +12 [Unmapped]                                                                               +12   +44%

  +0.0%    +264 TOTAL                                                                                +1.91Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                                                                  atm_add_per_iteration    atm_cas_per_iteration    nows_per_iteration
-----------------------------------------------------------------------------------------  -----------------------  -----------------------  --------------------
BM_StreamingPingPongWithCoalescingApi<InProcessCHTTP2, NoOpMutator, NoOpMutator>/0/0/0                              +4%
BM_StreamingPingPongWithCoalescingApi<InProcessCHTTP2, NoOpMutator, NoOpMutator>/0/0/1                              +4%
BM_StreamingPingPongWithCoalescingApi<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/0/0/0                           +4%
BM_StreamingPingPongWithCoalescingApi<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/0/0/1                           +4%
BM_TransportStreamSend/134217728                                                           -19%
BM_TransportStreamSend/16777216                                                            -19%
BM_TransportStreamSend/2097152                                                             -19%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/2097152/2097152                                                                  -14%
BM_UnaryPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/2097152/2097152                                                               -14%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/0/2097152                                                                                    -4%
```

File: src/core/ext/transport/chttp2/transport/chttp2_transport.cc [hunk 1]
```diff
@@ -1205,10 +1205,11 @@ void grpc_chttp2_complete_closure_step(grpc_chttp2_transport* t,
   }
   if (closure->next_data.scratch < CLOSURE_BARRIER_FIRST_REF_BIT) {
     if ((t->write_state == GRPC_CHTTP2_WRITE_STATE_IDLE) ||
-        !(closure->next_data.scratch & CLOSURE_BARRIER_MAY_COVER_WRITE)) {
+        !(closure->next_data.scratch & CLOSURE_BARRIER_MAY_COVER_WRITE) ||
```
Comment (yashykt) [inline src/core/ext/transport/chttp2/transport/chttp2_transport.cc]: so.. run the closure immediately if there is an error (just thinking to myself).. though documentation might help

File: src/core/ext/transport/chttp2/transport/chttp2_transport.cc [hunk 2]
```diff
@@ -2012,6 +2013,7 @@ void grpc_chttp2_cancel_stream(grpc_chttp2_transport* t, grpc_chttp2_stream* s,
   if (!t->is_client && !s->sent_trailing_metadata &&
       grpc_error_has_clear_grpc_status(due_to_error)) {
     close_from_api(t, s, due_to_error);
+    GRPC_CLOSURE_LIST_SCHED(&s->run_after_write);
```
Comment (yashykt) [inline src/core/ext/transport/chttp2/transport/chttp2_transport.cc]: shouldn't be needed right? remove_stream already has it

File: src/core/ext/transport/chttp2/transport/chttp2_transport.cc [hunk 3]
```diff
@@ -2031,6 +2033,8 @@ void grpc_chttp2_cancel_stream(grpc_chttp2_transport* t, grpc_chttp2_stream* s,
     s->seen_error = true;
   }
   grpc_chttp2_mark_stream_closed(t, s, 1, 1, due_to_error);
+  // Make sure any pending write callbacks are flushed
+  GRPC_CLOSURE_LIST_SCHED(&s->run_after_write);
```
Comment (yashykt) [inline src/core/ext/transport/chttp2/transport/chttp2_transport.cc]: same here. remove_stream should run everything

File: src/core/ext/transport/chttp2/transport/writing.cc [hunk 4]
```diff
@@ -609,15 +609,11 @@ grpc_chttp2_begin_write_result grpc_chttp2_begin_write(
     stream_ctx.FlushData();
     stream_ctx.FlushTrailingMetadata();
 
-    if (stream_ctx.stream_became_writable()) {
```
Comment (yashykt) [inline src/core/ext/transport/chttp2/transport/writing.cc]: we don't need to check for stream_became_writable anymore?

File: src/core/ext/transport/chttp2/transport/internal.h [hunk 5]
```diff
@@ -584,6 +584,7 @@ struct grpc_chttp2_stream {
 
   grpc_slice_buffer flow_controlled_buffer;
 
+  grpc_closure_list run_after_write;
```
Comment (yashykt) [inline src/core/ext/transport/chttp2/transport/internal.h]: I'm guessing this is memset to zero and hence does not need to be inited

File: src/core/ext/transport/chttp2/transport/chttp2_transport.cc (hunk 1 above)
Comment (kpayson64) [reply src/core/ext/transport/chttp2/transport/chttp2_transport.cc]: Added a note.

File: src/core/ext/transport/chttp2/transport/chttp2_transport.cc (hunk 2 above)
Comment (kpayson64) [reply src/core/ext/transport/chttp2/transport/chttp2_transport.cc]: Good observation, I've removed it.

File: src/core/ext/transport/chttp2/transport/chttp2_transport.cc (hunk 3 above)
Comment (kpayson64) [reply src/core/ext/transport/chttp2/transport/chttp2_transport.cc]: removed.

File: src/core/ext/transport/chttp2/transport/writing.cc (hunk 4 above)
Comment (kpayson64) [reply src/core/ext/transport/chttp2/transport/writing.cc]: ```stream_became_writable``` is somewhat of a misnomer, it seems to mean a stream was unblocked by flow control for a message.

File: src/core/ext/transport/chttp2/transport/internal.h (hunk 5 above)
Comment (kpayson64) [reply src/core/ext/transport/chttp2/transport/internal.h]: I copied the pattern of the old per-transport ```run_after_write```, and that one is not initialized either.

File: src/core/ext/transport/chttp2/transport/writing.cc (hunk 4 above)
Comment (yashykt) [reply src/core/ext/transport/chttp2/transport/writing.cc]: I guess my question is - was it a mistake to be there earlier?

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.0%     +50 [None]                                                                                 +1010  +0.0%
  +1.7%    +102 src/core/ext/transport/chttp2/transport/writing.cc                                      +102  +1.7%
       +61%    +118 grpc_chttp2_end_write                                                                   +118   +61%
      [NEW]    +117 report_stall(grpc_chttp2_transport*, grpc_chttp2_stream*, char const*) [clone .part.    +117  [NEW]
       +44%     +12 [Unmapped]                                                                               +12   +44%
  +0.3%     +80 src/core/ext/transport/chttp2/transport/chttp2_transport.cc                              +80  +0.3%
      +6.9%     +72 grpc_chttp2_mark_stream_closed                                                           +72  +6.9%
      +2.9%     +17 grpc_chttp2_complete_closure_step                                                        +17  +2.9%

  +0.0%    +232 TOTAL                                                                                +1.16Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

File: src/core/ext/transport/chttp2/transport/writing.cc (hunk 4 above)
Comment (kpayson64) [reply src/core/ext/transport/chttp2/transport/writing.cc]: Before ``` grpc_chttp2_end_write``` would only have an effect for streams that were unblocked by flow control, so it wasn't an issue, just kind of a misnomer of ```writable```.

Now we need to execute the new callback list, so we need to make sure it happens every time.

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                                                                  atm_add_per_iteration    atm_cas_per_iteration    cpu_time    nows_per_iteration    real_time
-----------------------------------------------------------------------------------------  -----------------------  -----------------------  ----------  --------------------  -----------
BM_StreamingPingPong<InProcess, NoOpMutator, NoOpMutator>/32768/2                                                                            -5%                               -5%
BM_StreamingPingPong<MinInProcess, NoOpMutator, NoOpMutator>/262144/1                                                                        -7%                               -7%
BM_StreamingPingPong<MinInProcess, NoOpMutator, NoOpMutator>/262144/2                                                                        -4%                               -4%
BM_StreamingPingPongMsgs<InProcess, NoOpMutator, NoOpMutator>/32768                                                                          -9%                               -9%
BM_StreamingPingPongMsgs<MinInProcess, NoOpMutator, NoOpMutator>/32768                                                                       -4%                               -4%
BM_StreamingPingPongWithCoalescingApi<InProcessCHTTP2, NoOpMutator, NoOpMutator>/0/0/0                              +4%
BM_StreamingPingPongWithCoalescingApi<InProcessCHTTP2, NoOpMutator, NoOpMutator>/0/0/1                              +4%
BM_StreamingPingPongWithCoalescingApi<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/0/0/0                           +4%
BM_StreamingPingPongWithCoalescingApi<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/0/0/1                           +4%
BM_TransportStreamSend/134217728                                                           -19%
BM_TransportStreamSend/16777216                                                            -19%
BM_TransportStreamSend/2097152                                                             -19%
BM_UnaryPingPong<InProcess, NoOpMutator, NoOpMutator>/0/262144                                                                               -4%                               -4%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/2097152/2097152                                                                              -14%
BM_UnaryPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/0/16777216                                                                                +7%
BM_UnaryPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/2097152/2097152                                                                           -15%
```

File: src/core/ext/transport/chttp2/transport/writing.cc (hunk 4 above)
Comment (yashykt) [reply src/core/ext/transport/chttp2/transport/writing.cc]: hmm? but wait. this should again have the same problem. If we run the closures only on grpc_chttp2_begin_write, then it would only be called when there is another write or the previous write completed. Isn't it the same issue all over again?

Comment (kpayson64) [reply src/core/ext/transport/chttp2/transport/writing.cc]: We flush the closures on both ```remove_stream``` and ```grpc_chttp2_end_write```.  In the cancellation case (the case that was broken before), remove_stream will be called, and that will take care of flushing the pending write ops.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                   FILE SIZE
 ++++++++++++++ GROWING                                                     ++++++++++++++
  +0.0%     +18 [None]                                                         +874  +0.0%
  +2.3%    +134 src/core/ext/transport/chttp2/transport/writing.cc             +134  +2.3%
       +61%    +118 grpc_chttp2_end_write                                          +118   +61%
      +0.3%     +16 grpc_chttp2_begin_write                                         +16  +0.3%
  +0.3%     +80 src/core/ext/transport/chttp2/transport/chttp2_transport.cc     +80  +0.3%
      +6.9%     +72 grpc_chttp2_mark_stream_closed                                  +72  +6.9%
      +2.9%     +17 grpc_chttp2_complete_closure_step                               +17  +2.9%

  +0.0%    +232 TOTAL                                                       +1.06Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

File: src/core/ext/transport/chttp2/transport/writing.cc (hunk 4 above)
Comment (kpayson64) [reply src/core/ext/transport/chttp2/transport/writing.cc]: Added back this check.  PTAL

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                   FILE SIZE
 ++++++++++++++ GROWING                                                     ++++++++++++++
  +0.0%     +18 [None]                                                         +874  +0.0%
  +2.3%    +134 src/core/ext/transport/chttp2/transport/writing.cc             +134  +2.3%
       +61%    +118 grpc_chttp2_end_write                                          +118   +61%
      +0.3%     +16 grpc_chttp2_begin_write                                         +16  +0.3%
  +0.3%     +80 src/core/ext/transport/chttp2/transport/chttp2_transport.cc     +80  +0.3%
      +6.9%     +72 grpc_chttp2_mark_stream_closed                                  +72  +6.9%
      +2.9%     +17 grpc_chttp2_complete_closure_step                               +17  +2.9%

  +0.0%    +232 TOTAL                                                       +1.06Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                                                                  atm_add_per_iteration    atm_cas_per_iteration    nows_per_iteration
-----------------------------------------------------------------------------------------  -----------------------  -----------------------  --------------------
BM_StreamingPingPongWithCoalescingApi<InProcessCHTTP2, NoOpMutator, NoOpMutator>/0/0/0                              +4%
BM_StreamingPingPongWithCoalescingApi<InProcessCHTTP2, NoOpMutator, NoOpMutator>/0/0/1                              +4%
BM_StreamingPingPongWithCoalescingApi<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/0/0/0                           +4%
BM_StreamingPingPongWithCoalescingApi<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/0/0/1                           +4%
BM_TransportStreamSend/134217728                                                           -19%
BM_TransportStreamSend/16777216                                                            -19%
BM_TransportStreamSend/2097152                                                             -19%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/2097152/2097152                                                                  -12%
BM_UnaryPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/2097152/2097152                                                               -13%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/2097152                                                                                 -7%
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                                                                        atm_add_per_iteration    atm_cas_per_iteration    nows_per_iteration
-----------------------------------------------------------------------------------------------  -----------------------  -----------------------  --------------------
BM_StreamingPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/16777216/1                                                                         -10%
BM_StreamingPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/2097152/1                                                                          -31%
BM_StreamingPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/2097152/2                                                                          -22%
BM_StreamingPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/16777216/1                                                                      -13%
BM_StreamingPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/2097152/1                                                                       -31%
BM_StreamingPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/2097152/2                                                                       -22%
BM_StreamingPingPongWithCoalescingApi<InProcessCHTTP2, NoOpMutator, NoOpMutator>/0/0/0                                    +4%
BM_StreamingPingPongWithCoalescingApi<InProcessCHTTP2, NoOpMutator, NoOpMutator>/0/0/1                                    +4%
BM_StreamingPingPongWithCoalescingApi<InProcessCHTTP2, NoOpMutator, NoOpMutator>/2097152/1/0                                                       -14%
BM_StreamingPingPongWithCoalescingApi<InProcessCHTTP2, NoOpMutator, NoOpMutator>/2097152/2/0                                                       -22%
BM_StreamingPingPongWithCoalescingApi<InProcessCHTTP2, NoOpMutator, NoOpMutator>/2097152/2/1                                                       -22%
BM_StreamingPingPongWithCoalescingApi<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/0/0/0                                 +4%
BM_StreamingPingPongWithCoalescingApi<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/0/0/1                                 +4%
BM_StreamingPingPongWithCoalescingApi<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/2097152/1/0                                                    -15%
BM_StreamingPingPongWithCoalescingApi<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/2097152/2/0                                                    -20%
BM_StreamingPingPongWithCoalescingApi<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/2097152/2/1                                                    -22%
BM_TransportStreamSend/134217728                                                                 -19%
BM_TransportStreamSend/16777216                                                                  -19%
BM_TransportStreamSend/2097152                                                                   -19%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/2097152/2097152                                                                        -13%
BM_UnaryPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/16777216/16777216                                                                   -5%
BM_UnaryPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/2097152/2097152                                                                     -14%
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                   FILE SIZE
 ++++++++++++++ GROWING                                                     ++++++++++++++
  +0.0%     +42 [None]                                                         +458  +0.0%
  +2.3%    +134 src/core/ext/transport/chttp2/transport/writing.cc             +134  +2.3%
       +61%    +118 grpc_chttp2_end_write                                          +118   +61%
      +0.3%     +16 grpc_chttp2_begin_write                                         +16  +0.3%
  +0.1%     +16 src/core/ext/transport/chttp2/transport/chttp2_transport.cc     +16  +0.1%
      +2.9%     +17 grpc_chttp2_complete_closure_step                               +17  +2.9%
      +1.0%     +11 grpc_chttp2_mark_stream_closed                                  +11  +1.0%
       +14%      +7 grpc_chttp2_mark_stream_writable                                 +7   +14%

  +0.0%    +192 TOTAL                                                          +608  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE                                    FILE SIZE
 ++++++++++++++ GROWING                      ++++++++++++++
  +4.3%      +4 src/cpp/common/version_cc.cc      +4  +4.3%
      +8.7%      +4 grpc::Version[abi:cxx11]          +4  +8.7%

 -+-+-+-+-+-+-+ MIXED                        +-+-+-+-+-+-+-
  -0.0%      -4 [None]                           +12  +0.0%

  [ = ]       0 TOTAL                            +16  +0.0%



```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                   FILE SIZE
 ++++++++++++++ GROWING                                                     ++++++++++++++
  +0.0%     +26 [None]                                                         +682  +0.0%
  +2.3%    +134 src/core/ext/transport/chttp2/transport/writing.cc             +134  +2.3%
       +61%    +118 grpc_chttp2_end_write                                          +118   +61%
      +0.3%     +16 grpc_chttp2_begin_write                                         +16  +0.3%
  +0.1%     +32 src/core/ext/transport/chttp2/transport/chttp2_transport.cc     +32  +0.1%
      +2.9%     +17 grpc_chttp2_complete_closure_step                               +17  +2.9%
      +1.0%     +11 grpc_chttp2_mark_stream_closed                                  +11  +1.0%
       +14%      +7 grpc_chttp2_mark_stream_writable                                 +7   +14%

  +0.0%    +192 TOTAL                                                          +848  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_fullstack_trickle.BM_PumpUnbalancedUnary_Trickle_1_16777216_67108864.opt.new: 4
    bm_fullstack_trickle.BM_PumpUnbalancedUnary_Trickle_1_16777216_262144.opt.new: 4
    bm_fullstack_trickle.BM_PumpUnbalancedUnary_Trickle_16777216_16777216_262144.opt.new: 4
    bm_fullstack_trickle.BM_PumpUnbalancedUnary_Trickle_16777216_16777216_67108864.opt.new: 4
    bm_fullstack_trickle.BM_PumpUnbalancedUnary_Trickle_16777216_16777216_4194304.opt.new: 4
    bm_fullstack_trickle.BM_PumpUnbalancedUnary_Trickle_1_16777216_4194304.opt.new: 4


[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                   FILE SIZE
 ++++++++++++++ GROWING                                                     ++++++++++++++
  +0.0%     +10 [None]                                                         +834  +0.0%
  +2.3%    +134 src/core/ext/transport/chttp2/transport/writing.cc             +134  +2.3%
       +61%    +118 grpc_chttp2_end_write                                          +118   +61%
      +0.3%     +16 grpc_chttp2_begin_write                                         +16  +0.3%
  +0.4%    +112 src/core/ext/transport/chttp2/transport/chttp2_transport.cc    +112  +0.4%
      +9.4%     +99 grpc_chttp2_mark_stream_closed                                  +99  +9.4%
      +2.9%     +17 grpc_chttp2_complete_closure_step                               +17  +2.9%
       +14%      +7 grpc_chttp2_mark_stream_writable                                 +7   +14%

  +0.0%    +256 TOTAL                                                       +1.05Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                   FILE SIZE
 ++++++++++++++ GROWING                                                     ++++++++++++++
  +0.0%     +26 [None]                                                         +866  +0.0%
  +2.3%    +134 src/core/ext/transport/chttp2/transport/writing.cc             +134  +2.3%
       +61%    +118 grpc_chttp2_end_write                                          +118   +61%
      +0.3%     +16 grpc_chttp2_begin_write                                         +16  +0.3%
  +0.4%    +128 src/core/ext/transport/chttp2/transport/chttp2_transport.cc    +128  +0.4%
      +9.4%     +99 grpc_chttp2_mark_stream_closed                                  +99  +9.4%
      +2.9%     +17 grpc_chttp2_complete_closure_step                               +17  +2.9%
       +32%     +16 grpc_chttp2_mark_stream_writable                                +16   +32%

  +0.0%    +288 TOTAL                                                       +1.10Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                   FILE SIZE
 ++++++++++++++ GROWING                                                     ++++++++++++++
  +0.1%    +632 [None]                                                      +2.55Ki  +0.0%
  +6.9%    +128 src/core/ext/transport/chttp2/transport/stream_lists.cc        +128  +6.9%
      [NEW]     +40 grpc_chttp2_list_add_waiting_for_write_stream                   +40  [NEW]
      [NEW]     +40 grpc_chttp2_list_remove_waiting_for_write_stream                +40  [NEW]
       +17%     +22 [Unmapped]                                                      +22   +17%
      +8.5%     +16 stream_list_id_string                                           +16  +8.5%
      [NEW]     +10 grpc_chttp2_list_pop_waiting_for_write_stream                   +10  [NEW]
  +1.8%    +104 src/core/ext/transport/chttp2/transport/writing.cc             +104  +1.8%
       +54%    +104 grpc_chttp2_end_write                                          +104   +54%
  +0.1%     +32 src/core/ext/transport/chttp2/transport/chttp2_transport.cc     +32  +0.1%
       +11%     +62 grpc_chttp2_complete_closure_step                               +62   +11%
      +1.2%     +29 grpc_chttp2_cancel_stream                                       +29  +1.2%
      +1.8%     +19 grpc_chttp2_mark_stream_closed                                  +19  +1.8%

  +0.1%    +896 TOTAL                                                       +2.80Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                   FILE SIZE
 ++++++++++++++ GROWING                                                     ++++++++++++++
  +0.1%    +648 [None]                                                      +2.45Ki  +0.0%
  +0.6%    +176 src/core/ext/transport/chttp2/transport/chttp2_transport.cc    +176  +0.6%
       +27%     +95 set_write_state                                                 +95   +27%
      +6.7%     +39 grpc_chttp2_complete_closure_step                               +39  +6.7%
      +1.2%     +29 grpc_chttp2_cancel_stream                                       +29  +1.2%
      +1.5%     +10 [Unmapped]                                                      +10  +1.5%
      +2.8%      +8 grpc_chttp2_add_ping_strike                                      +8  +2.8%
  +6.9%    +128 src/core/ext/transport/chttp2/transport/stream_lists.cc        +128  +6.9%
      [NEW]     +40 grpc_chttp2_list_add_waiting_for_write_stream                   +40  [NEW]
      [NEW]     +40 grpc_chttp2_list_remove_waiting_for_write_stream                +40  [NEW]
       +17%     +22 [Unmapped]                                                      +22   +17%
      +8.5%     +16 stream_list_id_string                                           +16  +8.5%
      [NEW]     +10 grpc_chttp2_list_pop_waiting_for_write_stream                   +10  [NEW]

  +0.1%    +952 TOTAL                                                       +2.75Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                                                       atm_add_per_iteration
------------------------------------------------------------------------------  -----------------------
BM_StreamCreateSendInitialMetadataDestroy<RepresentativeClientInitialMetadata>  +5%
BM_TransportStreamSend/0                                                        +14%
BM_TransportStreamSend/1                                                        +12%
BM_TransportStreamSend/134217728                                                +9%
BM_TransportStreamSend/16777216                                                 +9%
BM_TransportStreamSend/2097152                                                  +9%
BM_TransportStreamSend/262144                                                   +12%
BM_TransportStreamSend/32768                                                    +12%
BM_TransportStreamSend/4096                                                     +12%
BM_TransportStreamSend/512                                                      +12%
BM_TransportStreamSend/64                                                       +12%
BM_TransportStreamSend/8                                                        +12%
```
