### PR TITLE
PHP: fix some segfaults

### LINKED ISSUE #11632: Memory leak with php extension
Hello,

I have a memory leak with the php extension with this simple code : 
`
$clientRedis = new Serviceredis\ServiceRedisClient('localhost:10000', [
	'credentials' => Grpc\ChannelCredentials::createInsecure(),
]);
`
I think I manage to locate the leak, in `php/lib/Grpc/BaseStub.php` this part in the constructor
` ChannelCredentials::setDefaultRootsPem($ssl_roots);`

Link to this method `PHP_METHOD(ChannelCredentials, setDefaultRootsPem)` in `php/ext/grpc/channel_credentials.c`
There is a malloc there
`default_pem_root_certs = gpr_malloc((pem_roots_length + 1) * sizeof(char));
  memcpy(default_pem_root_certs, pem_roots, pem_roots_length + 1);`
but I can not see free for default_pem_root_certs.

If I comment `ChannelCredentials::setDefaultRootsPem($ssl_roots)` in the constructor i don't have memory leak anymore.

Nginx + php fpm
nginx 1.12.0
php 5.6.30
grpc      1.4.0
protobuf  3.3.2
`
Debian 8.8 / kernel 4.9.0-0.bpo.2-amd64

### LINKED ISSUE #12123: GRPC 1.4.4 for PHP error on Mac OSX (and timeout on Linux)
## MAC OSX
When calling the gRPC libraries on Mac OX, I receive the following error:

```
E0808 14:59:19.592674000 140736785834944 sync_posix.c:60]              assertion failed: pthread_mutex_lock(mu) == 0
/usr/local/bin/phpunit: line 2: 81049 Abort trap: 6           /usr/bin/env php -d allow_url_fopen=On -d detect_unicode=Off /usr/local/Cellar/phpunit/5.3.2/libexec/phpunit-5.3.2.phar "$@"
```

I've also received this error:
```
line 2: 84323 Segmentation fault: 11  /usr/bin/env php -d allow_url_fopen=On -d detect_unicode=Off /usr/local/Cellar/phpunit/5.3.2/libexec/phpunit-5.3.2.phar "$@"
```

To further confuse things, occasionally the tests pass, but a warning is thrown after execution:

```
/usr/local/bin/phpunit: line 2: 84797 Abort trap: 6           /usr/bin/env php -d allow_url_fopen=On -d detect_unicode=Off /usr/local/Cellar/phpunit/5.3.2/libexec/phpunit-5.3.2.phar "$@"
```

This error only takes place on a SPECIFIC TEST, even though there are 5 other tests that all use the GRPC extension. The specific call here is `DLP::ListInfoTypes`. I am looking into this call to find any clues as to why this one would throw an error.

**UPDATE** I also have now received this error

```
Assertion failed: (prior > 0), function gpr_ref_non_zero, file /private/tmp/pear/temp/grpc/src/core/lib/support/sync.c, line 106.
```

## Linux
These [travis builds](https://travis-ci.org/GoogleCloudPlatform/php-docs-samples/builds/262410732) install using `pecl install grpc`, but when the extension is called (the tests that run in the `dlp/` directory), the call hangs and the build times out after 10 minutes.

### PR DESCRIPTION
**Pull request by stanley-cheung**
Fixes #12123 
Fixes #11632

### CODE REVIEW

File: src/php/ext/grpc/channel_credentials.c [hunk 1]
```diff
@@ -116,8 +116,13 @@ PHP_METHOD(ChannelCredentials, setDefaultRootsPem) {
                          "setDefaultRootsPem expects 1 string", 1 TSRMLS_CC);
     return;
   }
-  default_pem_root_certs = gpr_malloc((pem_roots_length + 1) * sizeof(char));
-  memcpy(default_pem_root_certs, pem_roots, pem_roots_length + 1);
+  char *default_certs = php_grpc_get_default_pem_root_certs(TSRMLS_C);
+  if (default_certs == NULL) {
```
Comment (stanley-cheung) [inline src/php/ext/grpc/channel_credentials.c]: Need to fix this, in case the incoming parameter is different from what we saved

File: src/php/ext/grpc/php_grpc.h [hunk 2]
```diff
@@ -91,8 +92,13 @@ ZEND_END_MODULE_GLOBALS(grpc)
 #define GRPC_G(v) (grpc_globals.v)
 #endif
 
+ZEND_DECLARE_MODULE_GLOBALS(grpc)
```
Comment (kpayson64) [inline src/php/ext/grpc/php_grpc.h]: I'm not certain, but I feel like doing this in a ```.h``` files might have weird side effects.

File: src/php/ext/grpc/channel_credentials.c (hunk 1 above)
Comment (kpayson64) [inline src/php/ext/grpc/channel_credentials.c]: I don't understand this change.

AFAICT, you've added a "PHP global" for pem root certs, will set that the first time this function gets called, and subsequent calls to this function will do nothing.

Is that the intended behavior?  Also, if that's whats needed, wouldn't it be simpler to  use ```default_pem_root_certs``` to determine if it has been set?

File: src/php/ext/grpc/channel.c [hunk 3]
```diff
@@ -288,7 +289,9 @@ PHP_METHOD(Channel, __construct) {
   }
   channel->wrapper = malloc(sizeof(grpc_channel_wrapper));
   channel->wrapper->key = key;
-  channel->wrapper->target = target;
+  char *target_cpy = malloc(target_length + 1);
```
Comment (stanley-cheung) [inline src/php/ext/grpc/channel.c]: Using `strdup()` now

File: src/php/ext/grpc/channel.c [hunk 4]
```diff
@@ -431,6 +434,7 @@ PHP_METHOD(Channel, close) {
   gpr_mu_lock(&channel->wrapper->mu);
   if (channel->wrapper->wrapped != NULL) {
     grpc_channel_destroy(channel->wrapper->wrapped);
+    free(channel->wrapper->target);
```
Comment (stanley-cheung) [inline src/php/ext/grpc/channel.c]: The `key` is used to search through the list, not the `target`, which is part of the `key`

File: src/php/ext/grpc/php_grpc.h (hunk 2 above)
Comment (stanley-cheung) [inline src/php/ext/grpc/php_grpc.h]: Undid this, as I no longer used this `globals` mechanism.

File: src/php/ext/grpc/channel_credentials.c (hunk 1 above)
Comment (stanley-cheung) [inline src/php/ext/grpc/channel_credentials.c]: This has been done in a different way now. The certs string is stored in the "persistent list", similarly to persistent channel. Everytime we call `setDefaultRootPem`, we check the persistent list. If it exists, we retrieve it and compare it to the incoming parameter. If they are different, I update the persistent list. 

Previously we just store the char pointer in a variable and apparently PHP will somehow corrupt the pointer once in a while so I cannot use a simple variable.

File: src/php/ext/grpc/channel_credentials.c [hunk 5]
```diff
@@ -100,6 +113,27 @@ zval *grpc_php_wrap_channel_credentials(grpc_channel_credentials *wrapped,
...
+                                       php_grpc_int pem_roots_length
+                                       TSRMLS_DC) {
+
+  php_grpc_zend_resource new_rsrc;
+  channel_credentials_persistent_le_t *le;
+  php_grpc_int key_len = strlen(persistent_list_key);
+  new_rsrc.type = le_cc_plink;
+  le = malloc(sizeof(channel_credentials_persistent_le_t));
+
+  char *tmp = malloc(pem_roots_length+1);
```
Comment (kpayson64) [inline src/php/ext/grpc/channel_credentials.c]: Nit:  tmp seems uneeded here, you should be able to put the data directly into ```le->default_root_certs```

Comment (stanley-cheung) [inline src/php/ext/grpc/channel_credentials.c]: Fixed. thanks.
