### PR TITLE
Resolve delayed callback crash

### LINKED ISSUE #19290: objc_macos_opt_native failure
https://source.cloud.google.com/results/invocations/bd0fab0f-0819-4087-8200-eee982b71416/targets/github%2Fgrpc%2Fobjc_macos_opt_native/tests

```
Test Case '-[InteropTestsRemote testResponsesOver4MBAreAcceptedIfOptedIn]' started.
<unknown>:0: error: -[InteropTestsRemote testResponsesOver4MBAreAcceptedIfOptedIn] : Asynchronous wait failed: Exceeded timeout of 32 seconds, with unfulfilled expectations: "HigherResponseSizeLimit".
Test Case '-[InteropTestsRemote testResponsesOver4MBAreAcceptedIfOptedIn]' failed (32.251 seconds).
Test Case '-[InteropTestsRemote testResponsesOverMaxSizeFailWithActionableMessage]' started.
Test Case '-[InteropTestsRemote testResponsesOverMaxSizeFailWithActionableMessage]' passed (0.299 seconds).
Test Case '-[InteropTestsRemote testRPCAfterClosingOpenConnections]' started.
2019-06-07 08:49:43.877012-0700 xctest[24485:201360] *** Assertion failure in -[XCTestCase _enqueueFailureWithDescription:inFile:atLine:expected:breakWhenDequeued:](), /Library/Caches/com.apple.xbs/Sources/XCTest_Sim/XCTest-13764/Sources/XCTestFramework/Core/XCTestCase.m:399
2019-06-07 08:49:43.877667-0700 xctest[24485:201360] *** Assertion failure in -[XCTestCase _enqueueFailureWithDescription:inFile:atLine:expected:breakWhenDequeued:](), /Library/Caches/com.apple.xbs/Sources/XCTest_Sim/XCTest-13764/Sources/XCTestFramework/Core/XCTestCase.m:399
2019-06-07 08:49:43.889379-0700 xctest[24485:201360] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unable to report test assertion failure '((error) == nil) failed: throwing "Unable to report test assertion failure '((error) == nil) failed: "Error Domain=io.grpc Code=1 "{"created":"@1559922583.875487000","description":"Error received from peer ipv6:[2607:f8b0:4002:c0f::451]:443","file":"/Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_opt_native/src/core/lib/surface/call.cc","file_line":1052,"grpc_message":"Cancelled","grpc_status":1}" UserInfo={io.grpc.HeadersKey={
    "alt-svc" = "quic=\":443\"; ma=2592000; v=\"46,44,43,39\"";
    "content-disposition" = attachment;
    date = "Fri, 07 Jun 2019 15:49:12 GMT";
    "expect-ct" = preload;
}, io.grpc.TrailersKey={
}, NSDebugDescription={"created":"@1559922583.875487000","description":"Error received from peer ipv6:[2607:f8b0:4002:c0f::451]:443","file":"/Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_opt_native/src/core/lib/surface/call.cc","file_line":1052,"grpc_message":"Cancelled","grpc_status":1}, NSLocalizedDescription=Cancelled}" - Finished with unexpected error: Error Domain=io.grpc Code=1 "{"created":"@1559922583.875487000","description":"Error received from peer ipv6:[2607:f8b0:4002:c0f::451]:443","file":"/Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_opt_native/src/core/lib/surface/call.cc","file_line":1052,"grpc_message":"Cancelled","grpc_status":1}" UserInfo={io.grpc.HeadersKey={
    "alt-svc" = "quic=\":443\"; ma=2592000; v=\"46,44,43,39\"";
    "content-disposition" = attachment;
    date = "Fri, 07 Jun 2019 15:49:12 GMT";
    "expect-ct" = preload;
}, io.grpc.TrailersKey={
}, NSDebugDescription={"created":"@1559922583.875487000","description":"Error received from peer ipv6:[2607:f8b0:4002:c0f::451]:443","file":"/Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_opt_native/src/core/lib/surface/call.cc","file_line":1052,"grpc_message":"Cancelled","grpc_status":1}, NSLocalizedDescription=Cancelled}' from /Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_opt_native/src/objective-c/tests/InteropTests/InteropTests.m:713 because it was raised inside test case -[InteropTestsRemote testResponsesOver4MBAreAcceptedIfOptedIn] which has no associated XCTestRun object. This may happen when test cases are constructed and invoked independently of standard XCTest infrastructure, or when the test has already finished." - Finished with unexpected error: Error Domain=io.grpc Code=1 "{"created":"@1559922583.875487000","description":"Error received from peer ipv6:[2607:f8b0:4002:c0f::451]:443","file":"/Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_opt_native/src/core/lib/surface/call.cc","file_line":1052,"grpc_message":"Cancelled","grpc_status":1}" UserInfo={io.grpc.HeadersKey={
    "alt-svc" = "quic=\":443\"; ma=2592000; v=\"46,44,43,39\"";
    "content-disposition" = attachment;
    date = "Fri, 07 Jun 2019 15:49:12 GMT";
    "expect-ct" = preload;
}, io.grpc.TrailersKey={
}, NSDebugDescription={"created":"@1559922583.875487000","description":"Error received from peer ipv6:[2607:f8b0:4002:c0f::451]:443","file":"/Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_opt_native/src/core/lib/surface/call.cc","file_line":1052,"grpc_message":"Cancelled","grpc_status":1}, NSLocalizedDescription=Cancelled}' from /Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_opt_native/src/objective-c/tests/InteropTests/InteropTests.m:713 because it was raised inside test case -[InteropTestsRemote testResponsesOver4MBAreAcceptedIfOptedIn] which has no associated XCTestRun object. This may happen when test cases are constructed and invoked independently of standard XCTest infrastructure, or when the test has already finished.'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000107fa429b __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000107540735 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000107fa4022 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x0000000106e03c10 -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 166
	4   XCTest                              0x000000010741378f -[XCTestCase _enqueueFailureWithDescription:inFile:atLine:expected:breakWhenDequeued:] + 1034
	5   XCTest                              0x000000010741cf6c _XCTFailureHandler + 408
	6   InteropTests                        0x000000011f2855af __56-[InteropTests testResponsesOver4MBAreAcceptedIfOptedIn]_block_invoke + 1983
	7   InteropTests                        0x000000011f44da75 __43+[GRXWriteable writeableWithSingleHandler:]_block_invoke + 139
	8   InteropTests                        0x000000011f44dbe4 __43+[GRXWriteable writeableWithSingleHandler:]_block_invoke.11 + 62
	9   InteropTests                        0x000000011f44c3f2 __42-[GRXConcurrentWriteable cancelWithError:]_block_invoke + 86
	10  libdispatch.dylib                   0x000000010a0fb51d _dispatch_call_block_and_release + 12
	11  libdispatch.dylib                   0x000000010a0fc587 _dispatch_client_callout + 8
	12  libdispatch.dylib                   0x000000010a1083bc _dispatch_main_queue_callback_4CF + 1290
	13  CoreFoundation                      0x0000000107f077f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	14  CoreFoundation                      0x0000000107f01e86 __CFRunLoopRun + 2342
	15  CoreFoundation                      0x0000000107f01221 CFRunLoopRunSpecific + 625
	16  XCTest                              0x00000001074564ad -[XCTWaiter waitForExpectations:timeout:enforceOrder:] + 545
	17  XCTest                              0x00000001074074d5 -[XCTestCase(AsynchronousTesting) _waitForExpectations:timeout:enforceOrder:handler:] + 132
	18  XCTest                              0x000000010740767a -[XCTestCase(AsynchronousTesting) waitForExpectationsWithTimeout:handler:] + 287
	19  InteropTests                        0x000000011f29ff86 -[InteropTests testRPCAfterClosingOpenConnections] + 918
	20  CoreFoundation                      0x0000000107fab11c __invoking___ + 140
	21  CoreFoundation                      0x0000000107fa85b5 -[NSInvocation invoke] + 325
	22  XCTest                              0x0000000107413e30 __24-[XCTestCase invokeTest]_block_invoke + 591
	23  XCTest                              0x000000010745d17e -[XCUITestContext performInScope:] + 183
	24  XCTest                              0x0000000107413bd6 -[XCTestCase invokeTest] + 141
	25  XCTest                              0x0000000107414b97 __26-[XCTestCase performTest:]_block_invoke.369 + 42
	26  XCTest                              0x0000000107461f25 +[XCTContext runInContextForTestCase:block:] + 163
	27  XCTest                              0x0000000107414533 -[XCTestCase performTest:] + 608
	28  XCTest                              0x0000000107410539 __27-[XCTestSuite performTest:]_block_invoke + 363
	29  XCTest                              0x000000010740fea0 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 26
	30  XCTest                              0x000000010741009d -[XCTestSuite performTest:] + 239
	31  XCTest                              0x0000000107410539 __27-[XCTestSuite performTest:]_block_invoke + 363
	32  XCTest                              0x000000010740fea0 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 26
	33  XCTest                              0x000000010741009d -[XCTestSuite performTest:] + 239
	34  XCTest                              0x0000000107410539 __27-[XCTestSuite performTest:]_block_invoke + 363
	35  XCTest                              0x000000010740fea0 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 26
	36  XCTest                              0x000000010741009d -[XCTestSuite performTest:] + 239
	37  XCTest                              0x000000010746964f __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 40
	38  XCTest                              0x000000010742371a -[XCTestObservationCenter _observeTestExecutionForBlock:] + 475
	39  XCTest                              0x00000001074694ee -[XCTTestRunSession runTestsAndReturnError:] + 281
	40  XCTest                              0x00000001073ffaf1 -[XCTestDriver runTestsAndReturnError:] + 314
	41  XCTest                              0x0000000107461190 _XCTestMain + 619
	42  xctest                              0x0000000106adc591 xctest + 9617
	43  libdyld.dylib                       0x000000010a16c551 start + 1
	44  ???                                 0x0000000000000005 0x0 + 5
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Restarting after unexpected exit or crash in InteropTestsRemote/testRPCAfterClosingOpenConnections; summary will include totals from previous launches.
Test Suite 'Selected tests' started at 2019-06-07 08:50:00.342
Test Suite 'InteropTests.xctest' started at 2019-06-07 08:50:00.343
Test Suite 'InteropTestsRemote' started at 2019-06-07 08:50:00.343
2019-06-07 08:50:00.343379-0700 xctest[24495:202579] configureCronet()
2019-06-07 08:50:00.344154-0700 xctest[24495:202579] Documents directory: file:///Users/kbuilder/Library/Developer/CoreSimulator/Devices/C4B43700-33DF-4722-B38A-B0E547903E1A/data/Documents/
[0607/085000.346153:ERROR:dns_config_service_posix.cc(213)] DNS config watch failed to start.
[0607/085000.348535:WARNING:ssl_key_logger.cc(32)] Could not open /Users/kbuilder/Library/Developer/CoreSimulator/Devices/C4B43700-33DF-4722-B38A-B0E547903E1A/data/Documents/key
[0607/085000.349988:ERROR:cronet_environment.mm(147)] Can not start NetLog to /Users/kbuilder/Library/Developer/CoreSimulator/Devices/C4B43700-33DF-4722-B38A-B0E547903E1A/data/Documents/cronet_netlog.json: No such file or directory
Test Case '-[InteropTestsRemote testServerStreamingRPC]' started.
2019-06-07 08:50:00.350587-0700 xctest[24495:202598] DiskCookieStorage changing policy from 2 to 0, cookie file: file:///Users/kbuilder/Library/Developer/CoreSimulator/Devices/C4B43700-33DF-4722-B38A-B0E547903E1A/data/Library/Cookies/xctest.binarycookies
Test Case '-[InteropTestsRemote testServerStreamingRPC]' passed (0.063 seconds).
Test Suite 'InteropTestsRemote' failed at 2019-06-07 08:50:00.414.
	 Executed 27 tests, with 2 failures (0 unexpected) in 0.063 (0.071) seconds
Test Suite 'InteropTests.xctest' failed at 2019-06-07 08:50:00.414.
	 Executed 84 tests, with 2 failures (0 unexpected) in 0.063 (0.072) seconds
Test Suite 'Selected tests' failed at 2019-06-07 08:50:00.415.
	 Executed 84 tests, with 2 failures (0 unexpected) in 0.063 (0.073) seconds
kill -9 `jobs -p` ; echo "EXIT TIME:  $(date)"
jobs -p
date
EXIT TIME:  Fri Jun  7 08:50:06 PDT 2019
```

### PR DESCRIPTION
**Pull request by muxi**
Avoid XCTest throwing failures in a callback after the test case is already done. This will cause tests to crash.

Fixes #19290

### CODE REVIEW

File: src/objective-c/tests/InteropTests/InteropTests.m [hunk 1]
```diff
@@ -701,21 +703,21 @@ - (void)testResponsesOver4MBAreAcceptedIfOptedIn {
...
   RMTSimpleRequest *request = [RMTSimpleRequest message];
   const size_t kPayloadSize = 5 * 1024 * 1024;  // 5MB
   request.responseSize = kPayloadSize;
 
   [GRPCCall setResponseSizeLimit:6 * 1024 * 1024 forHost:[[self class] host]];
-
   [_service unaryCallWithRequest:request
                          handler:^(RMTSimpleResponse *response, NSError *error) {
-                           XCTAssertNil(error, @"Finished with unexpected error: %@", error);
-                           XCTAssertEqual(response.payload.body.length, kPayloadSize);
```
Comment (rmstar) [inline src/objective-c/tests/InteropTests/InteropTests.m]: Don't we need to move this assert to after waitForExpectationsWithTimeout, similar to callError?

File: src/objective-c/tests/InteropTests/InteropTests.m [hunk 2]
```diff
@@ -18,6 +18,8 @@
 
 #import "InteropTests.h"
 
+#import <libkern/OSAtomic.h>
```
Comment (rmstar) [inline src/objective-c/tests/InteropTests/InteropTests.m]: Why do we need to include this header?

Comment (muxi) [reply src/objective-c/tests/InteropTests/InteropTests.m]: Forgot to remove it...

File: src/objective-c/tests/InteropTests/InteropTests.m (hunk 1 above)
Comment (muxi) [reply src/objective-c/tests/InteropTests/InteropTests.m]: The purpose of this test is to test message size filter not get triggered, so this assert is unrelated (the same minimizing test concept).

**Comment by muxi** [comment]
Yes we should fix all others too. Since this particular one is crashing more often than others (probably because it's easier to trigger the CFStream hang) I'll fix this one first then the others.
