### PR TITLE
Node server shutdown improvements

### LINKED ISSUE #10557: grpc::node::Server::ShutdownServer() - Cannot create a handle without a HandleScope
Seen with node v6.9.1 + grpc-1.2.3 at least 3 times, but seems pretty random - I won't be able to extract/post the workload that lead to this, sorry. Hopefully you can think of a simple fix for this. Looks race-condition-ish when garbage collection kicks in?

```
FATAL ERROR: v8::HandleScope::CreateHandle() Cannot create a handle without a HandleScope
 1: node::Abort() [node]
 2: 0x1098b2c [node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: v8::internal::HandleScope::Extend(v8::internal::Isolate*) [node]
 5: v8::EscapableHandleScope::EscapableHandleScope(v8::Isolate*) [node]
 6: grpc::node::Server::ShutdownServer() [/srv/dta-dmack/companion/node_modules/grpc/src/node/extension_binary/grpc_node.node]
 7: grpc::node::Server::~Server() [/srv/dta-dmack/companion/node_modules/grpc/src/node/extension_binary/grpc_node.node]
 8: grpc::node::Server::~Server() [/srv/dta-dmack/companion/node_modules/grpc/src/node/extension_binary/grpc_node.node]
 9: v8::internal::GlobalHandles::DispatchPendingPhantomCallbacks(bool) [node]
10: v8::internal::GlobalHandles::PostGarbageCollectionProcessing(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
11: v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
12: v8::internal::Heap::CollectGarbage(v8::internal::GarbageCollector, char const*, char const*, v8::GCCallbackFlags) [node]
13: v8::internal::Heap::FinalizeIncrementalMarkingIfComplete(char const*) [node]
14: v8::internal::IncrementalMarkingJob::DelayedTask::RunInternal() [node]
15: v8::platform::DefaultPlatform::PumpMessageLoop(v8::Isolate*) [node]
16: node::Start(int, char**) [node]
17: __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
18: 0x7b4f6d [node]
```

### PR DESCRIPTION
**Pull request by murgatroid99**
The main change here is to ensure that the wrapped core server object is destroyed when the JS-level server is shutdown, no matter how it was shutdown. Previously, the wrapped server would be destroyed and set to NULL in the destructor or if `forceShutdown` was called, but not if `tryShutdown` was called. This fixes that.

In order to do that, I refactored some completion handling logic into `CompleteTag`, from the completion queue wrapping code.

This also fixes #10557.

### CODE REVIEW

**Comment by murgatroid99** [comment]
The bazel basic build failure is #10553. The performance failure is #9399.

File: src/node/ext/server.cc [hunk 1]
```diff
@@ -242,7 +277,9 @@ NAN_METHOD(Server::TryShutdown) {
     return Nan::ThrowTypeError("tryShutdown can only be called on a Server");
   }
   Server *server = ObjectWrap::Unwrap<Server>(info.This());
+  TryShutdownOp *op = new TryShutdownOp(server, info.This());
```
Comment (apolcyn) [inline src/node/ext/server.cc]: it seems like `TryShutdown` ends up doing the same thing as `ForceShutdown`, except that there's no call to `grpc_server_cancel_all_calls(this->wrapped_server);`. But `TryShutdown` ends up using the `OnComplete` op callback while `ForceShutdown` is using the tag's callback. Is it possible for `TryShutdown` to also use the tag callback?

Comment (murgatroid99) [inline src/node/ext/server.cc]: The issue is that `TryShutdown` already uses the tag callback for the callback that the user passes to the function. That's why I needed the `OnComplete` op callback to do my own cleanup. But after you said this, I realized I could use the `OnComplete` op callback for `ForceShutdown` too.

Comment (apolcyn) [inline src/node/ext/server.cc]: should this `TryShutdown` call wrap the whole wrapper inner grpc server shutdown in a null check as in `ShutdownServer`?

File: src/node/ext/server.cc [hunk 2]
```diff
@@ -147,6 +175,13 @@ bool Server::HasInstance(Local<Value> val) {
   return Nan::New(fun_tpl)->HasInstance(val);
 }
 
+void Server::DestroyWrappedServer() {
```
Comment (apolcyn) [inline src/node/ext/server.cc]: related to below comment, the shutdown is wrapped in the null check in the callback but isn't in `TryShutdown`?

mostly wondering if `TryShutdown` can be more similar with `ForceShutdown`

File: src/node/ext/server.cc (hunk 1 above)
Comment (murgatroid99) [inline src/node/ext/server.cc]: Done, basically.

File: src/node/ext/server.cc (hunk 2 above)
Comment (murgatroid99) [inline src/node/ext/server.cc]: I added the NULL check to `tryShutdown`.

**Comment by murgatroid99** [comment]
I think this is in a good state now

File: src/node/ext/call.cc [hunk 3]
```diff
@@ -499,36 +515,36 @@ tag::~tag() {
...
-}
-
-Callback *GetTagCallback(void *tag) {
-  struct tag *tag_struct = reinterpret_cast<struct tag *>(tag);
-  return tag_struct->callback;
-}
-
-void CompleteTag(void *tag) {
-  struct tag *tag_struct = reinterpret_cast<struct tag *>(tag);
+  bool success = error_message == NULL;
```
Comment (apolcyn) [inline src/node/ext/call.cc]: unneeded, just IMO but small comment is `bool success = (error_message == NULL);` for clarity

**Comment by murgatroid99** [comment]
test this please

**Comment by murgatroid99** [comment]
The bazel basic build failure is #10553.
