### PR TITLE
Fix TSAN race in handshakers

### LINKED ISSUE #20986: TSAN race in handshakers
```
WARNING: ThreadSanitizer: data race (pid=18)
  Write of size 8 at 0x7b50000103c8 by main thread (mutexes: write M2196, write M2194, write M2249, write M2267):
    #0 grpc_core::(anonymous namespace)::SecurityHandshaker::CleanupArgsForFailureLocked() /proc/self/cwd/src/core/lib/security/transport/security_handshaker.cc:179:19 (h2_ssl_proxy_test+0x7ea0b2)
    #1 grpc_core::(anonymous namespace)::SecurityHandshaker::Shutdown(grpc_error*) /proc/self/cwd/src/core/lib/security/transport/security_handshaker.cc:436:5 (h2_ssl_proxy_test+0x7e981c)
    #2 grpc_core::HandshakeManager::Shutdown(grpc_error*) /proc/self/cwd/src/core/lib/channel/handshaker.cc:119:33 (h2_ssl_proxy_test+0xc72bc3)
    #3 chttp2_connector_shutdown(grpc_connector*, grpc_error*) /proc/self/cwd/src/core/ext/transport/chttp2/client/chttp2_connector.cc:82:23 (h2_ssl_proxy_test+0x84b8b2)
    #4 grpc_connector_shutdown(grpc_connector*, grpc_error*) /proc/self/cwd/src/core/ext/filters/client_channel/connector.cc:40:3 (h2_ssl_proxy_test+0x8bb307)
    #5 grpc_core::Subchannel::Disconnect() /proc/self/cwd/src/core/ext/filters/client_channel/subchannel.cc:1078:3 (h2_ssl_proxy_test+0x884883)
    #6 grpc_core::Subchannel::Unref(char const*, int, char const*) /proc/self/cwd/src/core/ext/filters/client_channel/subchannel.cc:712:5 (h2_ssl_proxy_test+0x884664)
    #7 grpc_core::(anonymous namespace)::ChannelData::SubchannelWrapper::~SubchannelWrapper() /proc/self/cwd/src/core/ext/filters/client_channel/client_channel.cc:886:5 (h2_ssl_proxy_test+0x866ee6)
    #8 grpc_core::(anonymous namespace)::ChannelData::SubchannelWrapper::~SubchannelWrapper() /proc/self/cwd/src/core/ext/filters/client_channel/client_channel.cc:869:24 (h2_ssl_proxy_test+0x866fdf)
    #9 grpc_core::RefCounted<grpc_core::SubchannelInterface, grpc_core::PolymorphicRefCount>::Unref() /proc/self/cwd/./src/core/lib/gprpp/ref_counted.h:270:7 (h2_ssl_proxy_test+0x6dc599)
    #10 grpc_core::RefCountedPtr<grpc_core::SubchannelInterface>::reset(grpc_core::SubchannelInterface*) /proc/self/cwd/./src/core/lib/gprpp/ref_counted_ptr.h:110:36 (h2_ssl_proxy_test+0x6dc4d1)
    #11 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelList, grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData>::UnrefSubchannelLocked(char const*) /proc/self/cwd/./src/core/ext/filters/client_channel/lb_policy/subchannel_list.h:291:17 (h2_ssl_proxy_test+0x6d6a35)
    #12 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelList, grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData>::ShutdownLocked() /proc/self/cwd/./src/core/ext/filters/client_channel/lb_policy/subchannel_list.h:343:3 (h2_ssl_proxy_test+0x6d6862)
    #13 grpc_core::SubchannelList<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelList, grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData>::ShutdownLocked() /proc/self/cwd/./src/core/ext/filters/client_channel/lb_policy/subchannel_list.h:439:9 (h2_ssl_proxy_test+0x6d6641)
    #14 grpc_core::SubchannelList<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelList, grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData>::Orphan() /proc/self/cwd/./src/core/ext/filters/client_channel/lb_policy/subchannel_list.h:196:5 (h2_ssl_proxy_test+0x6d2c8f)
    #15 void grpc_core::OrphanableDelete::operator()<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelList>(grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelList*) /proc/self/cwd/./src/core/lib/gprpp/orphanable.h:63:8 (h2_ssl_proxy_test+0x6d06ba)
    #16 std::unique_ptr<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelList, grpc_core::OrphanableDelete>::reset(grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelList*) /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/unique_ptr.h:344:4 (h2_ssl_proxy_test+0x6d1dbd)
    #17 grpc_core::(anonymous namespace)::PickFirst::ShutdownLocked() /proc/self/cwd/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc:163:20 (h2_ssl_proxy_test+0x6d049c)
    #18 grpc_core::LoadBalancingPolicy::Orphan() /proc/self/cwd/src/core/ext/filters/client_channel/lb_policy.cc:46:3 (h2_ssl_proxy_test+0x8b11cf)
    #19 void grpc_core::OrphanableDelete::operator()<grpc_core::LoadBalancingPolicy>(grpc_core::LoadBalancingPolicy*) /proc/self/cwd/./src/core/lib/gprpp/orphanable.h:63:8 (h2_ssl_proxy_test+0x751dba)
    #20 std::unique_ptr<grpc_core::LoadBalancingPolicy, grpc_core::OrphanableDelete>::reset(grpc_core::LoadBalancingPolicy*) /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/unique_ptr.h:344:4 (h2_ssl_proxy_test+0x752fcd)
    #21 grpc_core::ResolvingLoadBalancingPolicy::ShutdownLocked() /proc/self/cwd/src/core/ext/filters/client_channel/resolving_lb_policy.cc:218:18 (h2_ssl_proxy_test+0x89b8e5)
    #22 grpc_core::LoadBalancingPolicy::Orphan() /proc/self/cwd/src/core/ext/filters/client_channel/lb_policy.cc:46:3 (h2_ssl_proxy_test+0x8b11cf)
    #23 void grpc_core::OrphanableDelete::operator()<grpc_core::ResolvingLoadBalancingPolicy>(grpc_core::ResolvingLoadBalancingPolicy*) /proc/self/cwd/./src/core/lib/gprpp/orphanable.h:63:8 (h2_ssl_proxy_test+0x878f0a)
    #24 std::unique_ptr<grpc_core::ResolvingLoadBalancingPolicy, grpc_core::OrphanableDelete>::reset(grpc_core::ResolvingLoadBalancingPolicy*) /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/unique_ptr.h:344:4 (h2_ssl_proxy_test+0x878d2d)
    #25 grpc_core::(anonymous namespace)::ChannelData::DestroyResolvingLoadBalancingPolicyLocked() /proc/self/cwd/src/core/ext/filters/client_channel/client_channel.cc:1615:26 (h2_ssl_proxy_test+0x85f218)
    #26 grpc_core::(anonymous namespace)::ChannelData::StartTransportOpLocked(void*, grpc_error*) /proc/self/cwd/src/core/ext/filters/client_channel/client_channel.cc:1854:12 (h2_ssl_proxy_test+0x85e981)
    #27 grpc_combiner_continue_exec_ctx() /proc/self/cwd/src/core/lib/iomgr/combiner.cc:236:5 (h2_ssl_proxy_test+0xc8fd8b)
    #28 grpc_core::ExecCtx::Flush() /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:161:17 (h2_ssl_proxy_test+0xc99e4a)
    #29 grpc_core::ExecCtx::~ExecCtx() /proc/self/cwd/./src/core/lib/iomgr/exec_ctx.h:126:5 (h2_ssl_proxy_test+0x61ae1c)
    #30 grpc_channel_destroy /proc/self/cwd/src/core/lib/surface/channel.cc:521:1 (h2_ssl_proxy_test+0xc31a07)
    #31 shutdown_client(grpc_end2end_test_fixture*) /proc/self/cwd/test/core/end2end/tests/cancel_after_invoke.cc:79:3 (h2_ssl_proxy_test+0x6b72d1)
    #32 end_test(grpc_end2end_test_fixture*) /proc/self/cwd/test/core/end2end/tests/cancel_after_invoke.cc:85:3 (h2_ssl_proxy_test+0x6b6eb6)
    #33 test_cancel_after_invoke(grpc_end2end_test_config, cancellation_mode, unsigned long) /proc/self/cwd/test/core/end2end/tests/cancel_after_invoke.cc:181:3 (h2_ssl_proxy_test+0x6b6bb6)
    #34 cancel_after_invoke(grpc_end2end_test_config) /proc/self/cwd/test/core/end2end/tests/cancel_after_invoke.cc:190:7 (h2_ssl_proxy_test+0x6b5fc9)
    #35 grpc_end2end_tests(int, char**, grpc_end2end_test_config) /proc/self/cwd/test/core/end2end/end2end_tests.cc:394:7 (h2_ssl_proxy_test+0x61d90a)
    #36 main /proc/self/cwd/test/core/end2end/fixtures/h2_ssl_proxy.cc:216:5 (h2_ssl_proxy_test+0x619dc8)

  Previous read of size 8 at 0x7b50000103c8 by thread T7:
    #0 grpc_core::(anonymous namespace)::SecurityHandshaker::ScheduleWrite(void*, grpc_error*) /proc/self/cwd/src/core/lib/security/transport/security_handshaker.cc:304:33 (h2_ssl_proxy_test+0x7e8cee)
    #1 exec_ctx_run(grpc_closure*, grpc_error*) /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:40:3 (h2_ssl_proxy_test+0xc9a0e7)
    #2 grpc_core::ExecCtx::Flush() /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:158:9 (h2_ssl_proxy_test+0xc99e2e)
    #3 end_worker(grpc_pollset*, grpc_pollset_worker*, grpc_pollset_worker**) /proc/self/cwd/src/core/lib/iomgr/ev_epoll1_linux.cc:986:34 (h2_ssl_proxy_test+0xccd8e8)
    #4 pollset_work(grpc_pollset*, grpc_pollset_worker**, long) /proc/self/cwd/src/core/lib/iomgr/ev_epoll1_linux.cc:1055:3 (h2_ssl_proxy_test+0xcc9101)
    #5 pollset_work(grpc_pollset*, grpc_pollset_worker**, long) /proc/self/cwd/src/core/lib/iomgr/ev_posix.cc:324:21 (h2_ssl_proxy_test+0xc98340)
    #6 grpc_pollset_work(grpc_pollset*, grpc_pollset_worker**, long) /proc/self/cwd/src/core/lib/iomgr/pollset.cc:48:10 (h2_ssl_proxy_test+0xcab7ea)
    #7 cq_next(grpc_completion_queue*, gpr_timespec, void*) /proc/self/cwd/src/core/lib/surface/completion_queue.cc:1037:23 (h2_ssl_proxy_test+0xc25569)
    #8 grpc_completion_queue_next /proc/self/cwd/src/core/lib/surface/completion_queue.cc:1113:10 (h2_ssl_proxy_test+0xc23e33)
    #9 thread_main(void*) /proc/self/cwd/test/core/end2end/fixtures/proxy.cc:425:21 (h2_ssl_proxy_test+0x6ca258)
    #10 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::operator()(void*) const /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:139:27 (h2_ssl_proxy_test+0xd2329e)
    #11 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::__invoke(void*) /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:109:25 (h2_ssl_proxy_test+0xd23098)

  Location is heap block of size 512 at 0x7b5000010200 allocated by thread T7:
    #0 malloc /tmp/clang-build/src/compiler-rt/lib/tsan/rtl/tsan_interceptors.cpp:650:5 (h2_ssl_proxy_test+0x5a93f4)
    #1 operator new(unsigned long) <null> (libstdc++.so.6+0x8de77)
    #2 start_handshake_locked(chttp2_connector*) /proc/self/cwd/src/core/ext/transport/chttp2/client/chttp2_connector.cc:160:22 (h2_ssl_proxy_test+0x84c2cb)
    #3 connected(void*, grpc_error*) /proc/self/cwd/src/core/ext/transport/chttp2/client/chttp2_connector.cc:193:5 (h2_ssl_proxy_test+0x84c235)
    #4 exec_ctx_run(grpc_closure*, grpc_error*) /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:40:3 (h2_ssl_proxy_test+0xc9a0e7)
    #5 grpc_core::ExecCtx::Flush() /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:158:9 (h2_ssl_proxy_test+0xc99e2e)
    #6 end_worker(grpc_pollset*, grpc_pollset_worker*, grpc_pollset_worker**) /proc/self/cwd/src/core/lib/iomgr/ev_epoll1_linux.cc:986:34 (h2_ssl_proxy_test+0xccd8e8)
    #7 pollset_work(grpc_pollset*, grpc_pollset_worker**, long) /proc/self/cwd/src/core/lib/iomgr/ev_epoll1_linux.cc:1055:3 (h2_ssl_proxy_test+0xcc9101)
    #8 pollset_work(grpc_pollset*, grpc_pollset_worker**, long) /proc/self/cwd/src/core/lib/iomgr/ev_posix.cc:324:21 (h2_ssl_proxy_test+0xc98340)
    #9 grpc_pollset_work(grpc_pollset*, grpc_pollset_worker**, long) /proc/self/cwd/src/core/lib/iomgr/pollset.cc:48:10 (h2_ssl_proxy_test+0xcab7ea)
    #10 cq_next(grpc_completion_queue*, gpr_timespec, void*) /proc/self/cwd/src/core/lib/surface/completion_queue.cc:1037:23 (h2_ssl_proxy_test+0xc25569)
    #11 grpc_completion_queue_next /proc/self/cwd/src/core/lib/surface/completion_queue.cc:1113:10 (h2_ssl_proxy_test+0xc23e33)
    #12 thread_main(void*) /proc/self/cwd/test/core/end2end/fixtures/proxy.cc:425:21 (h2_ssl_proxy_test+0x6ca258)
    #13 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::operator()(void*) const /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:139:27 (h2_ssl_proxy_test+0xd2329e)
    #14 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::__invoke(void*) /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:109:25 (h2_ssl_proxy_test+0xd23098)

  Mutex M2196 (0x7b5400001e20) created at:
    #0 pthread_mutex_init /tmp/clang-build/src/compiler-rt/lib/tsan/rtl/tsan_interceptors.cpp:1225:3 (h2_ssl_proxy_test+0x5ac31d)
    #1 gpr_mu_init /proc/self/cwd/src/core/lib/gpr/sync_posix.cc:44:3 (h2_ssl_proxy_test+0xd2c55c)
    #2 grpc_core::Mutex::Mutex() /proc/self/cwd/./src/core/lib/gprpp/sync.h:42:13 (h2_ssl_proxy_test+0x767318)
    #3 grpc_core::Subchannel::Subchannel(grpc_core::SubchannelKey*, grpc_connector*, grpc_channel_args const*) /proc/self/cwd/src/core/ext/filters/client_channel/subchannel.cc:616:13 (h2_ssl_proxy_test+0x882818)
    #4 grpc_core::Subchannel::Create(grpc_connector*, grpc_channel_args const*) /proc/self/cwd/src/core/ext/filters/client_channel/subchannel.cc:687:11 (h2_ssl_proxy_test+0x8841ab)
    #5 grpc_core::Chttp2SecureClientChannelFactory::CreateSubchannel(grpc_channel_args const*) /proc/self/cwd/src/core/ext/transport/chttp2/client/secure/secure_channel_create.cc:55:21 (h2_ssl_proxy_test+0x7d8244)
    #6 grpc_core::(anonymous namespace)::ChannelData::ClientChannelControlHelper::CreateSubchannel(grpc_channel_args const&) /proc/self/cwd/src/core/ext/filters/client_channel/client_channel.cc:1317:42 (h2_ssl_proxy_test+0x865baa)
    #7 grpc_core::ResolvingLoadBalancingPolicy::ResolvingControlHelper::CreateSubchannel(grpc_channel_args const&) /proc/self/cwd/src/core/ext/filters/client_channel/resolving_lb_policy.cc:113:47 (h2_ssl_proxy_test+0x89e363)
    #8 grpc_core::SubchannelList<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelList, grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData>::SubchannelList(grpc_core::LoadBalancingPolicy*, grpc_core::TraceFlag*, grpc_core::InlinedVector<grpc_core::ServerAddress, 1ul> const&, grpc_core::LoadBalancingPolicy::ChannelControlHelper*, grpc_channel_args const&) /proc/self/cwd/./src/core/ext/filters/client_channel/lb_policy/subchannel_list.h:394:17 (h2_ssl_proxy_test+0x6d276d)
    #9 grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelList::PickFirstSubchannelList(grpc_core::(anonymous namespace)::PickFirst*, grpc_core::TraceFlag*, grpc_core::InlinedVector<grpc_core::ServerAddress, 1ul> const&, grpc_channel_args const&) /proc/self/cwd/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc:88:11 (h2_ssl_proxy_test+0x6d1f38)
    #10 std::unique_ptr<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelList, grpc_core::OrphanableDelete> grpc_core::MakeOrphanable<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelList, grpc_core::(anonymous namespace)::PickFirst*, grpc_core::TraceFlag*, grpc_core::InlinedVector<grpc_core::ServerAddress, 1ul>&, grpc_channel_args const&>(grpc_core::(anonymous namespace)::PickFirst*&&, grpc_core::TraceFlag*&&, grpc_core::InlinedVector<grpc_core::ServerAddress, 1ul>&, grpc_channel_args const&) /proc/self/cwd/./src/core/lib/gprpp/orphanable.h:72:31 (h2_ssl_proxy_test+0x6d116a)
    #11 grpc_core::(anonymous namespace)::PickFirst::AttemptToConnectUsingLatestUpdateArgsLocked() /proc/self/cwd/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc:187:26 (h2_ssl_proxy_test+0x6d0a50)
    #12 grpc_core::(anonymous namespace)::PickFirst::UpdateLocked(grpc_core::LoadBalancingPolicy::UpdateArgs) /proc/self/cwd/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc:280:5 (h2_ssl_proxy_test+0x6d01d9)
    #13 grpc_core::ResolvingLoadBalancingPolicy::CreateOrUpdateLbPolicyLocked(char const*, grpc_core::RefCountedPtr<grpc_core::LoadBalancingPolicy::Config>, grpc_core::Resolver::Result, grpc_core::InlinedVector<char*, 3ul>*) /proc/self/cwd/src/core/ext/filters/client_channel/resolving_lb_policy.cc:365:21 (h2_ssl_proxy_test+0x89c5ae)
    #14 grpc_core::ResolvingLoadBalancingPolicy::OnResolverResultChangedLocked(grpc_core::Resolver::Result) /proc/self/cwd/src/core/ext/filters/client_channel/resolving_lb_policy.cc:480:5 (h2_ssl_proxy_test+0x89d3ce)
    #15 grpc_core::ResolvingLoadBalancingPolicy::ResolverResultHandler::ReturnResult(grpc_core::Resolver::Result) /proc/self/cwd/src/core/ext/filters/client_channel/resolving_lb_policy.cc:87:14 (h2_ssl_proxy_test+0x89f22c)
    #16 grpc_core::(anonymous namespace)::AresDnsResolver::OnResolvedLocked(void*, grpc_error*) /proc/self/cwd/src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc:360:26 (h2_ssl_proxy_test+0x6f6f5f)
    #17 grpc_combiner_continue_exec_ctx() /proc/self/cwd/src/core/lib/iomgr/combiner.cc:236:5 (h2_ssl_proxy_test+0xc8fd8b)
    #18 grpc_core::ExecCtx::Flush() /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:161:17 (h2_ssl_proxy_test+0xc99e4a)
    #19 grpc_core::ExecCtx::~ExecCtx() /proc/self/cwd/./src/core/lib/iomgr/exec_ctx.h:126:5 (h2_ssl_proxy_test+0x61ae1c)
    #20 grpc_call_start_batch /proc/self/cwd/src/core/lib/surface/call.cc:1975:3 (h2_ssl_proxy_test+0xc377d6)
    #21 test_cancel_after_invoke(grpc_end2end_test_config, cancellation_mode, unsigned long) /proc/self/cwd/test/core/end2end/tests/cancel_after_invoke.cc:159:11 (h2_ssl_proxy_test+0x6b68d4)
    #22 cancel_after_invoke(grpc_end2end_test_config) /proc/self/cwd/test/core/end2end/tests/cancel_after_invoke.cc:190:7 (h2_ssl_proxy_test+0x6b5fc9)
    #23 grpc_end2end_tests(int, char**, grpc_end2end_test_config) /proc/self/cwd/test/core/end2end/end2end_tests.cc:394:7 (h2_ssl_proxy_test+0x61d90a)
    #24 main /proc/self/cwd/test/core/end2end/fixtures/h2_ssl_proxy.cc:216:5 (h2_ssl_proxy_test+0x619dc8)

  Mutex M2194 (0x7b34000004e8) created at:
    #0 pthread_mutex_init /tmp/clang-build/src/compiler-rt/lib/tsan/rtl/tsan_interceptors.cpp:1225:3 (h2_ssl_proxy_test+0x5ac31d)
    #1 gpr_mu_init /proc/self/cwd/src/core/lib/gpr/sync_posix.cc:44:3 (h2_ssl_proxy_test+0xd2c55c)
    #2 grpc_chttp2_connector_create() /proc/self/cwd/src/core/ext/transport/chttp2/client/chttp2_connector.cc:236:3 (h2_ssl_proxy_test+0x84b639)
    #3 grpc_core::Chttp2SecureClientChannelFactory::CreateSubchannel(grpc_channel_args const*) /proc/self/cwd/src/core/ext/transport/chttp2/client/secure/secure_channel_create.cc:54:33 (h2_ssl_proxy_test+0x7d8226)
    #4 grpc_core::(anonymous namespace)::ChannelData::ClientChannelControlHelper::CreateSubchannel(grpc_channel_args const&) /proc/self/cwd/src/core/ext/filters/client_channel/client_channel.cc:1317:42 (h2_ssl_proxy_test+0x865baa)
    #5 grpc_core::ResolvingLoadBalancingPolicy::ResolvingControlHelper::CreateSubchannel(grpc_channel_args const&) /proc/self/cwd/src/core/ext/filters/client_channel/resolving_lb_policy.cc:113:47 (h2_ssl_proxy_test+0x89e363)
    #6 grpc_core::SubchannelList<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelList, grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData>::SubchannelList(grpc_core::LoadBalancingPolicy*, grpc_core::TraceFlag*, grpc_core::InlinedVector<grpc_core::ServerAddress, 1ul> const&, grpc_core::LoadBalancingPolicy::ChannelControlHelper*, grpc_channel_args const&) /proc/self/cwd/./src/core/ext/filters/client_channel/lb_policy/subchannel_list.h:394:17 (h2_ssl_proxy_test+0x6d276d)
    #7 grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelList::PickFirstSubchannelList(grpc_core::(anonymous namespace)::PickFirst*, grpc_core::TraceFlag*, grpc_core::InlinedVector<grpc_core::ServerAddress, 1ul> const&, grpc_channel_args const&) /proc/self/cwd/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc:88:11 (h2_ssl_proxy_test+0x6d1f38)
    #8 std::unique_ptr<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelList, grpc_core::OrphanableDelete> grpc_core::MakeOrphanable<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelList, grpc_core::(anonymous namespace)::PickFirst*, grpc_core::TraceFlag*, grpc_core::InlinedVector<grpc_core::ServerAddress, 1ul>&, grpc_channel_args const&>(grpc_core::(anonymous namespace)::PickFirst*&&, grpc_core::TraceFlag*&&, grpc_core::InlinedVector<grpc_core::ServerAddress, 1ul>&, grpc_channel_args const&) /proc/self/cwd/./src/core/lib/gprpp/orphanable.h:72:31 (h2_ssl_proxy_test+0x6d116a)
    #9 grpc_core::(anonymous namespace)::PickFirst::AttemptToConnectUsingLatestUpdateArgsLocked() /proc/self/cwd/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc:187:26 (h2_ssl_proxy_test+0x6d0a50)
    #10 grpc_core::(anonymous namespace)::PickFirst::UpdateLocked(grpc_core::LoadBalancingPolicy::UpdateArgs) /proc/self/cwd/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc:280:5 (h2_ssl_proxy_test+0x6d01d9)
    #11 grpc_core::ResolvingLoadBalancingPolicy::CreateOrUpdateLbPolicyLocked(char const*, grpc_core::RefCountedPtr<grpc_core::LoadBalancingPolicy::Config>, grpc_core::Resolver::Result, grpc_core::InlinedVector<char*, 3ul>*) /proc/self/cwd/src/core/ext/filters/client_channel/resolving_lb_policy.cc:365:21 (h2_ssl_proxy_test+0x89c5ae)
    #12 grpc_core::ResolvingLoadBalancingPolicy::OnResolverResultChangedLocked(grpc_core::Resolver::Result) /proc/self/cwd/src/core/ext/filters/client_channel/resolving_lb_policy.cc:480:5 (h2_ssl_proxy_test+0x89d3ce)
    #13 grpc_core::ResolvingLoadBalancingPolicy::ResolverResultHandler::ReturnResult(grpc_core::Resolver::Result) /proc/self/cwd/src/core/ext/filters/client_channel/resolving_lb_policy.cc:87:14 (h2_ssl_proxy_test+0x89f22c)
    #14 grpc_core::(anonymous namespace)::AresDnsResolver::OnResolvedLocked(void*, grpc_error*) /proc/self/cwd/src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc:360:26 (h2_ssl_proxy_test+0x6f6f5f)
    #15 grpc_combiner_continue_exec_ctx() /proc/self/cwd/src/core/lib/iomgr/combiner.cc:236:5 (h2_ssl_proxy_test+0xc8fd8b)
    #16 grpc_core::ExecCtx::Flush() /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:161:17 (h2_ssl_proxy_test+0xc99e4a)
    #17 grpc_core::ExecCtx::~ExecCtx() /proc/self/cwd/./src/core/lib/iomgr/exec_ctx.h:126:5 (h2_ssl_proxy_test+0x61ae1c)
    #18 grpc_call_start_batch /proc/self/cwd/src/core/lib/surface/call.cc:1975:3 (h2_ssl_proxy_test+0xc377d6)
    #19 test_cancel_after_invoke(grpc_end2end_test_config, cancellation_mode, unsigned long) /proc/self/cwd/test/core/end2end/tests/cancel_after_invoke.cc:159:11 (h2_ssl_proxy_test+0x6b68d4)
    #20 cancel_after_invoke(grpc_end2end_test_config) /proc/self/cwd/test/core/end2end/tests/cancel_after_invoke.cc:190:7 (h2_ssl_proxy_test+0x6b5fc9)
    #21 grpc_end2end_tests(int, char**, grpc_end2end_test_config) /proc/self/cwd/test/core/end2end/end2end_tests.cc:394:7 (h2_ssl_proxy_test+0x61d90a)
    #22 main /proc/self/cwd/test/core/end2end/fixtures/h2_ssl_proxy.cc:216:5 (h2_ssl_proxy_test+0x619dc8)

  Mutex M2249 (0x7b5000010218) created at:
    #0 pthread_mutex_init /tmp/clang-build/src/compiler-rt/lib/tsan/rtl/tsan_interceptors.cpp:1225:3 (h2_ssl_proxy_test+0x5ac31d)
    #1 gpr_mu_init /proc/self/cwd/src/core/lib/gpr/sync_posix.cc:44:3 (h2_ssl_proxy_test+0xd2c55c)
    #2 grpc_core::HandshakeManager::HandshakeManager() /proc/self/cwd/src/core/lib/channel/handshaker.cc:57:40 (h2_ssl_proxy_test+0xc72525)
    #3 grpc_core::RefCountedPtr<grpc_core::HandshakeManager> grpc_core::MakeRefCounted<grpc_core::HandshakeManager>() /proc/self/cwd/./src/core/lib/gprpp/ref_counted_ptr.h:182:31 (h2_ssl_proxy_test+0x80923a)
    #4 start_handshake_locked(chttp2_connector*) /proc/self/cwd/src/core/ext/transport/chttp2/client/chttp2_connector.cc:160:22 (h2_ssl_proxy_test+0x84c2cb)
    #5 connected(void*, grpc_error*) /proc/self/cwd/src/core/ext/transport/chttp2/client/chttp2_connector.cc:193:5 (h2_ssl_proxy_test+0x84c235)
    #6 exec_ctx_run(grpc_closure*, grpc_error*) /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:40:3 (h2_ssl_proxy_test+0xc9a0e7)
    #7 grpc_core::ExecCtx::Flush() /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:158:9 (h2_ssl_proxy_test+0xc99e2e)
    #8 end_worker(grpc_pollset*, grpc_pollset_worker*, grpc_pollset_worker**) /proc/self/cwd/src/core/lib/iomgr/ev_epoll1_linux.cc:986:34 (h2_ssl_proxy_test+0xccd8e8)
    #9 pollset_work(grpc_pollset*, grpc_pollset_worker**, long) /proc/self/cwd/src/core/lib/iomgr/ev_epoll1_linux.cc:1055:3 (h2_ssl_proxy_test+0xcc9101)
    #10 pollset_work(grpc_pollset*, grpc_pollset_worker**, long) /proc/self/cwd/src/core/lib/iomgr/ev_posix.cc:324:21 (h2_ssl_proxy_test+0xc98340)
    #11 grpc_pollset_work(grpc_pollset*, grpc_pollset_worker**, long) /proc/self/cwd/src/core/lib/iomgr/pollset.cc:48:10 (h2_ssl_proxy_test+0xcab7ea)
    #12 cq_next(grpc_completion_queue*, gpr_timespec, void*) /proc/self/cwd/src/core/lib/surface/completion_queue.cc:1037:23 (h2_ssl_proxy_test+0xc25569)
    #13 grpc_completion_queue_next /proc/self/cwd/src/core/lib/surface/completion_queue.cc:1113:10 (h2_ssl_proxy_test+0xc23e33)
    #14 thread_main(void*) /proc/self/cwd/test/core/end2end/fixtures/proxy.cc:425:21 (h2_ssl_proxy_test+0x6ca258)
    #15 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::operator()(void*) const /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:139:27 (h2_ssl_proxy_test+0xd2329e)
    #16 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::__invoke(void*) /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:109:25 (h2_ssl_proxy_test+0xd23098)

  Mutex M2267 (0x7b5c000003a8) created at:
    #0 pthread_mutex_init /tmp/clang-build/src/compiler-rt/lib/tsan/rtl/tsan_interceptors.cpp:1225:3 (h2_ssl_proxy_test+0x5ac31d)
    #1 gpr_mu_init /proc/self/cwd/src/core/lib/gpr/sync_posix.cc:44:3 (h2_ssl_proxy_test+0xd2c55c)
    #2 grpc_core::(anonymous namespace)::SecurityHandshaker::SecurityHandshaker(tsi_handshaker*, grpc_security_connector*, grpc_channel_args const*) /proc/self/cwd/src/core/lib/security/transport/security_handshaker.cc:123:3 (h2_ssl_proxy_test+0x7e88b6)
    #3 grpc_core::RefCountedPtr<grpc_core::(anonymous namespace)::SecurityHandshaker> grpc_core::MakeRefCounted<grpc_core::(anonymous namespace)::SecurityHandshaker, tsi_handshaker*&, grpc_security_connector*&, grpc_channel_args const*&>(tsi_handshaker*&, grpc_security_connector*&, grpc_channel_args const*&) /proc/self/cwd/./src/core/lib/gprpp/ref_counted_ptr.h:182:31 (h2_ssl_proxy_test+0x7e7a21)
    #4 grpc_core::SecurityHandshakerCreate(tsi_handshaker*, grpc_security_connector*, grpc_channel_args const*) /proc/self/cwd/src/core/lib/security/transport/security_handshaker.cc:528:12 (h2_ssl_proxy_test+0x7e76b0)
    #5 (anonymous namespace)::grpc_ssl_channel_security_connector::add_handshakers(grpc_channel_args const*, grpc_pollset_set*, grpc_core::HandshakeManager*) /proc/self/cwd/src/core/lib/security/security_connector/ssl/ssl_security_connector.cc:136:24 (h2_ssl_proxy_test+0x815c54)
    #6 grpc_core::(anonymous namespace)::ClientSecurityHandshakerFactory::AddHandshakers(grpc_channel_args const*, grpc_pollset_set*, grpc_core::HandshakeManager*) /proc/self/cwd/src/core/lib/security/transport/security_handshaker.cc:491:27 (h2_ssl_proxy_test+0x7eb89b)
    #7 grpc_core::(anonymous namespace)::HandshakerFactoryList::AddHandshakers(grpc_channel_args const*, grpc_pollset_set*, grpc_core::HandshakeManager*) /proc/self/cwd/src/core/lib/channel/handshaker_registry.cc:68:25 (h2_ssl_proxy_test+0xc7580f)
    #8 grpc_core::HandshakerRegistry::AddHandshakers(grpc_core::HandshakerType, grpc_channel_args const*, grpc_pollset_set*, grpc_core::HandshakeManager*) /proc/self/cwd/src/core/lib/channel/handshaker_registry.cc:114:16 (h2_ssl_proxy_test+0xc7570a)
    #9 start_handshake_locked(chttp2_connector*) /proc/self/cwd/src/core/ext/transport/chttp2/client/chttp2_connector.cc:161:3 (h2_ssl_proxy_test+0x84c35f)
    #10 connected(void*, grpc_error*) /proc/self/cwd/src/core/ext/transport/chttp2/client/chttp2_connector.cc:193:5 (h2_ssl_proxy_test+0x84c235)
    #11 exec_ctx_run(grpc_closure*, grpc_error*) /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:40:3 (h2_ssl_proxy_test+0xc9a0e7)
    #12 grpc_core::ExecCtx::Flush() /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:158:9 (h2_ssl_proxy_test+0xc99e2e)
    #13 end_worker(grpc_pollset*, grpc_pollset_worker*, grpc_pollset_worker**) /proc/self/cwd/src/core/lib/iomgr/ev_epoll1_linux.cc:986:34 (h2_ssl_proxy_test+0xccd8e8)
    #14 pollset_work(grpc_pollset*, grpc_pollset_worker**, long) /proc/self/cwd/src/core/lib/iomgr/ev_epoll1_linux.cc:1055:3 (h2_ssl_proxy_test+0xcc9101)
    #15 pollset_work(grpc_pollset*, grpc_pollset_worker**, long) /proc/self/cwd/src/core/lib/iomgr/ev_posix.cc:324:21 (h2_ssl_proxy_test+0xc98340)
    #16 grpc_pollset_work(grpc_pollset*, grpc_pollset_worker**, long) /proc/self/cwd/src/core/lib/iomgr/pollset.cc:48:10 (h2_ssl_proxy_test+0xcab7ea)
    #17 cq_next(grpc_completion_queue*, gpr_timespec, void*) /proc/self/cwd/src/core/lib/surface/completion_queue.cc:1037:23 (h2_ssl_proxy_test+0xc25569)
    #18 grpc_completion_queue_next /proc/self/cwd/src/core/lib/surface/completion_queue.cc:1113:10 (h2_ssl_proxy_test+0xc23e33)
    #19 thread_main(void*) /proc/self/cwd/test/core/end2end/fixtures/proxy.cc:425:21 (h2_ssl_proxy_test+0x6ca258)
    #20 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::operator()(void*) const /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:139:27 (h2_ssl_proxy_test+0xd2329e)
    #21 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::__invoke(void*) /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:109:25 (h2_ssl_proxy_test+0xd23098)

  Thread T7 'grpc_end2end_pr' (tid=26, running) created by main thread at:
    #0 pthread_create /tmp/clang-build/src/compiler-rt/lib/tsan/rtl/tsan_interceptors.cpp:967:3 (h2_ssl_proxy_test+0x5aacdb)
    #1 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&) /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:108:10 (h2_ssl_proxy_test+0xd22c10)
    #2 grpc_core::Thread::Thread(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&) /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:185:15 (h2_ssl_proxy_test+0xd224d6)
    #3 grpc_end2end_proxy_create(grpc_end2end_proxy_def const*, grpc_channel_args*, grpc_channel_args*) /proc/self/cwd/test/core/end2end/fixtures/proxy.cc:108:16 (h2_ssl_proxy_test+0x6ca0f1)
    #4 chttp2_create_fixture_secure_fullstack(grpc_channel_args*, grpc_channel_args*) /proc/self/cwd/test/core/end2end/fixtures/h2_ssl_proxy.cc:85:16 (h2_ssl_proxy_test+0x619f2c)
    #5 begin_test(grpc_end2end_test_config, char const*, cancellation_mode, unsigned long, grpc_channel_args*, grpc_channel_args*) /proc/self/cwd/test/core/end2end/tests/cancel_after_invoke.cc:45:7 (h2_ssl_proxy_test+0x6b6d54)
    #6 test_cancel_after_invoke(grpc_end2end_test_config, cancellation_mode, unsigned long) /proc/self/cwd/test/core/end2end/tests/cancel_after_invoke.cc:99:33 (h2_ssl_proxy_test+0x6b611e)
    #7 cancel_after_invoke(grpc_end2end_test_config) /proc/self/cwd/test/core/end2end/tests/cancel_after_invoke.cc:190:7 (h2_ssl_proxy_test+0x6b5fc9)
    #8 grpc_end2end_tests(int, char**, grpc_end2end_test_config) /proc/self/cwd/test/core/end2end/end2end_tests.cc:394:7 (h2_ssl_proxy_test+0x61d90a)
    #9 main /proc/self/cwd/test/core/end2end/fixtures/h2_ssl_proxy.cc:216:5 (h2_ssl_proxy_test+0x619dc8)

SUMMARY: ThreadSanitizer: data race /proc/self/cwd/src/core/lib/security/transport/security_handshaker.cc:179:19 in grpc_core::(anonymous namespace)::SecurityHandshaker::CleanupArgsForFailureLocked()
==================
```

### PR DESCRIPTION
**Pull request by yashykt**
The issue is that we were using args_->endpoint and args_->read_buffer for grpc_endpoint_read and grpc_endpoint_write outside of a mutex, but these fields can be reset in CleanupArgsForFailureLocked() on a failure or a shutdown. To avoid this, we no longer release locks when doing a grpc_endpoint_read or grpc_endpoint_write. Instead, we simply schedule the callbacks on ExecCtx.

Fixes #20986

### CODE REVIEW

File: src/core/lib/security/transport/security_handshaker.cc [hunk 1]
```diff
@@ -141,12 +141,12 @@ SecurityHandshaker::~SecurityHandshaker() {
   gpr_mu_destroy(&mu_);
   tsi_handshaker_destroy(handshaker_);
   tsi_handshaker_result_destroy(handshaker_result_);
-  if (endpoint_to_destroy_ != nullptr) {
```
Comment (apolcyn) [inline src/core/lib/security/transport/security_handshaker.cc]: IIC this is has some behavior change, since we're now unconditionally destroying `args_->endpoint` and `args_->read_buffer`, where before they would only be destroyed upon handshake failure?

**Comment by markdroth** [comment]
This looks like it should work.  But would it be simpler to just have the callback schedule itself on the `ExecCtx`, as we've done elsewhere?  That way, we don't have to give up the lock before calling the endpoint in the first place.

I am beginning to think that it really would make sense to change the endpoint API to indicate whether the operation returned synchronously or not.  That would avoid a lot of these problems.

File: src/core/lib/security/transport/security_handshaker.cc (hunk 1 above)
Comment (yashykt) [reply src/core/lib/security/transport/security_handshaker.cc]: You are right. Fixed it

**Comment by yashykt** [comment]
@markdroth , yes that would work too. Either the callback gets rescheduled on ExecCtx or the endpoint_read/write itself gets rescheduled.

Yes, changing the endpoint API would also fix this, but if handshaking code is the only place where we see this issue, then I don't see much motivation to change the endpoint API and all the usecases.

**Comment by markdroth** [comment]
Okay, so let's try having the callback schedule itself on the `ExecCtx`.  I think that should be simpler than what this PR is doing now.

**Comment by yashykt** [comment]
@markdroth Alright, sounds good to me. I would prefer working on a fresh branch for that change, and overwrite the current commits.

**Comment by yashykt** [comment]
Issues : #20198, #20686, #21015
Objc IOS - Seems like a trasient repository fetch error

**Comment by yashykt** [comment]
Thanks for reviewing!
