### PR TITLE
Node: Validate arguments to addService, fix a couple of minor issues

### LINKED ISSUE #7053: grpc.load does not handle deprecatedArgumentOrder correctly
For NodeJS library in version 0.14.1 and above, setting `options.deprecatedArgumentOrder` to true in `grpc.load` does not make gRPC use the old argument order format (where the mandatory `callback` is at the front instead of at the back). 

This could be because `makeProtobufClientConstructor` in [client.js](https://github.com/grpc/grpc/blob/master/src/node/src/client.js) is passing in a boolean `deprecatedArgumentOrder` instead of the object `options`.

Example code:
[test.js](http://pastebin.com/BpjSefH9)
[tester.proto](http://pastebin.com/HtGgp6rD)

cc @matthewloring

### LINKED ISSUE #9288: The Node server's addService method should do some argument validation
Currently, `server.addService` will accept just about anything, up to and including `undefined` as a value for the `service` argument without complaint. It should fail if the argument does not have the expected type.

### PR DESCRIPTION
**Pull request by murgatroid99**
Fixes #9288, also should fix #7053 and a lint error.

### CODE REVIEW

**Comment by murgatroid99** [comment]
test this please

File: src/node/src/client.js [hunk 1]
```diff
@@ -831,13 +831,12 @@ exports.waitForClientReady = function(client, deadline, callback) {
...
   var method_attrs = common.getProtobufServiceAttrs(service, options);
-  var deprecatedArgumentOrder = false;
-  if (options) {
-    deprecatedArgumentOrder = options.deprecatedArgumentOrder;
+  if (!options) {
+    options = {deprecatedArgumentOrder: false};
   }
   var Client = exports.makeClientConstructor(
       method_attrs, common.fullyQualifiedName(service),
-      deprecatedArgumentOrder);
```
Comment (apolcyn) [inline src/node/src/client.js]: nit: perhaps only use boolean `deprecatedArgumentOrder` instead of the `options` object. In `makeClientConstructor`, looks like only this field is used.

Comment (murgatroid99) [inline src/node/src/client.js]: I don't want to limit it. Part of the benefit of having an options field is to make it easier to add other options as necessary.

**Comment by murgatroid99** [comment]
The Linux test is fixed in #9527. The Mac failure is an infrastructure failure. The interop failure only involves the Java implementation.
