### PR TITLE
Don't segfault on header replay

### LINKED ISSUE #14175: HTTP2: sending multiple subsequent HTTP2 'HEADERS' frames causes crash on gRPC server
#### Should this be an issue in the gRPC issue tracker?
Yes.

#### What version of gRPC and what language are you using?
 Python, gRPC 1.8.4
 
#### What operating system (Linux, Windows, …) and version?
 CentOS release 6.6 (Final)
Linux 2.6.32-504.30.3.el6.x86_64 #1 SMP x86_64 x86_64 x86_64 GNU/Linux
 
#### What runtime / compiler are you using (e.g. python version or version of gcc)
 Python 2.7.11, GCC 4.4.7
 
#### What did you do?
When checking how a simple Python server handles invalid HTTP2 requests, I observed server crash caused by duplicating HEADERS frame (valid by itself) in client request (i.e. HTTP2 frame sequence HEADERS + HEADERS + DATA). This issue is reproducible and it is present also on older gRPC versions (since 1.0.0). In case the second HEADERS frame is empty (has no payload), the crash does not occur.

I am attaching the server debug log, although it does not provide much information other than the second HEADERS frame is treated as 'trailing metadata' - the only difference when compared to the log of a valid RPC are the extra lines 347-371.

[server_log_dupl_hdrs.txt](https://github.com/grpc/grpc/files/1663712/server_log_dupl_hdrs.txt)

When checking in wireshark, server does not send any frames and closes the TCP connection immediately (FIN).

### PR DESCRIPTION
**Pull request by kpayson64**
Once approved will backport fix to 1.8/1.9

Fixes #14175

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.0%     +24 [None]                                                                                  +528  +0.0%
  +0.4%     +64 src/core/lib/surface/call.cc                                                             +64  +0.4%
      [NEW]    +506 set_encodings_accepted_by_peer(grpc_call*, grpc_mdelem, unsigned int*, bool) [clone     +506  [NEW]
      [NEW]    +266 publish_app_metadata(grpc_call*, grpc_metadata_batch*, int) [clone .isra.5] [clone .    +266  [NEW]
      +1.2%     +16 finish_batch_step                                                                        +16  +1.2%
      +1.0%     +15 receiving_initial_metadata_ready                                                         +15  +1.0%
      +0.6%      +2 [Unmapped]                                                                                +2  +0.6%

  +0.0%     +88 TOTAL                                                                                   +592  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

File: src/core/lib/surface/call.cc [hunk 1]
```diff
@@ -1036,10 +1036,12 @@ static grpc_stream_compression_algorithm decode_stream_compression(
 static void publish_app_metadata(grpc_call* call, grpc_metadata_batch* b,
                                  int is_trailing) {
   if (b->list.count == 0) return;
+  if (is_trailing && call->buffered_metadata[1] == nullptr) return;
   GPR_TIMER_BEGIN("publish_app_metadata", 0);
   grpc_metadata_array* dest;
   grpc_metadata* mdusr;
   dest = call->buffered_metadata[is_trailing];
+  if (dest == NULL) gpr_log(GPR_ERROR, "dest %p", dest);
```
Comment (yang-g) [inline src/core/lib/surface/call.cc]: What is the point of this log line?

File: test/core/bad_client/tests/duplicate_header.cc [hunk 2]
```diff
@@ -0,0 +1,131 @@
+/*
+ *
+ * Copyright 2017 gRPC authors.
```
Comment (yang-g) [inline test/core/bad_client/tests/duplicate_header.cc]: 2018 :P

File: src/core/lib/surface/call.cc (hunk 1 above)
Comment (kpayson64) [reply src/core/lib/surface/call.cc]: Oops, good catch

File: test/core/bad_client/tests/duplicate_header.cc (hunk 2 above)
Comment (kpayson64) [reply test/core/bad_client/tests/duplicate_header.cc]: Fixed

File: test/core/bad_client/tests/duplicate_header.cc [hunk 3]
```diff
@@ -0,0 +1,131 @@
...
+  cq_verifier_destroy(cqv);
+}
+
+int main(int argc, char** argv) {
+  grpc_test_init(argc, argv);
+  grpc_init();
+
+  /* Verify that sending multiple headers doesn't segfault */
+  GRPC_RUN_BAD_CLIENT_TEST(verifier, nullptr,
+                           PFX_STR HEADER_STR HEADER_STR PAYLOAD_STR, 0);
```
Comment (yang-g) [inline test/core/bad_client/tests/duplicate_header.cc]: Do we want to test other cases?
For example:
- PFX_STR HEADER_STR PAYLOAD_STR(no EOS) HEADER_STR
- Duplicate HEADERS does not contain reserved keys

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

File: test/core/bad_client/tests/duplicate_header.cc (hunk 3 above)
Comment (yang-g) [reply test/core/bad_client/tests/duplicate_header.cc]: It is also interesting to see 3 HEADERS will cause what... if that is not too much...

Comment (nicolasnoble) [reply test/core/bad_client/tests/duplicate_header.cc]: That's not a bad idea.

Comment (nicolasnoble) [reply test/core/bad_client/tests/duplicate_header.cc]: Also, if at all possible, it'd be nice to inject that into the fuzzer's corpus, so it can further try and discover bugs around this.

**Comment by nicolasnoble** [comment]
I think you wanted to open that PR against 1.8, and not master.

**Comment by nicolasnoble** [comment]
Right and I can't just change the base, it will otherwise try to bring all of master into 1.8.

**Comment by yang-g** [comment]
LGTM if the 3 headers case pass

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

File: test/core/bad_client/tests/duplicate_header.cc (hunk 3 above)
Comment (kpayson64) [reply test/core/bad_client/tests/duplicate_header.cc]: I've added the 3 leading headers to the test.  I can add more variants into the fuzzer's corpus.

(FWIW, PFX_STR HEADER_STR PAYLOAD_STR(no EOS) HEADER_STR doesnt segfault, but cq->next returns an unsuccessful event)

**Comment by kpayson64** [comment]
I've addressed comments and rebased to 1.8.x

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                       FILE SIZE
 ++++++++++++++ GROWING                                                                         ++++++++++++++
  +0.1%     +16 src/core/lib/surface/call.cc                                                        +16  +0.1%
      +6.8%     +16 publish_app_metadata(grpc_call*, grpc_metadata_batch*, int) [clone .isra.6]         +16  +6.8%

 -+-+-+-+-+-+-+ MIXED                                                                           +-+-+-+-+-+-+-
  -0.0%     -16 [None]                                                                              +24  +0.0%

  [ = ]       0 TOTAL                                                                               +40  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

File: test/core/bad_client/tests/duplicate_header.cc (hunk 3 above)
Comment (yang-g) [reply test/core/bad_client/tests/duplicate_header.cc]: That can be further investigated without blocking this fix.

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

File: src/core/lib/surface/call.cc [hunk 4]
```diff
@@ -1101,6 +1101,7 @@ static grpc_stream_compression_algorithm decode_stream_compression(
 static void publish_app_metadata(grpc_call* call, grpc_metadata_batch* b,
                                  int is_trailing) {
   if (b->list.count == 0) return;
+  if (is_trailing && call->buffered_metadata[1] == nullptr) return;
```
Comment (ctiller) [inline src/core/lib/surface/call.cc]: It'd be better to find a fix in chttp2: fixes at this layer are more likely to break with efforts to remove this layer entirely in the c++ stack.

Comment (nicolasnoble) [reply src/core/lib/surface/call.cc]: Right, this is a temporary bandaid. We want to actually return a 400 from within chttp2, but "stop the bleeding first".
