### PR TITLE
PHP: do no re-create persisted channels in forked child process

### LINKED ISSUE #21321: PHP: Subprocess crash (via system) after simple rpc call attempt
### What version of gRPC and what language are you using?

v1.25.0

### What operating system (Linux, Windows,...) and version?
```
$ uname -a
Linux hostname.company.com 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core)
```

### What runtime / compiler are you using (e.g. python version or version of gcc)
```
$ php --version
PHP 7.2.2 (cli) (built: Feb  1 2018 15:30:38) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.2, Copyright (c) 1999-2018, by Zend Technologies
```

```
$ php -i | grep grpc
grpc
grpc support => enabled
grpc module version => 1.25.0
grpc.enable_fork_support => 1 => 1
grpc.poll_strategy => epoll1 => epoll1
```

protobuf extension version v3.11.0

```
$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

### What did you do?
Create the following php script in `index.php`

```
<?php
use Helloworld\GreeterClient;
use Helloworld\HelloRequest;

require_once __DIR__ . '/vendor/autoload.php';

$client = new GreeterClient(
    'localhost:50500', // does not matter that no server is running.
    [
        'credentials' => \Grpc\ChannelCredentials::createSsl()
    ]
);

$client->SayHello(
    (new HelloRequest())->setName('Freddie')
)->wait();

$status = 0;
// crash will occur in the subprocess just after fork
system('/usr/bin/true', $status);
if ($status !== 0) {
    throw new \Exception("subprocess failed: {$status}");
}
```

The gRPC client code here is generated from
https://github.com/grpc/grpc-go/blob/master/examples/helloworld/helloworld/helloworld.proto

composer includes `require: {"grpc/grpc": "^1.25"}`

Start the PHP CLI server in the directory with `index.php`

```
php -S 0.0.0.0:8899
```

Now issue 2 http requests to the script via the server.

```
curl -v http://localhost:8899/
curl -v http://localhost:8899/
```

The first request should return a `200`
The second a `500` and the console with show the error:

```
[Wed Nov 27 20:06:33 2019] PHP Fatal error:  Uncaught Exception: subprocess failed: 11 in /opt/app/current/web/index.php:29
Stack trace:
#0 {main}
  thrown in /opt/app/current/web/index.php on line 29
[Wed Nov 27 20:06:33 2019] 192.168.213.1:57471 [500]: / - Uncaught Exception: subprocess failed: 11 in /opt/app/current/web/index.php:29
Stack trace:
#0 {main}
  thrown in /opt/app/current/web/index.php on line 29
```

All subsequent requests will return a `500` with the same error listed above.

### What did you expect to see?
All requests should return `200`

### What did you see instead?
Rather than executing cleanly, the subprocess on the 2nd request crashes resulting in a return status of `11`.

If you use `gdb` and `set follow-fork-mode child`, you can get a back trace for the subprocess, which looks like:

```
#0  credentials_pointer_arg_copy (p=0x436f674143434441) at /opt/app/admin/grpc-1.25.0/src/core/lib/security/credentials/credentials.cc:143
#1  0x00007fc2384fa19a in copy_arg (src=src@entry=0x7fff3407f540) at /opt/app/admin/grpc-1.25.0/src/core/lib/channel/channel_args.cc:49
#2  0x00007fc2384fa36c in grpc_channel_args_copy_and_add_and_remove (src=src@entry=0x7fff3407f5f0, to_remove=to_remove@entry=0x0, num_to_remove=num_to_remove@entry=0,
    to_add=to_add@entry=0x7fff3407f520, num_to_add=num_to_add@entry=2) at /opt/app/admin/grpc-1.25.0/src/core/lib/channel/channel_args.cc:110
#3  0x00007fc2384fa44f in grpc_channel_args_copy_and_add (src=src@entry=0x7fff3407f5f0, to_add=to_add@entry=0x7fff3407f520, num_to_add=num_to_add@entry=2)
    at /opt/app/admin/grpc-1.25.0/src/core/lib/channel/channel_args.cc:59
#4  0x00007fc2385d6909 in grpc_secure_channel_create (creds=0x436f674143434441, target=0x55b6ba68ff70 "localhost:50500", args=args@entry=0x7fff3407f5f0,
    reserved=reserved@entry=0x0) at /opt/app/admin/grpc-1.25.0/src/core/ext/transport/chttp2/client/secure/secure_channel_create.cc:212
#5  0x00007fc2384f3006 in create_new_channel (channel=channel@entry=0x7fff3407f610, target=<optimized out>, args=..., creds=<optimized out>)
    at /opt/app/admin/grpc-1.25.0/src/php/ext/grpc/php_grpc.c:101
#6  0x00007fc2384f31c3 in restart_channels () at /opt/app/admin/grpc-1.25.0/src/php/ext/grpc/php_grpc.c:163
#7  0x00007fc24fb573bf in fork () from /lib64/libc.so.6
#8  0x00007fc24fb04bbc in _IO_proc_open@@GLIBC_2.2.5 () from /lib64/libc.so.6
#9  0x00007fc24fb04e4c in popen@@GLIBC_2.2.5 () from /lib64/libc.so.6
#10 0x000055b6b84520f6 in php_exec ()
#11 0x000055b6b84525b0 in php_exec_ex ()
#12 0x000055b6b85b636c in execute_ex ()
#13 0x000055b6b85bf043 in zend_execute ()
#14 0x000055b6b85164b3 in zend_execute_scripts ()
#15 0x000055b6b84b2710 in php_execute_script ()
#16 0x000055b6b85c6fea in php_cli_server_dispatch_script ()
#17 0x000055b6b85c7edb in php_cli_server_recv_event_read_request ()
#18 0x000055b6b85c8426 in php_cli_server_do_event_for_each_fd_callback ()
#19 0x000055b6b85c9200 in do_cli_server ()
#20 0x000055b6b832796e in main ()
```

This is also reproducible in an apache worker. I have not successfully reproduced it in a pure cli environment, though.

### PR DESCRIPTION
**Pull request by HannahShiSFB**
To fix #21321. The crash happened because we attempt to re-create the underlying `grpc_channel` after `fork()` by re-using information we saved in the PHP persistent list. But under some very peculiar situation (looks like especially when `opcache` extension is also enabled), some PHP objects have been pre-maturely freed by PHP. 

So the fix here is that, in `postfork_child()`, instead of `restart_channel()`, we just clear all the entries from our PHP persistent list. So if the child process wants to send RPCs, they need to create the `Grpc\Channel` again, instead of being able to re-use the Channel object from the parent process.

### CODE REVIEW

File: src/php/ext/grpc/channel.c [hunk 1]
```diff
@@ -586,6 +586,13 @@ void php_grpc_delete_persistent_list_entry(char *key, php_grpc_int key_len
   gpr_mu_unlock(&global_persistent_list_mu);
 }
 
+// Clean all channels in the persistent list
+// Called at post fork
+void php_grpc_clean_persistent_list(TSRMLS_D) {
```
Comment (stanley-cheung) [inline src/php/ext/grpc/channel.c:591]: Instead of refactoring out this `php_grpc_clean_persistent_list` function in `channel.c`, perhaps we can limit our changes to only `php_grpc.c`, and refactor out these 4 lines instead https://github.com/grpc/grpc/blob/master/src/php/ext/grpc/php_grpc.c#L435-L438, and call them in those 2 separate places, but within `php_grpc.c`

File: src/php/ext/grpc/php_grpc.c [hunk 2]
```diff
@@ -206,9 +206,8 @@ void postfork_child() {
   grpc_init();
   grpc_php_init_completion_queue(TSRMLS_C);
 
-  // re-create grpc_channel and point wrapped to it
-  // unlock wrapped grpc channel mutex
-  restart_channels();
+  // clean all channels in the persistent list
+  php_grpc_clean_persistent_list(TSRMLS_C);
```
Comment (stanley-cheung) [inline src/php/ext/grpc/php_grpc.c:210]: Instead of doing this here, perhaps we should do it slightly earlier in L193: https://github.com/grpc/grpc/blob/master/src/php/ext/grpc/php_grpc.c#L193

Also, we might be missing a `release_persistent_locks()` call in `postfork_child()`. We call `acquire_persistent_locks()` at `prefork_parent()`, and then `release_persistent_locks()` in `postfork_parent()`, but never in `postfork_child()`. Calling `zend_hash_clean()` without `release_persistent_locks()` will result in a hang. So we probably should it around L193 too. So I think the sequence should be

```
... in postfork_child()...

destroy_grpc_channels();

release_persistent_locks();

// OR a function to abstract out 2 callers within php_grpc.c
zend_hash_clean(&grpc_persistent_list);
zend_hash_destroy(&grpc_persistent_list);
zend_hash_clean(&grpc_target_upper_bound_map);
zend_hash_destroy(&grpc_target_upper_bound_map);
```

File: src/php/ext/grpc/php_grpc.c [hunk 3]
```diff
@@ -206,9 +206,8 @@ void postfork_child() {
   grpc_init();
   grpc_php_init_completion_queue(TSRMLS_C);
 
-  // re-create grpc_channel and point wrapped to it
-  // unlock wrapped grpc channel mutex
-  restart_channels();
```
Comment (stanley-cheung) [inline src/php/ext/grpc/php_grpc.c:211]: Also we probably should remove the code for the `restart_channels` function itself because no code is calling it now.

File: src/php/ext/grpc/channel.h [hunk 4]
```diff
@@ -60,6 +60,8 @@ void generate_sha1_str(char *sha1str, char *str, php_grpc_int len);
 void php_grpc_delete_persistent_list_entry(char *key, php_grpc_int key_len
                                            TSRMLS_DC);
 
+void php_grpc_clean_persistent_list(TSRMLS_D);
```
Comment (stanley-cheung) [inline src/php/ext/grpc/channel.h:63]: We probably don't need this.

File: src/php/ext/grpc/channel.c [hunk 5]
```diff
@@ -615,12 +622,11 @@ static void php_grpc_target_bound_dtor(php_grpc_zend_resource *rsrc
 #ifdef GRPC_PHP_DEBUG
 
 /**
-* Clean all channels in the persistent. Test only.
+* Clean all channels in the persistent
 * @return void
 */
 PHP_METHOD(Channel, cleanPersistentList) {
-  zend_hash_clean(&grpc_persistent_list);
```
Comment (stanley-cheung) [inline src/php/ext/grpc/channel.c:622]: We can probably leave this alone. Or we should see whether we need to call `zend_hash_destroy` like the other places too.

**Comment by stanley-cheung** [comment]
Please also add a check to the `Channel` object to make sure user can't call functions on it in the child process after fork().

File: src/php/ext/grpc/channel.c (hunk 1 above)
Comment (HannahShiSFB) [reply src/php/ext/grpc/channel.c:591]: comment addressed

File: src/php/ext/grpc/channel.c (hunk 5 above)
Comment (HannahShiSFB) [reply src/php/ext/grpc/channel.c:622]: comment addressed

File: src/php/ext/grpc/channel.h (hunk 4 above)
Comment (HannahShiSFB) [reply src/php/ext/grpc/channel.h:63]: comment addressed

File: src/php/ext/grpc/php_grpc.c (hunk 2 above)
Comment (HannahShiSFB) [reply src/php/ext/grpc/php_grpc.c:210]: comment addressed

File: src/php/ext/grpc/php_grpc.c (hunk 3 above)
Comment (HannahShiSFB) [reply src/php/ext/grpc/php_grpc.c:211]: comment addressed

**Comment by stanley-cheung** [comment]
@markdroth As discussed offline, this PR attempts to _not_ recreate the underlying `grpc_channel` in `postfork_child()` handler and move the responsibility to the user, which aligns with the Python implementation. Can you approve this approach conceptually? Thanks!

**Comment by markdroth** [comment]
LGTM as a conceptual approach.  Thanks!

**Comment by stanley-cheung** [comment]
I have done a final round of testing using the user's test case: https://github.com/kellegous/grpc-21321 and https://github.com/dkop/grpc-21321. The crash went away after applying this PR. I am going to merge this now and this is going into the next 1.30.0 release.
