### PR TITLE
[HTTP Proxy] Support CIDR blocks in `no_proxy` config

### LINKED ISSUE #22681: NO_PROXY handling doesn't support CIDR addresses
# What version of gRPC and what language are you using?

1.27.1 python

### What operating system (Linux, Windows,...) and version?

Debian 10 (python:3.7-slim)

### What runtime / compiler are you using (e.g. python version or version of gcc)

Python 3.7

### What did you do?

Spun up a container in a local k8s development environment with NO_PROXY set to include the local CIDR range for the cluster internal IP addresses in addition to other settings for the internal corp network so that it could connect via GRPC to another pod within the cluster while also accessing resources external to the corporate network.

### What did you expect to see?

Client should connect without going through the proxy

### What did you see instead?

Debug logs showing response from the proxy and connection failed.

### Anything else we should know about your project / environment?

Looking at the code https://github.com/grpc/grpc/blob/4466a4ce6156cd9b93a7ce130bf3f59b9c09d700/src/core/ext/filters/client_channel/http_proxy.cc#L147-L154 I can see that it currently should work for complete matches for IP addresses, hostnames and I think domains, though I'm a little rusty with C so I'm not completely sure. Looks like the piece of code `&(server_host.get()[uri_len - no_proxy_len]))` is indexing into the string for a starting point so that if you have `hostname.domainname` and `.domainname` is in the no_proxy that it would start the comparison from the 9th character in the server_host variable in order to compare domain names only.

Though this does look like there is a subtle bug should someone use a domain name in the no_proxy without a leading dot as `domainname` would also match `hostname.someotherdomainname` as well

I'm thinking making use of something like https://stackoverflow.com/a/28535174/1597808 and if the return value is >=0 then https://stackoverflow.com/a/31041121/1597808 would be used to complete the comparison. Little unsure if it's correct to convert the server_host to an IP address in such a case if it's not already an IP.

Is it worth making a stab at fixing this?

### PR DESCRIPTION
**Pull request by stanhu**
This commit adds support for using CIDR blocks defined in the `no_proxy` environment variable. For example:

```
http_proxy=http://localhost:8080 no_proxy=10.10.0.0/24
```

The example above would bypass the proxy if the server IP matched 10.10.0.0 - 10.10.0.255.

Closes #22681

### CODE REVIEW

File: src/core/ext/filters/client_channel/http_proxy.cc [hunk 1]
```diff
@@ -53,6 +55,33 @@
...
+  if (!server_address.ok()) {
+    return false;
+  }
+
+  std::vector<absl::string_view> cidr = absl::StrSplit(no_proxy_entry, '/', absl::SkipEmpty());
+  if (cidr.size() == 0 || cidr.size() > 2) {
+    return false;
+  }
+
+  auto proxy_address = StringToSockaddr(cidr[0], 0);
```
Comment (stanhu) [inline src/core/ext/filters/client_channel/http_proxy.cc:69]: We may want to parse port numbers for exact IP matches. Golang does this: https://github.com/golang/go/blob/f771edd7f92a47c276d65fbd9619e16a786c6746/src/vendor/golang.org/x/net/http/httpproxy/proxy.go#L38-L50

**Comment by stanhu** [comment]
@yashykt Would you be able to review?

**Comment by yashykt** [comment]
Sorry for the delay. I'll take a look at this this week.

File: src/core/ext/filters/client_channel/http_proxy.cc [hunk 2]
```diff
@@ -52,6 +55,28 @@
 namespace grpc_core {
 namespace {
 
+static bool serverInCIDRRange(std::string server_host, absl::string_view no_proxy_entry) {
+  auto server_address = StringToSockaddr(server_host, 0);
+  if (!server_address.ok()) {
+    return false;
+  }
+
```
Comment (yashykt) [inline src/core/ext/filters/client_channel/http_proxy.cc:63]: please remove unnecessary blank lines. Or maybe replace them with comments. same thing throughout

File: src/core/ext/filters/client_channel/http_proxy.cc [hunk 3]
```diff
@@ -52,6 +55,28 @@
...
+  if (cidr.size() != 2) {
+    return false;
+  }
+
+  auto proxy_address = StringToSockaddr(cidr[0], 0);
+  if (!proxy_address.ok()) {
+    return false;
+  }
+
+  uint32_t mask_bits = atoi(std::string(cidr[1]).c_str());
```
Comment (yashykt) [inline src/core/ext/filters/client_channel/http_proxy.cc:74]: please use absl::SimpleAtoi instead

File: test/core/client_channel/http_proxy_mapper_test.cc [hunk 4]
```diff
@@ -70,6 +70,121 @@ TEST(NoProxyTest, EmptyEntries) {
...
 }
 
+// Test entries with CIDR blocks (Class A) in 'no_proxy' list.
+TEST(NoProxyTest, CIDRClassAEntries) {
+  ScopedSetEnv no_proxy("foo.com,192.168.0.255/8");
+  auto args = ChannelArgs().Set(GRPC_ARG_HTTP_PROXY, "http://proxy.google.com");
+  EXPECT_EQ(HttpProxyMapper().MapName("dns:///192.0.1.1:443", &args),
+            absl::nullopt);
+  EXPECT_EQ(args.GetString(GRPC_ARG_HTTP_CONNECT_SERVER), absl::nullopt);
+
```
Comment (yashykt) [inline test/core/client_channel/http_proxy_mapper_test.cc:80]: can you add some comments please - something like - "address not matching no_proxy cidr block"

File: src/core/ext/filters/client_channel/http_proxy.cc [hunk 5]
```diff
@@ -52,6 +55,28 @@
 namespace grpc_core {
 namespace {
 
+static bool serverInCIDRRange(std::string server_host, absl::string_view no_proxy_entry) {
```
Comment (yashykt) [inline src/core/ext/filters/client_channel/http_proxy.cc:58]: should be `ServerInCIDRRange`

File: test/core/client_channel/http_proxy_mapper_test.cc [hunk 6]
```diff
@@ -70,6 +70,121 @@ TEST(NoProxyTest, EmptyEntries) {
...
+  EXPECT_EQ(HttpProxyMapper().MapName("dns:///192.168.1.0:443", &args),
+            "proxy.google.com");
+  EXPECT_EQ(args.GetString(GRPC_ARG_HTTP_CONNECT_SERVER),
+            "192.168.1.0:443");
+}
+
+// Test entries with CIDR blocks (exact match) in 'no_proxy' list.
+TEST(NoProxyTest, CIDREntries) {
```
Comment (yashykt) [inline test/core/client_channel/http_proxy_mapper_test.cc:133]: Rename to CIDREntriesExactMatch maybe?

File: test/core/client_channel/http_proxy_mapper_test.cc [hunk 7]
```diff
@@ -70,6 +70,121 @@ TEST(NoProxyTest, EmptyEntries) {
...
+  EXPECT_EQ(args.GetString(GRPC_ARG_HTTP_CONNECT_SERVER), absl::nullopt);
+
+  EXPECT_EQ(HttpProxyMapper().MapName("dns:///192.168.1.1:443", &args),
+            "proxy.google.com");
+  EXPECT_EQ(args.GetString(GRPC_ARG_HTTP_CONNECT_SERVER),
+            "192.168.1.1:443");
+}
+
+// Test entries with CIDR blocks (Class D) in 'no_proxy' list.
+TEST(NoProxyTest, CIDRClassDEntries) {
```
Comment (yashykt) [inline test/core/client_channel/http_proxy_mapper_test.cc:118]: This test seems to be repetitive.

File: test/core/client_channel/http_proxy_mapper_test.cc [hunk 8]
```diff
@@ -70,6 +70,121 @@ TEST(NoProxyTest, EmptyEntries) {
...
+            "proxy.google.com");
+  EXPECT_EQ(args.GetString(GRPC_ARG_HTTP_CONNECT_SERVER),
+            "193.0.1.1:443");
+}
+
+// Test entries with CIDR blocks (Class B) in 'no_proxy' list.
+TEST(NoProxyTest, CIDRClassBEntries) {
+  ScopedSetEnv no_proxy("foo.com,192.168.0.255/16");
+  auto args = ChannelArgs().Set(GRPC_ARG_HTTP_PROXY, "http://proxy.google.com");
+  absl::optional<std::string> name_to_resolve;
```
Comment (yashykt) [inline test/core/client_channel/http_proxy_mapper_test.cc:91]: I suspect this showed up since you probably copied the template of `EmptyEntries` but it does not seem to be needed.

**Review by yashykt — CHANGES_REQUESTED** [review]
Sorry for the delay! :pray:

File: src/core/ext/filters/client_channel/http_proxy.cc [hunk 9]
```diff
@@ -168,7 +192,10 @@ absl::optional<std::string> HttpProxyMapper::MapName(
       std::vector<absl::string_view> no_proxy_hosts =
           absl::StrSplit(*no_proxy_str, ',', absl::SkipEmpty());
       for (const auto& no_proxy_entry : no_proxy_hosts) {
-        if (absl::EndsWithIgnoreCase(server_host, no_proxy_entry)) {
+	auto entry = absl::StripAsciiWhitespace(no_proxy_entry);
+
```
Comment (yashykt) [inline src/core/ext/filters/client_channel/http_proxy.cc:196]: missed this :)

**Review by yashykt — COMMENTED** [review]
Also, could I request that you do not force-push/delete older commits that were reviewed. It would help maintain review history. The commits would be squashed at merge time anyway.

**Comment by stanhu** [comment]
> Also, could I request that you do not force-push/delete older commits that were reviewed. It would help maintain review history. The commits would be squashed at merge time anyway.

Sure, thing. I'm curious, though, how it maintains review history. The pull request still has the comments?

**Comment by yashykt** [comment]
> Sure, thing. I'm curious, though, how it maintains review history. The pull request still has the comments?
If the previous commits remain, I can do a diff and see what changed from the previous commit, as opposed to having to look at the entire PR again.

**Review by yashykt — APPROVED** [review]

**Comment by stanhu** [comment]
Trying to reproduce this build failure. Am I just missing this?

```diff
diff --cc BUILD
index 4ec32ff966,4ec32ff966..9159917f7c
--- a/BUILD
+++ b/BUILD
@@@ -2756,10 -2756,10 +2756,12 @@@ grpc_cc_library
          "//src/core:ext/filters/client_channel/lb_policy/child_policy_handler.cc",
          "//src/core:ext/filters/client_channel/lb_policy/oob_backend_metric.cc",
          "//src/core:ext/filters/client_channel/local_subchannel_pool.cc",
++        "//src/core:ext/filters/client_channel/parse_address.cc",
          "//src/core:ext/filters/client_channel/retry_filter.cc",
          "//src/core:ext/filters/client_channel/retry_service_config.cc",
          "//src/core:ext/filters/client_channel/retry_throttle.cc",
          "//src/core:ext/filters/client_channel/service_config_channel_arg_filter.cc",
++        "//src/core:ext/filters/client_channel/sockaddr_utils.cc",
          "//src/core:ext/filters/client_channel/subchannel.cc",
          "//src/core:ext/filters/client_channel/subchannel_pool_interface.cc",
          "//src/core:ext/filters/client_channel/subchannel_stream_client.cc",
@@@ -2782,9 -2782,9 +2784,11 @@@
          "//src/core:ext/filters/client_channel/lb_policy/oob_backend_metric.h",
          "//src/core:ext/filters/client_channel/lb_policy/oob_backend_metric_internal.h",
          "//src/core:ext/filters/client_channel/local_subchannel_pool.h",
++        "//src/core:ext/filters/client_channel/parse_address.h",
          "//src/core:ext/filters/client_channel/retry_filter.h",
          "//src/core:ext/filters/client_channel/retry_service_config.h",
          "//src/core:ext/filters/client_channel/retry_throttle.h",
++        "//src/core:ext/filters/client_channel/sockaddr_utils.h",
          "//src/core:ext/filters/client_channel/subchannel.h",
          "//src/core:ext/filters/client_channel/subchannel_interface_internal.h",
          "//src/core:ext/filters/client_channel/subchannel_pool_interface.h",
```

**Comment by yashykt** [comment]
oops, looks like I overwrote your commit. My bad! But, I think that should fix the build issues.

**Comment by stanhu** [comment]
Thanks! I wasn't able to reproduce the error locally with `bazel build :all`.

File: src/core/ext/filters/client_channel/http_proxy.cc [hunk 10]
```diff
@@ -52,6 +57,30 @@
 namespace grpc_core {
 namespace {
 
+bool ServerInCIDRRange(std::string server_host,
+                       absl::string_view no_proxy_entry) {
+  auto server_address = StringToSockaddr(server_host, 0);
+  if (!server_address.ok()) {
+    return false;
+  }
+  std::vector<absl::string_view> cidr =
```
[the remark this answers is not in the document]
Comment (stanhu) [reply src/core/ext/filters/client_channel/http_proxy.cc]: Thanks!

File: src/core/ext/filters/client_channel/http_proxy.cc [hunk 11]
```diff
@@ -57,23 +57,24 @@
...
   auto server_address = StringToSockaddr(server_host, 0);
   if (!server_address.ok()) {
     return false;
   }
-  std::vector<absl::string_view> cidr =
-      absl::StrSplit(no_proxy_entry, '/', absl::SkipEmpty());
-  if (cidr.size() != 2) {
+
+  std::pair<absl::string_view, absl::string_view> possible_cidr =
+    absl::StrSplit(no_proxy_entry, absl::MaxSplits('/', 2));
```
Comment (markdroth) [inline src/core/ext/filters/client_channel/http_proxy.cc:68]: Don't you still want `absl::SkipEmpty()` here?  Note that you can use both that and `MaxSplits()`:

```
absl::StrSplit(no_proxy_entry, absl::MaxSplits('/', 2), absl::SkipEmpty());
```

File: src/core/ext/filters/client_channel/http_proxy.cc [hunk 12]
```diff
@@ -57,23 +57,24 @@
...
+bool ServerInCIDRRange(absl::string_view server_host,
                        absl::string_view no_proxy_entry) {
   auto server_address = StringToSockaddr(server_host, 0);
   if (!server_address.ok()) {
     return false;
   }
-  std::vector<absl::string_view> cidr =
-      absl::StrSplit(no_proxy_entry, '/', absl::SkipEmpty());
-  if (cidr.size() != 2) {
+
```
Comment (markdroth) [inline src/core/ext/filters/client_channel/http_proxy.cc:66]: Nit: Please remove blank line.

File: src/core/ext/filters/client_channel/http_proxy.cc (hunk 11 above)
Comment (markdroth) [inline src/core/ext/filters/client_channel/http_proxy.cc:68]: This needs to be indented two more spaces.

**Review by markdroth — APPROVED** [review]
I've re-triggered the tests.  @yashykt, I'll let you get this merged once everything is passing.

**Comment by yashykt** [comment]
@stanhu can you please run -
```
tools/distrib/iwyu.sh
tools/distrib/clang_format_code.sh
```

**Comment by yashykt** [comment]
Thanks for the contribution!
