### PR TITLE
Flush printers in protoc plugins properly

### LINKED ISSUE #1769: grpc_csharp_plugin.exe crashes on Windows
When trying to use grpc_csharp_plugin on windows (for the helloworld example):

C:\Users\jtattermusch\github\grpc-common\csharp>protoc -I Greeter/protos --csharp_out=Greeter --grpc_out=Greeter --plugin=protoc-gen-grpc=grpc_csharp_plugin.exe
 Greeter/protos/helloworld.proto
[libprotobuf FATAL c:\users\jtattermusch\github\grpc\third_party\protobuf\src\go
ogle\protobuf\io\zero_copy_stream_impl_lite.cc:190] CHECK failed: (count) <= (ta
rget_->size()):
--grpc_out: protoc-gen-grpc: Plugin failed with status code 3.

### PR DESCRIPTION
**Pull request by jtattermusch**
Fixes #1769.
I also fixed generators for other languages when I spotted the same potential problem.

FYI @tbetbetbe, @jcanizales as this impacts ruby and objC.

### CODE REVIEW

**Comment by nicolasnoble** [comment]
So, isn't there any actual explicit flush call to the Printer object ? This would be much more explicit than an obscure scope addition. This is bound to break again in the future otherwise.

This would also qualify for a compiler bug in my opinion, if Visual Studio is really destroying objets before running the move operator. I haven't been able to find the relevant spec from C++ though.

**Comment by jtattermusch** [comment]
Unfortunately, neither StringOutputStream nor Printer provides a way to flush aside from calling a destructor.

**Comment by jcanizales** [comment]
Weird, why aren't wee seeing this bug when running the ObjC plugin?

**Comment by jtattermusch** [comment]
I think that basically depends on the compiler (if he decides to optimize the return value with move semantics). So depending on how you call your function, it either breaks under MSVC or not. But I think it would be better if some C++ expert explained that properly ;-).

File: src/compiler/objective_c_generator.cc [hunk 1]
```diff
@@ -176,65 +176,71 @@ void PrintMethodImplementations(Printer *printer,
 
 string GetHeader(const ServiceDescriptor *service, const string prefix) {
   string output;
-  grpc::protobuf::io::StringOutputStream output_stream(&output);
-  Printer printer(&output_stream, '$');
+  {
+    // Scope the output stream so it closes and finalizes output to the string.
```
Comment (jcanizales) [inline src/compiler/objective_c_generator.cc]: Let's make clear that we know that's what's _supposed_ to happen when the function returns anyway, but we've found it's not always the case. Or just:
```cpp
// The extra scope is needed due to gRPC issue #1769
```
Whichever way to word it you prefer, as long as it's specific so someone doesn't find this in a year and removes an apparently-unnecessary scope.

Comment (nicolasnoble) [inline src/compiler/objective_c_generator.cc]: Note that this isn't a grpc issue per-se. I'm 94.3% certain we could file that as a compiler bug. There's no way moving the string before calling the local destructors is an acceptable behavior. The bad part we're exhibiting here (and I just realized that) is that we're taking addresses of temporaries, which is supposed to be a compiler warning.

If you want to be more specific in that comment, I'd rather suggest saying this is to solve a Visual Studio problem with the destruction ordering of temporaries vs the move operation.

Comment (nicolasnoble) [inline src/compiler/objective_c_generator.cc]: Also, I'd be surprised if that isn't affecting more protoc code. I am fairly certain they have the same code pattern in there.

Comment (jcanizales) [inline src/compiler/objective_c_generator.cc]: >  we're taking addresses of temporaries

You mean the string? Taking the address of an automatic variable is ok, if you don't use that address beyond the variable's life.

If `Printer` expects the `OutputStream` to be alive during `~Printer`, then we actually can't have both being local variables in the same scope, as there's no reason the compiler should call the destructors in the order we expect. I now think so far we've just been lucky, and the additional scope is the way to satisfy Printer's contract. If OutputStream has the same requirement for the string pointer it receives, then we actually need two scopes IMO. Ew.

> There's no way moving the string before calling the local destructors is an acceptable behavior.

Well if the compiler wants to move it at all, it has to do it before calling the local destructors, or that will destruct the string too _before_ moving it. I would bet the reason we're not seeing it elsewhere is the compilers being conservative and not moving, plus string's copy constructor not copying the actual characters.

Comment (jcanizales) [inline src/compiler/objective_c_generator.cc]: Oh, scratch most of that. The destruction order [is determined](http://stackoverflow.com/questions/14688285/c-local-variable-destruction-order).

Comment (jcanizales) [inline src/compiler/objective_c_generator.cc]: The point that this _might_ be behavior allowed by the standard remains, per [the conversation Jan found](http://programmers.stackexchange.com/questions/258238/move-semantics-in-c-move-return-of-local-variables).

Comment (nicolasnoble) [inline src/compiler/objective_c_generator.cc]: Yes, so. If you do:

```
A a;
B * b = new B(&a);
```
then the constructor of B is taking the address of a temporary. That is supposed to be a warning. I guess it doesn't happen here because we're doing everything on the stack. But still.

For the destruction order, yes, it is determined. The problem here is that the destruction occurs AFTER the move operator is being called to move the variable `output`. While technically a move operation isn't a destruction, it is supposed to leave the object in a destructed state. Meaning that the actual destruction of `output` happens before the actual destruction of `output_stream` and `printer`, which is against the spec.

Comment (jcanizales) [inline src/compiler/objective_c_generator.cc]: > That is supposed to be a warning.

I don't think that's true; taking the address of an automatic variable is a perfectly acceptable thing to do. A very common use case of it is to pass the address of a local variable to a function call (e.g. `&error`), as "output parameters." I'd think passing it to a constructor is as fine.

> which is against the spec

Are we sure of that? The conversation in StackOverflow seems to me to imply the spec authors decided to allow it. Without that, there's no way to move on return, or you'd destruct your object before moving it.

In any case, back to this PR: let's make clear in the comment that without the scope, the string might get moved before the printer flushes _which results in a crash_ (even if it ends up being some compiler's bug).

**Comment by nicolasnoble** [comment]
Alright, I know exactly what's going on now. I'm going to do a PR against protobuf to have a better fix.

**Comment by nicolasnoble** [comment]
Alright, we will go with this current fix. Let's leave the comments as they are.

**Comment by nicolasnoble** [comment]
You will also need to do that one in the release branch.
