### PR TITLE
Fix http_proxy proxy mapper to not set proxy_name when returning false.

### LINKED ISSUE #12543: GRPC Erroneously talks to an HTTP proxy when connecting to a Unix Domain Socket
### What version of gRPC and what language are you using?

gRPC v1.4.2

Languages in use:

 - Go
 - PHP
 - Ruby
 
### What operating system (Linux, Windows, …) and version?
 
Scientific Linux 7, NixOS 17.03
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
 - gcc version 5.4.0 (GCC)
 - ruby 2.3.3.p222
 - php 7.1.x
 
### What did you do?

1. Have an `http_proxy` in your environment:

```
$ echo $http_proxy
http://httpproxy.mydomain:8080

$ echo $no_proxy
.mydomain,localhost,127.0.0.1
```

2. Connect to a GRPC server on a local domain socket:

```ruby
Foo::Bar::Stub.new("unix:/var/run/mydaemon.sock", :this_channel_is_insecure)
```

3. Ouch! GRPC chats up the proxy!

```
$ pry
[1] pry(main)> require 'mything'
=> true

[2] pry(main)> config = {:socket => '/tmp/mydaemon.sock'}
=> {:socket=>"/tmp/mydaemon.sock"}

[3] pry(main)> conn = MyThing::Client.new(config)
=> #<MyThing::Client:0x007f06f413a248
 @mything_stub=
  #<MyThnig::Stub:0x007f06f413a130
   @ch=#<GRPC::Core::Channel:0x007f06f4139ff0>,
   @host="unix:/tmp/mydaemon.sock",
   @propagate_mask=nil,
   @timeout=1969-12-31 18:59:59 -0500>>

[4] pry(main)> conn.mything.a_grpc_call('fizzbuzz')
GRPC::Unavailable: 14:Endpoint read failed
from /opt/ruby/2.3/lib/ruby/gems/2.3.0/gems/grpc-1.6.0-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:31:in `check_status'
```
 
### What did you expect to see?
 
GRPC should not talk to an http_proxy when talking to local unix domain sockets.
 
### What did you see instead?

GRPC tried to use the remote HTTP proxy to talk to a local unix domain socket.

### PR DESCRIPTION
**Pull request by markdroth**
Fixes #12543.

### CODE REVIEW

**Comment by yashykt** [comment]
setting name_to_resolve to NULL was the fix?

**Comment by markdroth** [comment]
Yes.  But this also fixes a potential memory leak whereby we failed to free `*name_to_resolve` before returning false.

An argument can be made that the code in client_channel.c should actually check the return value, but it's not clear that that's really a win, because the `proxy_mapper_map_name()` contract is that it will return a name to resolve only if it returns true.  If it does this when returning false, that's always a memory leak, so it's clearly bad behavior.  A better alternative might be to just change `proxy_mapper_map_name()` to return void, but I don't really have cycles to take on that API change right now.

File: src/core/ext/filters/client_channel/http_proxy.c [hunk 1]
```diff
@@ -98,18 +98,12 @@ static bool proxy_mapper_map_name(grpc_exec_ctx* exec_ctx,
             "'http_proxy' environment variable set, but cannot "
             "parse server URI '%s' -- not using proxy",
             server_uri);
-    if (uri != NULL) {
-      gpr_free(user_cred);
-      grpc_uri_destroy(uri);
-    }
-    return false;
+    goto no_use_proxy;
```
Comment (yashykt) [inline src/core/ext/filters/client_channel/http_proxy.c]: Adding gotos is going to create the jump errors over no_proxy_str at line 108 for the C to C++ conversion. This can be solved by adding
char *no_proxy_str = NULL at the start of the function.

Comment (markdroth) [reply src/core/ext/filters/client_channel/http_proxy.c]: Done.

**Comment by markdroth** [comment]
Known issues: #12747 #11737 #12138 #11745 #12748 #12595
