### PR TITLE
bad_client test: do multiple reads if needed to read full server response

### LINKED ISSUE #11522: Flaky large_metadata_bad_client_test
Currently at master (5678ac0c8e4a0d30f28e88712302c098cbe5097c):

```
...
D0616 14:36:03.139888825   66849 ev_posix.c:106]             Using polling engine: poll-cv
D0616 14:36:03.139900024   66849 dns_resolver.c:301]         Using native dns resolver
D0616 14:36:03.140290447   66851 parsing.c:523]              received initial metadata size exceeds limit (16507 vs. 16384)
E0616 14:36:03.140404358   66849 large_metadata.c:180]       assertion failed: *p++ == 4



*******************************
Caught signal SIGABRT
bins/opt/large_metadata_bad_client_test[0x4725ae]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x10330)[0x7fe51f10b330]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37)[0x7fe51ed69c37]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x148)[0x7fe51ed6d028]
bins/opt/large_metadata_bad_client_test[0x40378e]
bins/opt/large_metadata_bad_client_test[0x403b3a]
bins/opt/large_metadata_bad_client_test[0x409f6e]
bins/opt/large_metadata_bad_client_test[0x40d322]
bins/opt/large_metadata_bad_client_test[0x409f6e]
bins/opt/large_metadata_bad_client_test[0x40a067]
bins/opt/large_metadata_bad_client_test[0x403f8e]
bins/opt/large_metadata_bad_client_test[0x40314e]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7fe51ed54f45]
bins/opt/large_metadata_bad_client_test[0x4031c7]
FAILED: bins/opt/large_metadata_bad_client_test GRPC_POLL_STRATEGY=poll-cv [ret=-6, pid=66849]
```

It's quicker to reproduce in a UBSAN run:

`$ ./tools/run_tests/run_tests.py -l c -c ubsan  -r large_metadata_bad_client_test -n 1000` fails almost immediately.

### PR DESCRIPTION
**Pull request by markdroth**
Fixes #11522.

### CODE REVIEW

File: test/core/bad_client/tests/large_metadata.c [hunk 1]
```diff
@@ -166,34 +167,41 @@ static void server_verifier_sends_too_much_metadata(grpc_server *server,
   cq_verifier_destroy(cqv);
 }
 
-static void client_validator(grpc_slice_buffer *incoming) {
+static bool client_validator(grpc_slice_buffer *incoming) {
+  for (size_t i = 0; i < incoming->count; ++i) {
+    const char* s = (const char*)GRPC_SLICE_START_PTR(incoming->slices[i]);
+    char *hex = gpr_dump(s, GRPC_SLICE_LENGTH(incoming->slices[i]),
+                         GPR_DUMP_HEX | GPR_DUMP_ASCII);
+    gpr_log(GPR_INFO, "RESPONSE SLICE %zu: %s", i, hex);
```
Comment (dgquintas) [inline test/core/bad_client/tests/large_metadata.c]: no `%zu` on windows, need to use `%lu` and cast `i` to unsigned long.

Comment (markdroth) [inline test/core/bad_client/tests/large_metadata.c]: Doh!  I always forget that.

Fixed.

**Comment by markdroth** [comment]
Known failures: #10894 #11745
