### PR TITLE
Fix race condition in GRPCCall

### LINKED ISSUE #2690: [objective-c] GRXImmediateWriter.m:writeUntilPausedOrStopped  _enumerator may be nil
[objective-c] GRXImmediateWriter.m:writeUntilPausedOrStopped  _enumerator may be nil。

grpc ios client crash, and point that in GRXImmediateWriter.m:writeUntilPausedOrStopped  _enumerator is nil.

the crash is sometimes happen, i suppose the reason is the other thread invoke   [writeable writesFinishedWithError:errorOrNil] async when some error happen like tcp closed。

@jcanizales

### PR DESCRIPTION
**Pull request by jcanizales**
Fixes #2690 

(Although debugging it revealed a bunch of other issues, but they'll be tracked separately).

@DavidPhillipOster to review.

Tested by running the OAuth2 sample app, which luckily was triggering the race condition on more than half the RPCs made.

### CODE REVIEW

File: src/objective-c/RxLibrary/GRXForwardingWriter.m [hunk 1]
```diff
@@ -48,7 +48,10 @@ - (instancetype)init {
 // Designated initializer
 - (instancetype)initWithWriter:(GRXWriter *)writer {
   if (!writer) {
-    [NSException raise:NSInvalidArgumentException format:@"writer can't be nil."];
+    return nil;
+  }
+  if (writer.state != GRXWriterStateNotStarted) {
+    [NSException raise:NSInvalidArgumentException format:@"writer can't be started."];
```
Comment (DavidPhillipOster) [inline src/objective-c/RxLibrary/GRXForwardingWriter.m]: The error text is hard to understand. better:
"writer argument must not have already started."

File: src/objective-c/GRPCClient/GRPCCall.m [hunk 2]
```diff
@@ -139,8 +146,10 @@ - (void)finishWithError:(NSError *)errorOrNil {
   _self = nil;
```
Comment (DavidPhillipOster) [inline src/objective-c/GRPCClient/GRPCCall.m]: This _self = nil; is very peculiar, and doesn't do anything, since self must be of storage class unsafe_unretained or Objective-C could not work. If you want an object to retain itself while a call is in progress you can have an instance variable:

GRPCCall *_retainSelf;

and when you want to make sure it will not be dealloc'ed, do a 
_retainSelf = self;

and in the finish, do:
_retainSelf = nil;

but there better be timeout error callbacks on the finish, or calls GRPCCalls that wait forever will never get dealloc'ed

File: src/objective-c/GRPCClient/GRPCCall.m [hunk 3]
```diff
@@ -139,8 +146,10 @@ - (void)finishWithError:(NSError *)errorOrNil {
...
 
   // If there were still request messages coming, stop them.
-  _requestWriter.state = GRXWriterStateFinished;
-  _requestWriter = nil;
+  @synchronized(_requestWriter) {
```
Comment (DavidPhillipOster) [inline src/objective-c/GRPCClient/GRPCCall.m]: I'm surprised Xcode's 'Analyze' command didn't flag this: _requestWriter is sometimes nil (in fact it is set to nil inside the block) and you should never @synchronize(nil)

did you mean:
@synchronized(self) { ... } ?

since you need to synchronize on an object with a lifetime longer than the @synchronized block

File: src/objective-c/GRPCClient/GRPCCall.m [hunk 4]
```diff
@@ -240,12 +249,14 @@ - (void)writeMessage:(NSData *)message withErrorHandler:(void (^)())errorHandler
     // Resume the request writer.
     GRPCCall *strongSelf = weakSelf;
     if (strongSelf) {
-      strongSelf->_requestWriter.state = GRXWriterStateStarted;
+      @synchronized(_requestWriter) {
```
Comment (DavidPhillipOster) [inline src/objective-c/GRPCClient/GRPCCall.m]: As described above, all access to the _requestWrite's state, both getting and setting, have to be _synchronized on the same object.

@synchronized(strongSelf) { } in this case to match the @synchronized(self) above (they are the same object, its just that assigning to strongSelf can set strongSelf to nil if self got deallocated before the callback was called.)

File: src/objective-c/GRPCClient/GRPCCall.m [hunk 5]
```diff
@@ -273,7 +286,9 @@ - (void)finishRequestWithErrorHandler:(void (^)())errorHandler {
 }
 
 - (void)writesFinishedWithError:(NSError *)errorOrNil {
-  _requestWriter = nil;
+  @synchronized(_requestWriter) {
```
Comment (DavidPhillipOster) [inline src/objective-c/GRPCClient/GRPCCall.m]: I'm surprised Xcode's 'Analyze' command didn't flag this: _requestWriter is sometimes nil (in fact it is set to nil inside the block) and you should never @synchronize(nil)

did you mean:
@synchronized(self) { ... } ?

File: src/objective-c/GRPCClient/GRPCCall.m [hunk 6]
```diff
@@ -327,7 +342,9 @@ - (void)invokeCall {
     }
   }];
   // Now that the RPC has been initiated, request writes can start.
-  [_requestWriter startWithWriteable:self];
+  @synchronized(_requestWriter) {
```
Comment (DavidPhillipOster) [inline src/objective-c/GRPCClient/GRPCCall.m]: As described above, all access to the _requestWrite's state, both getting and setting, have to be _synchronized on the same object. so @synchronized(self){ }

File: src/objective-c/GRPCClient/GRPCCall.m (hunk 2 above)
Comment (jcanizales) [inline src/objective-c/GRPCClient/GRPCCall.m]: `_self` there is actually an instance variable, but I can see how the name is confusing :D I'll rename it to `_retainSelf`.

> but there better be timeout error callbacks on the finish, or calls GRPCCalls that wait forever will never get dealloc'ed

I'll be adding a way for the user to specify a timeout, but the plan was to have the default be infinite. Having a finite default value makes sense, but how to pick one?

Comment (DavidPhillipOster) [inline src/objective-c/GRPCClient/GRPCCall.m]: I don't think it is possible to pick a single default value that will make sense in all circumstances - sufficiently long that calls that will eventually succeed aren't needlessly pruned (think space probes that are light-days away) yet sufficiently short that RAM doesn't fill up with calls that are uselessly old. Best to document that calls in-flight retain themselves until they either complete or are cancelled, or give up on the retain idea, and just add a dealloc that cancels if needed so that it's the client programmer's responsibility to keep references to calls-in-flight that the client cares about.

Maybe set the default to 1 minute,  with a header comment documenting that the client programmer may need to change this.

See http://www.ibiblio.org/harris/500milemail.html for more information.

File: src/objective-c/GRPCClient/GRPCCall.m (hunk 3 above)
Comment (jcanizales) [inline src/objective-c/GRPCClient/GRPCCall.m]: > you should never **@synchronize**(nil)

I was going by this: http://rykap.com/objective-c/2015/05/09/synchronized.html. The guy tested that `@synchronized(nil)` just bypasses locking; and setting the synchronized variable to `nil` inside the block is ok (in the sense that it doesn't prevent the lock from unlocking at the end of the block). But on further reading, apparently it's undocumented by Apple?

Synchronizing on `self` wouldn't stop the code from messaging `_requestWriter` concurrently with other threads outside my control (the requests writer is passed by the user on `init...`); so it really needs to be `@synchronized(_requestWriter)`.

I'm thinking a way out of this is just to _not set_ it to `nil`. When the writer finishes (because we tell it so, or because it run out of stuff to write), it'll release its reference to us (the call object is its writeable), so the retain cycle writer <-> call is guaranteed to be broken.

Comment (DavidPhillipOster) [inline src/objective-c/GRPCClient/GRPCCall.m]: > I was going by this: http://rykap.com/objective-c/2015/05/09/synchronized.html. 

Please don't depend on undocumented behavior. 'undocumented behavior' is defined as 'behavior that has not been documented by Apple'

It looks like you  do want 
@synchronized(_requestWriter) {
  _requestWriter.state = GRXWriterStateFinished;
}
_requestWriter = nil;

as long as all objects that look at the same requestWriter @synchronize on that requestWriter - races are things like:
if (_requestWriter.state != GRXWriterStateXXX) {
   _requestWriter.state = GRXWriterStateYYY;
}

An if () {} like this would have to be inside a @synchronized(_requestWriter) { }

File: src/objective-c/RxLibrary/GRXForwardingWriter.m (hunk 1 above)
Comment (jcanizales) [inline src/objective-c/RxLibrary/GRXForwardingWriter.m]: Done (fd51dff).

File: src/objective-c/GRPCClient/GRPCCall.m (hunk 2 above)
Comment (jcanizales) [inline src/objective-c/GRPCClient/GRPCCall.m]: > I'll rename it to `_retainSelf`.

Done (eb87b46).

File: src/objective-c/GRPCClient/GRPCCall.m (hunk 3 above)
Comment (jcanizales) [inline src/objective-c/GRPCClient/GRPCCall.m]: Stopped setting `_requestWriter` to `nil`: 297ed7b.

Comment (jcanizales) [inline src/objective-c/GRPCClient/GRPCCall.m]: Oops, I went with that before reading your response.

Comment (DavidPhillipOster) [inline src/objective-c/GRPCClient/GRPCCall.m]: LG

Comment (jcanizales) [inline src/objective-c/GRPCClient/GRPCCall.m]: `@synchronized(_requestWriter) {...}` with non-synchronized `_requestWriter = nil;` in another thread could have the first thread reading `self->_requestWriter` (to know what to lock on) concurrently with the second thread writing it, and those two things aren't atomic with ARC, are they?

Comment (DavidPhillipOster) [inline src/objective-c/GRPCClient/GRPCCall.m]: This why @property defaults to atomic - 
@property GRXWriter *requestWriter;

...

@synchronized(self.requestWriter) {...}

I'm under the impression that the compiler essentially generates:
- (GRXWriter *)requestWriter {
  @synchronized(self) {
    return [[_requestWriter retain] autorelease];
  }
}

- (void)setRequestWriter:(GRXWriter *)requestWriter {
  @synchronized(self) {
    if (_requestWriter != requestWriter) {
      [_requestWriter autorelease];
      _requestWriter = [requestWriter retain];
    }
  }
}

so that other threads can't look at a partially deallocated object if the setter would otherwise cause the old value to be deallocated.

File: src/objective-c/GRPCClient/GRPCCall.m (hunk 2 above)
Comment (jcanizales) [inline src/objective-c/GRPCClient/GRPCCall.m]: > Maybe set the default to 1 minute, with a header comment documenting that the client programmer may need to change this.

TVL is strongly against us documenting the very possibility of setting a timeout :) His experience is people tend to set timeouts like 30s that work fine in a Sillicon Valley office, but are unrealistically low for developing countries.

I think the best option is indeed to document clearly that calls in-flight retain themselves, and that if it becomes too hard on memory for someone's use case, they can keep a reference to the call object and cancel it when they receive a memory warning.

File: src/objective-c/GRPCClient/GRPCCall.m (hunk 3 above)
Comment (jcanizales) [inline src/objective-c/GRPCClient/GRPCCall.m]: > This why **@property** defaults to atomic -

Aaaaah! right!

**Comment by jcanizales** [comment]
I think all issues are addressed now.

File: src/objective-c/RxLibrary/GRXForwardingWriter.m [hunk 7]
```diff
@@ -48,7 +48,11 @@ - (instancetype)init {
 // Designated initializer
 - (instancetype)initWithWriter:(GRXWriter *)writer {
   if (!writer) {
-    [NSException raise:NSInvalidArgumentException format:@"writer can't be nil."];
+    return nil;
+  }
+  if (writer.state != GRXWriterStateNotStarted) {
```
Comment (DavidPhillipOster) [inline src/objective-c/RxLibrary/GRXForwardingWriter.m]: For thread safety.  do you need to @synchronize access to writer.state ?

**Comment by DavidPhillipOster** [comment]
LGTM - Looks good to me.
