### PR TITLE
Fix server side call finalization when connection is closed.

### LINKED ISSUE #1487: C# Grpc.Core.Tests seems very flaky
I suspect it's hitting up against our five minute test limit.

Suggest breaking the test into smaller binaries.

### PR DESCRIPTION
**Pull request by jtattermusch**
Fixes #1487

### CODE REVIEW

**Comment by ctiller** [comment]
Green

File: src/core/transport/chttp2_transport.c [hunk 1]
```diff
@@ -823,24 +823,26 @@ static void unlock(transport *t) {
...
-    }
-    if (t->num_pending_goaways) {
-      goaways = t->pending_goaways;
-      num_goaways = t->num_pending_goaways;
-      t->pending_goaways = NULL;
-      t->num_pending_goaways = 0;
-      t->cap_pending_goaways = 0;
-      t->calling_back = 1;
+    if (cb) {
+      if (t->error_state == ERROR_STATE_SEEN && !t->writing && !t->calling_back) {
```
Comment (nicolasnoble) [inline src/core/transport/chttp2_transport.c]: Collapse the two ifs into one maybe ? Also, use perform_callbacks instead of t->calling_back, that'll avoid one pointer dereference, and that value is going to be the same.

Comment (ctiller) [inline src/core/transport/chttp2_transport.c]: Ah my bad. I made this change at Jan's machine. The extra t->calling_back check here is spurious. The right thing to do is remove it again.

Comment (nicolasnoble) [inline src/core/transport/chttp2_transport.c]: I was kind of wondering that, yes :-)

Comment (ctiller) [inline src/core/transport/chttp2_transport.c]: Want to merge and fix Travis anyway... This will only add some latency
disconnecting. I'll fix it up better this morning.

**Comment by nicolasnoble** [comment]
Fair enough.

File: src/core/transport/chttp2_transport.c [hunk 2]
```diff
@@ -823,24 +823,26 @@ static void unlock(transport *t) {
   finish_reads(t);
 
   /* gather any callbacks that need to be made */
-  if (!t->calling_back && cb) {
+  if (!t->calling_back) {
     perform_callbacks = prepare_callbacks(t);
     if (perform_callbacks) {
```
Comment (nicolasnoble) [inline src/core/transport/chttp2_transport.c]: Also, while I'm here, unless prepare_callbacks can change the value of t->calling_back, that `if` here is superfluous, but can't be compiler-optimized.

Comment (nicolasnoble) [inline src/core/transport/chttp2_transport.c]: As in, you could simply do t->calling_back = perform_callbacks here.
