### PR TITLE
Revert "Set error status correctly on server side"

### LINKED ISSUE #13953: bins/dbg/h2_ssl_proxy_test filter_status_code GRPC_POLL_STRATEGY=epollsig
```
Failure
D0105 00:40:36.153056962   28005 test_config.cc:388]         test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
I0105 00:40:36.153402314   28005 ev_epollsig_linux.cc:76]    epoll engine will be using signal: 40
D0105 00:40:36.153415087   28005 ev_posix.cc:128]            Using polling engine: epollsig
D0105 00:40:36.153440119   28005 dns_resolver.cc:294]        Using native dns resolver
I0105 00:40:36.153489333   28005 filter_status_code.cc:52]   Running test: filter_status_code/chttp2/simple_ssl_fullstack
D0105 00:40:36.155766478   28005 proxy.cc:89]                PROXY ADDR:localhost:10274 BACKEND:localhost:30074
E0105 00:40:36.177003131   28005 filter_status_code.cc:229]  assertion failed: g_client_status_code == GRPC_STATUS_UNIMPLEMENTED

*******************************
Caught signal SIGABRT
```
https://sponge.corp.google.com/target?id=a81f69d4-57ce-465c-85ab-c6b888d3b885&target=github/grpc/c_linux_dbg_native&searchFor=&show=ALL&sortBy=STATUS

### PR DESCRIPTION
**Pull request by dgquintas**
Reverts grpc/grpc#13794

Fixes #13953

Commit 6535cfd14001a433f1af5da8476b9b1247fce689 in this change makes `filter_status_code` tests very flaky. It seems this test was newly introduced. In that case, it needs more work.

Way to reproduce: `$ ./tools/run_tests/run_tests.py -l c -c asan -n 200 -r filter_status_code`.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                    FILE SIZE
 ++++++++++++++ GROWING                      ++++++++++++++
  +0.3%     +48 src/core/lib/surface/call.cc     +48  +0.3%
      +1.7%     +56 call_start_batch                 +56  +1.7%

  +0.0%     +48 TOTAL                            +48  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

File: src/core/lib/surface/call.cc [hunk 1]
```diff
@@ -1851,9 +1851,8 @@ static grpc_call_error call_start_batch(grpc_call* call, const grpc_op* ops,
         {
           grpc_error* override_error = GRPC_ERROR_NONE;
           if (op->data.send_status_from_server.status != GRPC_STATUS_OK) {
-            override_error =
```
Comment (kpayson64) [inline src/core/lib/surface/call.cc]: Can we keep this part?  It looks like just the test is flaking, and this change hasn't caused any other tests to fail.

**Comment by dgquintas** [comment]
Example flakiness report for `-c opt -n 100 -a 10`:
```
FLAKE: bins/opt/h2_census_nosec_test filter_status_code GRPC_POLL_STRATEGY=epoll1 [5/100 runs flaked]
FLAKE: bins/opt/h2_census_nosec_test filter_status_code GRPC_POLL_STRATEGY=epollsig [12/100 runs flaked]
FLAKE: bins/opt/h2_census_nosec_test filter_status_code GRPC_POLL_STRATEGY=poll [2/100 runs flaked]
FLAKE: bins/opt/h2_census_nosec_test filter_status_code GRPC_POLL_STRATEGY=poll-cv [2/100 runs flaked]
FLAKE: bins/opt/h2_census_test filter_status_code GRPC_POLL_STRATEGY=epoll1 [14/100 runs flaked]
FLAKE: bins/opt/h2_census_test filter_status_code GRPC_POLL_STRATEGY=epollsig [14/100 runs flaked]
FLAKE: bins/opt/h2_compress_nosec_test filter_status_code GRPC_POLL_STRATEGY=epoll1 [12/100 runs flaked]
FLAKE: bins/opt/h2_compress_nosec_test filter_status_code GRPC_POLL_STRATEGY=epollsig [14/100 runs flaked]
FLAKE: bins/opt/h2_compress_test filter_status_code GRPC_POLL_STRATEGY=epoll1 [7/100 runs flaked]
FLAKE: bins/opt/h2_compress_test filter_status_code GRPC_POLL_STRATEGY=epollsig [4/100 runs flaked]
FLAKE: bins/opt/h2_compress_test filter_status_code GRPC_POLL_STRATEGY=poll [1/100 runs flaked]
FLAKE: bins/opt/h2_compress_test filter_status_code GRPC_POLL_STRATEGY=poll-cv [1/100 runs flaked]
FLAKE: bins/opt/h2_fakesec_test filter_status_code GRPC_POLL_STRATEGY=epoll1 [24/100 runs flaked]
FLAKE: bins/opt/h2_fakesec_test filter_status_code GRPC_POLL_STRATEGY=epollsig [18/100 runs flaked]
FLAKE: bins/opt/h2_full+pipe_nosec_test filter_status_code GRPC_POLL_STRATEGY=epoll1 [16/100 runs flaked]
FLAKE: bins/opt/h2_full+pipe_nosec_test filter_status_code GRPC_POLL_STRATEGY=epollsig [8/100 runs flaked]
FLAKE: bins/opt/h2_full+pipe_nosec_test filter_status_code GRPC_POLL_STRATEGY=poll [2/100 runs flaked]
FLAKE: bins/opt/h2_full+pipe_test filter_status_code GRPC_POLL_STRATEGY=epoll1 [17/100 runs flaked]
FLAKE: bins/opt/h2_full+pipe_test filter_status_code GRPC_POLL_STRATEGY=epollsig [10/100 runs flaked]
FLAKE: bins/opt/h2_full+pipe_test filter_status_code GRPC_POLL_STRATEGY=poll [1/100 runs flaked]
FLAKE: bins/opt/h2_full+trace_nosec_test filter_status_code GRPC_POLL_STRATEGY=epoll1 [8/100 runs flaked]
FLAKE: bins/opt/h2_full+trace_nosec_test filter_status_code GRPC_POLL_STRATEGY=epollsig [6/100 runs flaked]
FLAKE: bins/opt/h2_full+trace_nosec_test filter_status_code GRPC_POLL_STRATEGY=poll [3/100 runs flaked]
FLAKE: bins/opt/h2_full+trace_test filter_status_code GRPC_POLL_STRATEGY=epoll1 [10/100 runs flaked]
FLAKE: bins/opt/h2_full+trace_test filter_status_code GRPC_POLL_STRATEGY=epollsig [1/100 runs flaked]
FLAKE: bins/opt/h2_full+trace_test filter_status_code GRPC_POLL_STRATEGY=poll [4/100 runs flaked]
FLAKE: bins/opt/h2_full+workarounds_nosec_test filter_status_code GRPC_POLL_STRATEGY=epoll1 [14/100 runs flaked]
FLAKE: bins/opt/h2_full+workarounds_nosec_test filter_status_code GRPC_POLL_STRATEGY=epollsig [20/100 runs flaked]
FLAKE: bins/opt/h2_full+workarounds_nosec_test filter_status_code GRPC_POLL_STRATEGY=poll [2/100 runs flaked]
FLAKE: bins/opt/h2_full+workarounds_test filter_status_code GRPC_POLL_STRATEGY=epoll1 [15/100 runs flaked]
FLAKE: bins/opt/h2_full+workarounds_test filter_status_code GRPC_POLL_STRATEGY=epollsig [10/100 runs flaked]
FLAKE: bins/opt/h2_full_nosec_test filter_status_code GRPC_POLL_STRATEGY=epoll1 [11/100 runs flaked]
FLAKE: bins/opt/h2_full_nosec_test filter_status_code GRPC_POLL_STRATEGY=epollsig [16/100 runs flaked]
FLAKE: bins/opt/h2_full_nosec_test filter_status_code GRPC_POLL_STRATEGY=poll [1/100 runs flaked]
FLAKE: bins/opt/h2_full_nosec_test filter_status_code GRPC_POLL_STRATEGY=poll-cv [1/100 runs flaked]
FLAKE: bins/opt/h2_full_test filter_status_code GRPC_POLL_STRATEGY=epoll1 [13/100 runs flaked]
FLAKE: bins/opt/h2_full_test filter_status_code GRPC_POLL_STRATEGY=epollsig [12/100 runs flaked]
FLAKE: bins/opt/h2_full_test filter_status_code GRPC_POLL_STRATEGY=poll [1/100 runs flaked]
FLAKE: bins/opt/h2_load_reporting_nosec_test filter_status_code GRPC_POLL_STRATEGY=epoll1 [5/100 runs flaked]
FLAKE: bins/opt/h2_load_reporting_nosec_test filter_status_code GRPC_POLL_STRATEGY=epollsig [10/100 runs flaked]
FLAKE: bins/opt/h2_load_reporting_nosec_test filter_status_code GRPC_POLL_STRATEGY=poll [1/100 runs flaked]
FLAKE: bins/opt/h2_load_reporting_test filter_status_code GRPC_POLL_STRATEGY=epoll1 [11/100 runs flaked]
FLAKE: bins/opt/h2_load_reporting_test filter_status_code GRPC_POLL_STRATEGY=epollsig [10/100 runs flaked]
FLAKE: bins/opt/h2_oauth2_test filter_status_code GRPC_POLL_STRATEGY=epoll1 [9/100 runs flaked]
FLAKE: bins/opt/h2_oauth2_test filter_status_code GRPC_POLL_STRATEGY=epollsig [6/100 runs flaked]
FLAKE: bins/opt/h2_proxy_nosec_test filter_status_code GRPC_POLL_STRATEGY=epoll1 [72/100 runs flaked]
FLAKE: bins/opt/h2_proxy_nosec_test filter_status_code GRPC_POLL_STRATEGY=epollsig [62/100 runs flaked]
FLAKE: bins/opt/h2_proxy_nosec_test filter_status_code GRPC_POLL_STRATEGY=poll [84/100 runs flaked]
FLAKE: bins/opt/h2_proxy_nosec_test filter_status_code GRPC_POLL_STRATEGY=poll-cv [26/100 runs flaked]
FLAKE: bins/opt/h2_proxy_test filter_status_code GRPC_POLL_STRATEGY=epoll1 [76/100 runs flaked]
FLAKE: bins/opt/h2_proxy_test filter_status_code GRPC_POLL_STRATEGY=epollsig [69/100 runs flaked]
FLAKE: bins/opt/h2_proxy_test filter_status_code GRPC_POLL_STRATEGY=poll [74/100 runs flaked]
FLAKE: bins/opt/h2_proxy_test filter_status_code GRPC_POLL_STRATEGY=poll-cv [24/100 runs flaked]
FLAKE: bins/opt/h2_ssl_proxy_test filter_status_code GRPC_POLL_STRATEGY=epoll1 [50/100 runs flaked]
FLAKE: bins/opt/h2_ssl_proxy_test filter_status_code GRPC_POLL_STRATEGY=epollsig [53/100 runs flaked]
FLAKE: bins/opt/h2_ssl_proxy_test filter_status_code GRPC_POLL_STRATEGY=poll [72/100 runs flaked]
FLAKE: bins/opt/h2_ssl_proxy_test filter_status_code GRPC_POLL_STRATEGY=poll-cv [26/100 runs flaked]
FLAKE: bins/opt/h2_ssl_test filter_status_code GRPC_POLL_STRATEGY=epoll1 [8/100 runs flaked]
FLAKE: bins/opt/h2_ssl_test filter_status_code GRPC_POLL_STRATEGY=epollsig [5/100 runs flaked]
FLAKE: bins/opt/h2_ssl_test filter_status_code GRPC_POLL_STRATEGY=poll [1/100 runs flaked]
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

File: src/core/lib/surface/call.cc (hunk 1 above)
Comment (dgquintas) [reply src/core/lib/surface/call.cc]: Sure. I wonder how to do that on a revert PR... would it be too much trouble to have this revert go in as-is and then introduce this change? Otherwise this PR wouldn't really be a revert and things would be confusing.

Comment (kpayson64) [reply src/core/lib/surface/call.cc]: That's fine

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by dgquintas** [comment]
Issues: #13999 #13477
