### PR TITLE
Change pick_first to immediately select the first subchannel in READY state.

### LINKED ISSUE #17282: Undesired reconnection backoff triggered due to subchannel connection failures
### What version of gRPC and what language are you using?
grpc-node v1.16.1 
 
### What operating system (Linux, Windows, …) and version?
 Linux + macOS
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 node v8.9.4
 
### What did you do?
Runnable repro: https://github.com/ryanpbrewster/grpc-node-example
 
### What did you expect to see?
 Creating a new connection should happen quickly
 
### What did you see instead?
Exponential backoff kicked in despite the server being reachable from the client. The client is connecting with two subchannels, one for ipv4 and one for ipv6:
```
I1121 16:08:27.915904109  230990 subchannel_list.h:535]      [pick_first 0x3281720] subchannel list 0x3281b40 index 0: Created subchannel 0x3282630 for address uri ipv6:[::1]:50051
I1121 16:08:27.915924766  230990 subchannel_list.h:535]      [pick_first 0x3281720] subchannel list 0x3281b40 index 1: Created subchannel 0x32830e0 for address uri ipv4:127.0.0.1:50051
```

I believe the ipv6 subchannel is failing to connect and the ipv4 subchannel is succeeding. From both the client and server perspectives, the connection looks successful and the requests are being processed. However, when trying to open subsequent connections, we're running into exponential backoff:

```
{ raw: 'FOO BAR BAZ #0' }
0: 11.216ms
{ raw: 'FOO BAR BAZ #1' }
1: 998.730ms
{ raw: 'FOO BAR BAZ #2' }
2: 1328.682ms
{ raw: 'FOO BAR BAZ #3' }
3: 2734.221ms
{ raw: 'FOO BAR BAZ #4' }
4: 3765.556ms
```

If I change the server to accept ipv6 traffic, or change the client to try to connect to an explicit ipv4 address, this backoff behavior is _not_ triggered:
```
{ raw: 'FOO BAR BAZ #0' }
0: 11.141ms
{ raw: 'FOO BAR BAZ #1' }
1: 1.473ms
{ raw: 'FOO BAR BAZ #2' }
2: 1.094ms
{ raw: 'FOO BAR BAZ #3' }
3: 1.185ms
{ raw: 'FOO BAR BAZ #4' }
4: 1.150ms
{ raw: 'FOO BAR BAZ #5' }
5: 0.932ms
{ raw: 'FOO BAR BAZ #6' }
6: 1.117ms
{ raw: 'FOO BAR BAZ #7' }
7: 0.918ms
{ raw: 'FOO BAR BAZ #8' }
8: 0.917ms
{ raw: 'FOO BAR BAZ #9' }
9: 0.927ms
```

### PR DESCRIPTION
**Pull request by markdroth**
Fixes #17282.

Note that this replaces the current special case of selecting the currently selected subchannel if it is present in the update, which we were only doing if the subchannel was READY.  What we really care about here is whether the subchannel is READY, not whether it was the previously selected subchannel (or even if there was a previously selected subchannel).  This means that we will do the right thing when (e.g.) the LB policy first starts up and finds a subchannel already in READY state due to being in use by a different channel.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                              FILE SIZE
 ++++++++++++++ GROWING                                                                ++++++++++++++

 -------------- SHRINKING                                                              --------------
  -0.6%     -80 src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc     -80  -0.6%
      -2.3%     -75 grpc_core::(anonymous namespace)::PickFirst::UpdateLocked                  -75  -2.3%
      -1.9%      -5 [Unmapped]                                                                  -5  -1.9%

 -+-+-+-+-+-+-+ MIXED                                                                  +-+-+-+-+-+-+-
  -0.0%    -128 [None]                                                                    +488  +0.0%

  -0.0%    -208 TOTAL                                                                     +408  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,020,263      Total (<)      2,020,410

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,174,081      Total (>)     11,174,077

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                              FILE SIZE
 ++++++++++++++ GROWING                                                                ++++++++++++++

 -------------- SHRINKING                                                              --------------
  -0.6%     -80 src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc     -80  -0.6%
      -2.3%     -75 grpc_core::(anonymous namespace)::PickFirst::UpdateLocked                  -75  -2.3%
      -1.9%      -5 [Unmapped]                                                                  -5  -1.9%

 -+-+-+-+-+-+-+ MIXED                                                                  +-+-+-+-+-+-+-
  -0.0%    -128 [None]                                                                    +488  +0.0%

  -0.0%    -208 TOTAL                                                                     +408  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,020,263      Total (<)      2,020,410

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,174,076      Total (<)     11,174,077

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

File: src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc [hunk 1]
```diff
@@ -391,42 +416,8 @@ void PickFirst::UpdateLocked(const grpc_channel_args& args,
           ->CheckConnectivityStateAndStartWatchingLocked();
```
Comment (AspirinSJL) [inline src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc]: Now that we are checking the subchannels' state above, we can just call `StartConnectivityWatchLocked()` here.

Comment (markdroth) [reply src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc]: Good catch.  Done.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                              FILE SIZE
 ++++++++++++++ GROWING                                                                ++++++++++++++

 -------------- SHRINKING                                                              --------------
  -0.7%     -96 src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc     -96  -0.7%
      -2.9%     -94 grpc_core::(anonymous namespace)::PickFirst::UpdateLocked                  -94  -2.9%
      -0.8%      -2 [Unmapped]                                                                  -2  -0.8%

 -+-+-+-+-+-+-+ MIXED                                                                  +-+-+-+-+-+-+-
  -0.0%    -112 [None]                                                                    +504  +0.0%

  -0.0%    -208 TOTAL                                                                     +408  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,019,588      Total (<)      2,019,735

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,154,120      Total (>)     11,154,111

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Comment by markdroth** [comment]
Known issues: #17375

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,019,604      Total (<)      2,019,751

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,154,114      Total (<)     11,154,117

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```
