### PR TITLE
Fix Go perftests and a few other fixes.

### LINKED ISSUE #6533: netperf_tcp_rr  scenario does not contain Jenkins job details
(because the details are extracted from environment variables set by jenkins, but the netperf client runs on a different machine, so those variables are not available).

Workaround: make sure those variables are set when sshing to the client to run netperf test.

### PR DESCRIPTION
**Pull request by jtattermusch**
-- GOPATH needs to be set for Go worker to correctly detect test certificates
-- run go as part of smoketest
-- run netperf as part of smoketest
-- fix #6533

### CODE REVIEW

**Comment by jtattermusch** [comment]
@menghanl  CC (feel free to review)

**Comment by vjpai** [comment]
LGTM.

File: tools/jenkins/run_performance.sh [hunk 1]
```diff
@@ -34,4 +34,4 @@ set -ex
 # Enter the gRPC repo root
 cd $(dirname $0)/../..
 
-tools/run_tests/run_performance_tests.py -l c++ node ruby csharp python
+tools/run_tests/run_performance_tests.py -l c++ node ruby csharp python --netperf --category smoketest
```
Comment (jtattermusch) [inline tools/jenkins/run_performance.sh]: Actually, I cannot run go as part of smoketest yet (because that would require setting up a multi-repo project). Removing go for now.

**Comment by jtattermusch** [comment]
Basic tests were green before three-character change in 7d5111e. Merging.
