### PR TITLE
Fix Spammy Log on Empty GRPC_TRACE Var

### LINKED ISSUE #14984: Empty GRPC_TRACE variable prints error in log
### What version of gRPC and what language are you using?
1.10.1 C#
  
### What operating system (Linux, Windows, …) and version?
Ubuntu 16.04
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 .NET Core 2.0.6
 
### What did you do?
Start app with `GRPC_TRACE=` environment variable (value is empty string).
 
### What did you expect to see?
Nothing special. 
 
### What did you see instead?
`139929731512128 src/core/lib/debug/trace.cc:57: Unknown trace var: ''`

I am assuming gRPC does not like the empty string as value. I would expect it not to complain about this.

### PR DESCRIPTION
**Pull request by ncteisen**
Fixes #14984

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                         FILE SIZE
 ++++++++++++++ GROWING                           ++++++++++++++
  +1.6%     +16 src/core/lib/debug/trace.cc           +16  +1.6%
      +5.1%     +16 grpc_core::TraceFlagList::Set         +16  +5.1%

 -+-+-+-+-+-+-+ MIXED                             +-+-+-+-+-+-+-
  +0.0%     +16 [None]                                -16  -0.0%

  +0.0%     +32 TOTAL                                   0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

File: src/core/lib/debug/trace.cc [hunk 1]
```diff
@@ -55,7 +55,7 @@ bool TraceFlagList::Set(const char* name, bool enabled) {
         found = true;
       }
     }
-    if (!found) {
+    if (!found && strcmp(name, "")) {
```
Comment (hcaseyal) [inline src/core/lib/debug/trace.cc]: The strcmp uses in this function could be decomposed into a separate function with clear naming so that the code is easier to read

Comment (ncteisen) [reply src/core/lib/debug/trace.cc]: Can you elaborate here? c std lib calls are quite common, and pretty readable IMO.

Are you suggesting something like:

```
bool is_empty_string(const char* s) { return  !strcmp(s, ""); }
```

I am not inclined to wrap c lib calls unless there is extra functionality needed

Comment (ncteisen) [reply src/core/lib/debug/trace.cc]: Also, I found the style guideline where I was taught to not wrap library calls without changing functionality: http://umich.edu/~eecs381/handouts/C_Coding_Standards.pdf

This is from a C class I took in college :)

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by ncteisen** [comment]
Interop failures: #10763 
Bazel: #14692
