### PR TITLE
[iomgr][Windows] Return proper error code to client when connection is reset

### LINKED ISSUE #24206: GRPC-Core Client inconsistency between Windows/Unix when server shuts down during a request
### What version of gRPC and what language are you using?
Python client/server using gRPC core 1.32.0 and 1.31.0
C++ client/server using gRPC core 1.31.0
Go client/server using gRPC core 1.31.0

### What operating system (Linux, Windows,...) and version?
Verified with Windows 10 Home, WSL Ubuntu

### What runtime / compiler are you using (e.g. python version or version of gcc)
Windows: Python 3.7.1, go1.13, Visual Studio 2019 - Microsoft (R) C/C++ Optimizing Compiler Version 19.27.29111 for x86

Ubuntu 18.04.4 LTS (WSL version 1): python 3.6.9, go1.14.5 linux/amd64, gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

Using the helloworld example repository:
1) Add an os.Exit or time.Sleep (with a manual keyboard interrupt) to the rpc handler for the greeter server (for example, here: https://github.com/grpc/grpc-go/blob/master/examples/helloworld/greeter_server/main.go#L36 and https://github.com/grpc/grpc/blob/master/examples/python/helloworld/greeter_server.py#L28 )
2) Start the server.
3) Start the client.
4) Shut down the server with a keyboard interrupt (or it will shut down via os.Exit)

### What did you expect to see?
Consistent error between Windows and Unix: Error Code 14 Unavailable with message "Socket closed"

### What did you see instead?
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
Error Code 2 with message "Stream removed" on Windows.
From the Windows python greeter_client:
```
C:\Users\Hamza\testgrpc\grpc\examples\python\helloworld>python greeter_client.py
Traceback (most recent call last):
  File "greeter_client.py", line 37, in <module>
    run()
  File "greeter_client.py", line 31, in run
    response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
  File "E:\Hamza\AppData\Local\Programs\Python\Python37\lib\site-packages\grpc\_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "E:\Hamza\AppData\Local\Programs\Python\Python37\lib\site-packages\grpc\_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Stream removed"
        debug_error_string = "{"created":"@1600748422.156000000","description":"Error received from peer ipv6:[::1]:50051","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Stream removed","grpc_status":2}"
>
```
From the Ubuntu python greeter_client:
```
qureshi@DESKTOP-DHAG5GE:~/grpc/examples/python/helloworld$ python3 greeter_client.py
Traceback (most recent call last):
  File "greeter_client.py", line 37, in <module>
    run()
  File "greeter_client.py", line 31, in run
    response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
  File "/home/qureshi/.local/lib/python3.6/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/qureshi/.local/lib/python3.6/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Socket closed"
        debug_error_string = "{"created":"@1600747516.913030200","description":"Error received from peer ipv6:[::1]:50052","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
>
```
I believe this is a client problem since the errors and differences are the same irrespective of whether the server was from the python, c++, or go examples. The grpc-go client also does not experience the same behavior; it has a consistent code 14 "transport is closing" error between OSes.

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
I tried this on Windows Server 2019 and macOS Mojave 10.14.6 with the same respective Windows/Unix inconsistency between the two. It also occurs between remote machines as long as it is a windows client.

### PR DESCRIPTION
**Pull request by drfloob**
Fixes #24206 by ensuring that IOCP/socket errors in the iomgr on_read callback are properly annotated with the gRPC Unavailable status. The WindowsEventEngine was already doing this correctly (try running the client with `$env:GRPC_EXPERIMENTS="event_engine_client"`).

This also adds two small cleanups:
 * Cleanly prints statuses with their child statuses in a few spots within the chttp2 transport logging (previously, child messages were printed with garbled bits)
 * Adds friendly names to a subset of WSA errors that we're likely to see from common operations. The top-level status message will no longer just say "WSA Error" in many cases.

CC @Hamza-Q

### CODE REVIEW

File: src/core/lib/iomgr/error.cc [hunk 1]
```diff
@@ -70,12 +70,42 @@ absl::Status grpc_os_error(const grpc_core::DebugLocation& location, int err,
 }
 
 #ifdef GPR_WINDOWS
+std::string WSAErrorToShortDescription(int err) {
```
Comment (markdroth) [inline src/core/lib/iomgr/error.cc:73]: Does Windows not provide a function that does this already?  I would have expected that it would.  Posix has had `strerror()` for a long time.

**Review by markdroth — APPROVED** [review]
Thanks for fixing this!

File: src/core/lib/iomgr/error.cc (hunk 1 above)
Comment (ctiller) [reply src/core/lib/iomgr/error.cc:73]: https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-formatmessage

File: src/core/ext/transport/chttp2/transport/chttp2_transport.cc [hunk 2]
```diff
@@ -1605,8 +1605,8 @@ static void perform_stream_op(grpc_transport* gt, grpc_stream* gs,
 }
 
 static void cancel_pings(grpc_chttp2_transport* t, grpc_error_handle error) {
-  GRPC_CHTTP2_IF_TRACING(
-      gpr_log(GPR_INFO, "%p CANCEL PINGS: %s", t, error.ToString().c_str()));
+  GRPC_CHTTP2_IF_TRACING(gpr_log(GPR_INFO, "%p CANCEL PINGS: %s", t,
+                                 grpc_core::StatusToString(error).c_str()));
```
Comment (ctiller) [inline src/core/ext/transport/chttp2/transport/chttp2_transport.cc:1609]: For my education: why is ToString not the right thing?

File: src/core/lib/iomgr/error.cc (hunk 1 above)
Comment (drfloob) [reply src/core/lib/iomgr/error.cc:73]: We use `FormatMessage` in `gpr_format_message`, but it produces longer messages. For example, for the `WSAECONNRESET` error, FormatMessage produces "An existing connection was forcibly closed by the remote host", but for a top-level Status summary (which becomes the error strings that clients receive), something like "Connection reset" will do for a summary. The summary seems friendlier.

Here is an example error:

```
I0620 18:33:23.213000000 15608 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:1609] 000001946F442850 CANCEL PINGS: UNKNOWN:Delayed close due to in-progress write {created_time:"2023-06-21T01:33:23.211759741+00:00", file_line:662, file:"src/core/ext/transport/chttp2/transport/chttp2_transport.cc", children:[UNKNOWN:Endpoint read failed {file:"src/core/ext/transport/chttp2/transport/chttp2_transport.cc", file_line:2534, created_time:"2023-06-21T01:33:23.210383893+00:00", occurred_during_write:0, children:[UNAVAILABLE:Connection Reset {file:"src/core/lib/iomgr/tcp_windows.cc", file_line:189, created_time:"2023-06-21T01:33:23.2102455+00:00", wsa_error:10054, grpc_status:14, os_error:"An existing connection was forcibly closed by the remote host.\r\n", syscall:"IOCP/Socket"}]}, UNAVAILABLE:Connection Reset {file:"src/core/lib/iomgr/tcp_windows.cc", file_line:425, created_time:"2023-06-21T01:33:23.212417741+00:00", wsa_error:10054, grpc_status:14, os_error:"An existing connection was forcibly closed by the remote host.\r\n", syscall:"WSASend"}]}    
```

This propagates to the surface as an error with status `GRPC_STATUS_UNAVAILABLE` and message "Connection Reset".

File: src/core/ext/transport/chttp2/transport/chttp2_transport.cc (hunk 2 above)
Comment (drfloob) [reply src/core/ext/transport/chttp2/transport/chttp2_transport.cc:1609]: On Windows at least, the child errors are printed with embedded hex when you use status.ToString(). Try to pick out the file line number for the child error in this example: 

```
D0620 15:33:35.497000000 19492 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:2198] MARK_STREAM_CLOSED: t=000001C9618D5830 s=000001C9618DB710(id=1) read+write [UNKNOWN: Endpoint read failed [type.googleapis.com/grpc.status.str.file='src/core/ext/transport/chttp2/transport/chttp2_transport.cc'] [type.googleapis.com/grpc.status.int.file_line='2534'] [type.googleapis.com/grpc.status.time.created_time='2023-06-20T22:33:35.497401355+00:00'] [type.googleapis.com/grpc.status.children='\'\x01\x00\x00\x08\x02\x12\x44\x41n existing connection was forcibly closed by the remote host.%0D%0A\x1aX\n1type.googleapis.com/grpc.status.time.created_time\x12#2023-06-20T22:33:35.497371459+00:00\x1a\x34\n-type.googleapis.com/grpc.status.int.file_line\x12\x03\x31\x39\x30\x1aM\n(type.googleapis.com/grpc.status.str.file\x12!src/core/lib/iomgr/tcp_windows.cc'] [type.googleapis.com/grpc.status.int.occurred_during_write='0']]
```
