### PR TITLE
Change C implementation to not log an "Unexpected content-type" message when the header includes a semicolon.

### LINKED ISSUE #3136: When checking content-type, ignore anything following semicolon
Content types in the spec are in the form application/grpc+encoding. Most implementations are likely just ignoring anything after the '+', but we should also ignore things after a semicolon since mime-types can include additional parameters (e.g., "text/plain; charset=us-ascii").

The Java issue for this is grpc/grpc-java#360.

### PR DESCRIPTION
**Pull request by markdroth**
Fixes #3136.

It looks to me like the pre-existing code would already accept the semicolon, although it would log an an "Unexpected content-type" message. The only real impact of this PR is to avoid logging that message. As such, I'm not sure if the testing changes are really sufficient -- the test I've changed here passes both with and without the code change, because the test doesn't check whether the code logs the offending message.

This is my first change in the gRPC code, so any and all feedback would be welcome.

### CODE REVIEW

File: src/core/lib/channel/http_server_filter.c [hunk 1]
```diff
@@ -92,8 +92,10 @@ static grpc_mdelem *server_filter(void *user_data, grpc_mdelem *md) {
        require */
     return NULL;
   } else if (md->key == GRPC_MDSTR_CONTENT_TYPE) {
-    if (strncmp(grpc_mdstr_as_c_string(md->value), "application/grpc+", 17) ==
-        0) {
+    const char* value_str = grpc_mdstr_as_c_string(md->value);
+    if (strncmp(value_str, "application/grpc", 16) == 0 &&
```
Comment (ctiller) [inline src/core/lib/channel/http_server_filter.c]: It might be time to do something about that 16...

```
#define EXPECTED_CONTENT_TYPE "application/grpc"
#define EXPECTED_CONTENT_TYPE_LENGTH sizeof(EXPECTED_CONTENT_TYPE)-1
```

**Comment by ctiller** [comment]
Tiny cleanup while we're here... but this looks really good.

File: src/core/lib/channel/http_server_filter.c (hunk 1 above)
Comment (markdroth) [inline src/core/lib/channel/http_server_filter.c]: Done.

File: src/core/lib/channel/http_server_filter.c [hunk 2]
```diff
@@ -92,8 +92,10 @@ static grpc_mdelem *server_filter(void *user_data, grpc_mdelem *md) {
...
+        (strlen(value_str) == 16 ||
```
Comment (markdroth) [inline src/core/lib/channel/http_server_filter.c]: I realized last night that the strlen() call isn't necessary here, for two reasons.  First, if there is nothing after the "/grpc" part, then we won't get here in the first place, because that case will be caught as GRPC_MDELEM_CONTENT_TYPE_APPLICATION_SLASH_GRPC on line 78 above.  And second, if strncmp() returns 0, then even if the string ends after the "/grpc" part, there will at least be a nul byte there, so we won't run off the end of the string anyway.

Please double-check my logic here, though.  I don't want to introduce a buffer overflow vulnerability on my first PR. :)

**Comment by markdroth** [comment]
I've fixed the clang formatting problems, but I'm not sure what's causing the other test failures.  It's not obvious to me how this change could have caused those problems.  Are they pre-existing?

**Comment by ctiller** [comment]
I think random flake. LGTM. @jtattermusch will merge (we're in a semi-freeze).
