### PR TITLE
xds_end2end_test: Only start backends when needed

### LINKED ISSUE #27892: FLAKE: xds_end2end_test UseOriginalDstNotSupported test
From the test history, it looks like this started flaking on 2021-10-26, and it's failed a whopping 187 times since then.  The earliest failure was:

https://source.cloud.google.com/results/invocations/8ad167c0-a191-439d-8236-225037414002/targets/%2F%2Ftest%2Fcpp%2Fend2end%2Fxds:xds_end2end_test@poller%3Depoll1/tests

```
test/cpp/end2end/xds/xds_end2end_test.cc:1313: Failure
Value of: status.ok()
  Actual: true
Expected: false
test/cpp/end2end/xds/xds_end2end_test.cc:1315: Failure
Expected equality of these values:
  options.expected_error_code
    Which is: 14
  status.error_code()
    Which is: 0
```

### PR DESCRIPTION
**Pull request by yashykt**
Fix #27892 
Details in the issue

### CODE REVIEW

File: test/cpp/end2end/xds/xds_end2end_test.cc [hunk 1]
```diff
@@ -1318,29 +1318,21 @@ class XdsEnd2endTest : public ::testing::TestWithParam<TestType> {
   }
 
   bool WaitForNack(
-      std::function<AdsServiceImpl::ResponseState::State()> get_state,
-      StatusCode expected_status = StatusCode::UNAVAILABLE) {
```
Comment (markdroth) [inline test/cpp/end2end/xds/xds_end2end_test.cc:1322]: It seems useful to check that the client RPCs fail with the right code in this function.  If there are certain cases where the RPCs may not fail, then how about changing the code here to call `CheckRpcSendOk()` instead of `CheckRpcSendFailure()` if `expected_status` is `OK`?

Comment (yashykt) [reply test/cpp/end2end/xds/xds_end2end_test.cc:1322]: I think it's better to separate checking the RPC status from `WaitForNack` for exactly the case that I described in the issue where the test does not know what the status is going to be.

Tests that want to make sure that RPCs fail with a certain status should explicitly check for it.

Comment (markdroth) [reply test/cpp/end2end/xds/xds_end2end_test.cc:1322]: Yes, tests should explicitly check that.  And allowing them to specify what RPC response code to expect does that.  I don't see what benefit we gain by requiring them to send a separate RPC to check this when we can just check the status code of the RPCs that we're already sending.

Moreover, even if we agreed that that was the right thing to do, removing this parameter means that all existing tests that are calling `WaitForNack()`, either directly or indirectly, are no longer verifying what they were before, so this is basically breaking existing tests.  To avoid that, you would need to look at all tests that are currently calling `WaitForNack()` and change them to verify the RPC status code separately.

Stepping back, I think the real problem here is that we're starting the server before we set the new resources on the xDS server, which means that the server may see the default resources when it starts instead of the ones that we actually want to start the test with.  If you look at the `UseOriginalDstNotSupported` test, the test itself *should* cause the RPCs to be failed with UNAVAILABLE.  The fact that that's not happening is an artifact of the strange way that we set up the test framework, so I think that's the actual problem here.

I think the right way to solve this problem is to address this TODO:

https://github.com/grpc/grpc/blob/826b888e75038d00d7d13a5679613a7de66dcb95/test/cpp/end2end/xds/xds_end2end_test.cc#L671

Each test should explicitly start up the set of backends it wants to run, which means that each test should be able to avoid starting the backend until after it has set the appropriate resources on the xDS server.

File: test/cpp/end2end/xds/xds_end2end_test.cc [hunk 2]
```diff
@@ -2118,7 +2112,6 @@ TEST_P(BasicTest, BackendsRestart) {
   // yet having noticed that the backends were all down.
   CheckRpcSendFailure(CheckRpcSendFailureOptions().set_times(num_backends_));
   // Restart all backends.  RPCs should start succeeding again.
-  StartAllBackends();
```
Comment (markdroth) [inline test/cpp/end2end/xds/xds_end2end_test.cc:2121]: I think this change is incorrect.  We actually need to restart the backends here, since we stopped them above.

File: test/cpp/end2end/xds/xds_end2end_test.cc [hunk 3]
```diff
@@ -1951,7 +1945,7 @@ class XdsEnd2endTest : public ::testing::TestWithParam<TestType> {
 
 class BasicTest : public XdsEnd2endTest {
  public:
-  BasicTest() : XdsEnd2endTest(4, 1) {}
+  BasicTest() : XdsEnd2endTest(4, 1) { StartAllBackends(); }
```
Comment (markdroth) [inline test/cpp/end2end/xds/xds_end2end_test.cc:1948]: Looks like you missed one other spot where this change is needed:

https://github.com/grpc/grpc/blob/b1e6b1f8ccff2dabdaaee6cff1d6a2c14cb09cf1/test/cpp/end2end/xds/xds_end2end_test.cc#L2584

Here's an alternative that might be less invasive:

- Rename `XdsEnd2endTest` to `XdsEnd2endTestBase`.
- Create a subclass called `XdsEnd2endTest` whose ctor calls `StartAllBackends()`.
- Change `XdsEnabledServerTest` and `XdsServerSecurityTest` to inherit from `XdsEnd2endTestBase` instead of `XdsEnd2endTest`.

File: test/cpp/end2end/xds/xds_end2end_test.cc [hunk 4]
```diff
@@ -9820,10 +9873,7 @@ TEST_P(EdsTest, EdsServiceNameDefaultsToClusterName) {
 
 class TimeoutTest : public BasicTest {
  protected:
-  void SetUp() override {
-    xds_resource_does_not_exist_timeout_ms_ = 500;
-    BasicTest::SetUp();
-  }
+  TimeoutTest() { xds_resource_does_not_exist_timeout_ms_ = 500; }
```
Comment (markdroth) [inline test/cpp/end2end/xds/xds_end2end_test.cc:9876]: This isn't going to work.  The test requires that `xds_resource_does_not_exist_timeout_ms_` be set before the parent class' `SetUp()` method is called, since this value is used to create the client stub.

I see a few options here:
- Go back to using `SetUp()` and `TearDown()` instead of the ctor/dtor.
- Add a call to `ResetStub()` here after setting `xds_resource_does_not_exist_timeout_ms_`.  This is a little wasteful, since it will initialize the client channel twice.
- Add an optional parameter to the `XdsEnd2endTest` ctor to set this value, and pass it here via the initialization list.  This would have to be plumbed through `BasicTest`, which is a little invasive.

I think that for now, going back to using `SetUp()` and `TearDown()` is probably the best option.  We can probably improve this later, because in order to split this up into multiple files, we're going to have to provide a cleaner API for subclasses that does not involve reaching directly into the parent class's internals.

**Review by markdroth — COMMENTED** [review]
This approach looks a lot better!  Just a few details to work out.

Please let me know if you have any questions.  Thanks!

File: test/cpp/end2end/xds/xds_end2end_test.cc (hunk 4 above)
Comment (yashykt) [reply test/cpp/end2end/xds/xds_end2end_test.cc:9876]: I simply changed `TimeoutTest` to inherit from `XdsEnd2endTest` instead and added `xds_resource_does_not_exist_timeout_ms` as an optional parameter to the `XdsEnd2endTest` ctor which seems like the right thing to do here even considering future changes.

File: test/cpp/end2end/xds/xds_end2end_test.cc (hunk 2 above)
Comment (yashykt) [reply test/cpp/end2end/xds/xds_end2end_test.cc:2121]: You're right. I just did a blind removal of `StartAllBackends();` and hoped for the tests to catch any issues :)

File: test/cpp/end2end/xds/xds_end2end_test.cc (hunk 3 above)
Comment (yashykt) [reply test/cpp/end2end/xds/xds_end2end_test.cc:1948]: I think as you suggested each test suite should make its own decision on what backends to start. Explicitly seeing the `StartAllBackends()` method would make it easier to iteratively change ALL tests such that they only start the backends that they need.

**Review by markdroth — APPROVED** [review]
Looks great!

**Comment by yashykt** [comment]
Thanks for reviewing!
