### PR TITLE
Fix RR policy connectivity state upon subchannels shutdown (1.4.x branch)

### LINKED ISSUE #11578: No reconnect attempts with round_robin
It appears that when using the `round_robin` client-side load-balancing policy, once a "subchannel" (i.e. one of the server instances) is down, the client never attempts to reconnect again.

This is easy to reproduce even in the trivial case of a single client and server, where the client makes repeated requests through a channel configured with `round_robin` that specifies only the single server instance. When bringing the server down and back up, the client is never again able to make a request to it.

Contrast this with the default ("pick first") load balancing policy: here, the client successfully reconnects.

I have tried reducing the `grpc.min_reconnect_backoff_ms` and `grpc.initial_reconnect_backoff_ms` config values, but to no avail.

I'm using gRPC 1.4.0. (In 1.3.1, this seemed to work at least partially, with the client periodically attempting to reconnect, although I often observed it not actually succeeding due to some spurious-seeming timeout error.)

Am I correct in thinking this is a bug? Or is it intentional that no reconnect attempts are ever made?

### PR DESCRIPTION
**Pull request by dgquintas**
Fixes #11578

### CODE REVIEW

File: src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.c [hunk 1]
```diff
@@ -421,7 +425,7 @@ static grpc_connectivity_state update_lb_connectivity_status_locked(
                                 GRPC_CHANNEL_CONNECTING, GRPC_ERROR_NONE,
                                 "rr_connecting");
     return GRPC_CHANNEL_CONNECTING;
-  } else if (p->num_subchannels == 0) { /* 3) SHUTDOWN */
+  } else if (p->num_shutdown == p->num_subchannels) { /* 3) SHUTDOWN */
```
Comment (c4rlo) [inline src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.c]: Comment in line 408 should be updated to reflect this change

File: src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.c [hunk 2]
```diff
@@ -421,16 +425,15 @@ static grpc_connectivity_state update_lb_connectivity_status_locked(
...
     grpc_connectivity_state_set(exec_ctx, &p->state_tracker,
-                                GRPC_CHANNEL_SHUTDOWN, GRPC_ERROR_REF(error),
```
Comment (markdroth) [inline src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.c]: Why are we no longer reffing the error for these two calls?

Comment (dgquintas) [inline src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.c]: That was a leak. The ref is already incremented [here](https://github.com/dgquintas/grpc/blob/bc6bc090f471ac60c28a00152c637522e3bc72aa/src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.c#L471). This codepath wasn't hit prior to this PR.

Comment (markdroth) [inline src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.c]: I see.

This fixes the problem if we happen to hit the branches for cases 3 or 4, but it leaves the leak in case we hit any of the other branches.  While it is probably true that error will be GRPC_ERROR_NONE in any of the other cases, it seems safer to not depend on that assumption.

I think the right fix here is to leave the GRPC_ERROR_REF in place in these two branches, but add a GRPC_ERROR_UNREF right before we return from this function.

File: src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.c (hunk 1 above)
Comment (dgquintas) [inline src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.c]: Done

File: src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.c (hunk 2 above)
Comment (dgquintas) [inline src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.c]: Good point. Done.

**Comment by dgquintas** [comment]
Issues: #11223 
Windows failures should be fixed by recently merged #11605
