### PR TITLE
Fall calls with wait_for_ready=false on transient resolver failure.

### LINKED ISSUE #13627: wait_for_ready=false RPCs should fail when name resolution fails
After DNS cache is flushed and network has 100% packet loss rate, a gRPC call initiated at this time will hang waiting for DNS to succeed.

### PR DESCRIPTION
**Pull request by markdroth**
Fixes #13627.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                          FILE SIZE
 ++++++++++++++ GROWING                                                            ++++++++++++++
  +0.1%    +575 [None]                                                             +2.13Ki  +0.0%
   +14%    +240 src/core/ext/filters/client_channel/resolver/fake/fake_resolver.cc    +240   +14%
      [NEW]    +146 grpc_core::FakeResolverResponseGenerator::SetFailure                  +146  [NEW]
       +49%     +51 grpc_core::FakeResolver::MaybeFinishNextLocked                         +51   +49%
      [NEW]     +30 grpc_core::FakeResolverResponseGenerator::SetFailureLocked             +30  [NEW]
      +5.1%      +9 [Unmapped]                                                              +9  +5.1%
      +3.3%      +4 grpc_core::FakeResolver::FakeResolver                                   +4  +3.3%
  +0.7%    +209 src/core/ext/filters/client_channel/client_channel.cc                 +209  +0.7%
       +31%    +182 pick_after_resolver_result_done_locked                                +182   +31%
      +0.5%     +17 on_resolver_result_changed_locked                                      +17  +0.5%
      +2.5%     +10 [Unmapped]                                                             +10  +2.5%

  +0.1%   +1024 TOTAL                                                              +2.57Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

File: src/core/ext/filters/client_channel/client_channel.cc [hunk 1]
```diff
@@ -515,11 +518,16 @@ static void on_resolver_result_changed_locked(void* arg, grpc_error* error) {
...
       watch_lb_policy_locked(chand, chand->lb_policy.get(), state);
+    } else if (chand->resolver_result == nullptr) {
+      // Transient failure.
+      GRPC_CLOSURE_LIST_SCHED(&chand->waiting_for_resolver_result_closures);
     }
     if (!lb_policy_updated) {
       set_channel_connectivity_state_locked(
           chand, state, GRPC_ERROR_REF(state_error), "new_lb+resolver");
     }
+    grpc_channel_args_destroy(chand->resolver_result);
```
Comment (dgquintas) [inline src/core/ext/filters/client_channel/client_channel.cc]: nit: why move these lines but leave them further down than they need to be? Any reason we can't have them after line 524. `chand->resolver_result` doesn't seem to be referenced after that.

File: test/core/end2end/connection_refused_test.cc [hunk 2]
```diff
@@ -110,10 +115,36 @@ static void run_test(bool wait_for_ready, bool use_service_config) {
...
+      grpc_channel_args response = {1, &arg};
+      response_generator->SetResponse(&response);
+    }
+  }
+
   /* verify that all tags get completed */
   CQ_EXPECT_COMPLETION(cqv, tag(1), 1);
   cq_verify(cqv);
 
+  gpr_log(GPR_INFO, "status=%d", status);
```
Comment (dgquintas) [inline test/core/end2end/connection_refused_test.cc]: nit: status of what?

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

File: src/core/ext/filters/client_channel/client_channel.cc (hunk 1 above)
Comment (markdroth) [reply src/core/ext/filters/client_channel/client_channel.cc]: It doesn't actually need to be reset until just before we call `NextLocked()` again.  I'm effectively changing the mode here from "keep this only until we've processed it" to "keep this for the whole callback, so that we can access it at any time".

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                          FILE SIZE
 ++++++++++++++ GROWING                                                            ++++++++++++++
  +0.1%    +559 [None]                                                             +2.12Ki  +0.0%
   +14%    +240 src/core/ext/filters/client_channel/resolver/fake/fake_resolver.cc    +240   +14%
      [NEW]    +146 grpc_core::FakeResolverResponseGenerator::SetFailure                  +146  [NEW]
       +49%     +51 grpc_core::FakeResolver::MaybeFinishNextLocked                         +51   +49%
      [NEW]     +30 grpc_core::FakeResolverResponseGenerator::SetFailureLocked             +30  [NEW]
      +5.1%      +9 [Unmapped]                                                              +9  +5.1%
      +3.3%      +4 grpc_core::FakeResolver::FakeResolver                                   +4  +3.3%
  +0.7%    +225 src/core/ext/filters/client_channel/client_channel.cc                 +225  +0.7%
       +31%    +182 pick_after_resolver_result_done_locked                                +182   +31%
      +0.9%     +33 on_resolver_result_changed_locked                                      +33  +0.9%
      +2.5%     +10 [Unmapped]                                                             +10  +2.5%

  +0.1%   +1024 TOTAL                                                              +2.58Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

File: test/core/end2end/connection_refused_test.cc (hunk 2 above)
Comment (markdroth) [reply test/core/end2end/connection_refused_test.cc]: Fixed.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                          FILE SIZE
 ++++++++++++++ GROWING                                                            ++++++++++++++
  +0.1%    +559 [None]                                                             +2.12Ki  +0.0%
   +14%    +240 src/core/ext/filters/client_channel/resolver/fake/fake_resolver.cc    +240   +14%
      [NEW]    +146 grpc_core::FakeResolverResponseGenerator::SetFailure                  +146  [NEW]
       +49%     +51 grpc_core::FakeResolver::MaybeFinishNextLocked                         +51   +49%
      [NEW]     +30 grpc_core::FakeResolverResponseGenerator::SetFailureLocked             +30  [NEW]
      +5.1%      +9 [Unmapped]                                                              +9  +5.1%
      +3.3%      +4 grpc_core::FakeResolver::FakeResolver                                   +4  +3.3%
  +0.7%    +225 src/core/ext/filters/client_channel/client_channel.cc                 +225  +0.7%
       +31%    +182 pick_after_resolver_result_done_locked                                +182   +31%
      +0.9%     +33 on_resolver_result_changed_locked                                      +33  +0.9%
      +2.5%     +10 [Unmapped]                                                             +10  +2.5%

  +0.1%   +1024 TOTAL                                                              +2.58Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by markdroth** [comment]
I think the remaining failures are unrelated to this PR.  David, do you want to look one more time before I squash commits?

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                          FILE SIZE
 ++++++++++++++ GROWING                                                            ++++++++++++++
  +0.1%    +559 [None]                                                             +2.14Ki  +0.0%
   +14%    +240 src/core/ext/filters/client_channel/resolver/fake/fake_resolver.cc    +240   +14%
      [NEW]    +146 grpc_core::FakeResolverResponseGenerator::SetFailure                  +146  [NEW]
       +49%     +51 grpc_core::FakeResolver::MaybeFinishNextLocked                         +51   +49%
      [NEW]     +30 grpc_core::FakeResolverResponseGenerator::SetFailureLocked             +30  [NEW]
      +5.1%      +9 [Unmapped]                                                              +9  +5.1%
      +3.3%      +4 grpc_core::FakeResolver::FakeResolver                                   +4  +3.3%
  +0.7%    +225 src/core/ext/filters/client_channel/client_channel.cc                 +225  +0.7%
       +31%    +182 pick_after_resolver_result_done_locked                                +182   +31%
      +0.9%     +33 on_resolver_result_changed_locked                                      +33  +0.9%
      +2.5%     +10 [Unmapped]                                                             +10  +2.5%

  +0.1%   +1024 TOTAL                                                              +2.59Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by markdroth** [comment]
Known issues: #14234 #14240
