### PR TITLE
c++ check if workerthread could be spawned

### LINKED ISSUE #20366: c++ Synchronous Server unresponsive, after threadlimit was reached
### What version of gRPC and what language are you using?
gRPC 1.23.0, C++

### What operating system (Linux, Windows,...) and version?
Red Hat Enterprise Linux Server release 7.6

### What runtime / compiler are you using (e.g. python version or version of gcc)
clang7el7

### Summary
When the server is unable to spawn a new worker thread (because ulimit -u was reached), this is silently ignored and leads to it being unable to respond, even after the offending threads ended.
Possible solution outlined.

### What did you do?
Using a simple bash-script i started a large number of client processes on the same machine (and same user) as the server:
```
#!/bin/bash
count=4200
for (( i=0; i<$count; i++ )); do
  ./myForeverPollingClient &
done
```

When i let these clients end (more or less gracefully), the server does not respond to grpc calls and cannot shutdown regularly anymore.

### What did you expect to see?
* the server responds with "resource exhausted" messages, as long as the tight process situation remains
* after ending the client processes the server responds to calls as expected, without needing to restart the server
* the server can shutdown regularly

### What did you see instead?
Server did not react and could not shut down gracefully.

### Locating the error:
Debugging a sane server and comparing it to the unresponsive one i am missing one worker thread (ThreadManager::MainWorkLoop).

By adding some debug output and debugging the unresponsive server some more i could solve the issue, but i am not sure, if this is the best way - so i would appreciate you looking into it:

### The root of the problem, that i could track:
In src/cpp/thread_manager/thread_manager.cc:void ThreadManager::MainWorkLoop() there is some code that spawns a "new WorkerThread".
This starts a "grpc_core::Thread" in its constructor - when this grpc_core::Thread fails to create a pthread, this is ignored by the constructor code (success gets defaulted to nullptr in src/core/lib/gprpp/thd.h).
Back in the ThreadManagers MainWorkLoop it is assumed, that the WorkerThread has been spawned and in the end the MainWorkLoop is exited ( num_pollers_ would be >= max_pollers_ ).

### The solution that worked for me:
 * added a boolean flag to the WorkerThread (created_).
 * used it when invoking grpc_core::Thread
 * added the getter function isCreated to the WorkerThread
 * Saved new WorkerThread() to a pointer, when isCreated evaluated to false:
   * num_pollers_-- 
   * num_threads_--
   * resource_exhausted=true

### After patching this:
* the server responds with "resource exhausted" messages, as long as the tight process situation remains
* after ending the client processes the server responds to calls as expected, without needing to restart the server
* the server can shutdown regularly

### Open items
* what about the lock - would this be needed here?
* what if "void ThreadManager::Initialize()" can not get WorkerThreads?
* is there a better way altogether

### PR DESCRIPTION
**Pull request by chrisse74**
As described in #20366 - when the server is unable to spawn a new worker thread, this is silently ignored and leads to it being unable to respond, even if after some time new threads could be spawned.

This PR proposes to solve this by
* checking the return-value of grpc_core::Thread
* adjusting num_pollers, num_threads
* reporting resource_exhausted

Fixes #20366

@nicolasnoble

### CODE REVIEW

File: src/cpp/thread_manager/thread_manager.h [hunk 1]
```diff
@@ -124,13 +124,15 @@ class ThreadManager {
     WorkerThread(ThreadManager* thd_mgr);
     ~WorkerThread();
 
+    bool isCreated();
```
Comment (vjpai) [inline src/cpp/thread_manager/thread_manager.h]: Let's rename this to `created()` since it's a simple getter. And also label it `const` (and just place the definition inline).

File: src/cpp/thread_manager/thread_manager.cc [hunk 2]
```diff
@@ -34,15 +34,28 @@ ThreadManager::WorkerThread::WorkerThread(ThreadManager* thd_mgr)
...
 
 void ThreadManager::WorkerThread::Run() {
   thd_mgr_->MainWorkLoop();
   thd_mgr_->MarkAsCompleted(this);
 }
 
+
+bool ThreadManager::WorkerThread::isCreated() {
+  return created_;
+}
```
Comment (vjpai) [inline src/cpp/thread_manager/thread_manager.cc]: I think we can move this defn inline (and i should probably do so for the other members of `ThreadManager::WorkerThread` in a separate PR). I've also suggested a new name in my comment on the header file.

**Comment by vjpai** [comment]
I'm in the process of updating thread_manager_test for other reasons so we can also add a test there for this case.

File: src/cpp/thread_manager/thread_manager.cc (hunk 2 above)
Comment (vjpai) [reply src/cpp/thread_manager/thread_manager.cc]: No, inline in a .cc won't work in general (though I suppose it's ok in this case since the use is in the same translation unit). I just meant moving it into the .h file so it looks like

```cpp
   bool created() const { return created_; }
```

File: src/cpp/thread_manager/thread_manager.h (hunk 1 above)
Comment (chrisse74) [reply src/cpp/thread_manager/thread_manager.h]: Renamed isCreated and labeled it const, as suggested.

File: src/cpp/thread_manager/thread_manager.cc (hunk 2 above)
Comment (chrisse74) [reply src/cpp/thread_manager/thread_manager.cc]: Renamed isCreated, inlined it and labeled it const, as suggested. :)

Comment (chrisse74) [reply src/cpp/thread_manager/thread_manager.cc]: Just read your comment... expect a new commit in a few minutes... :)

Comment (vjpai) [reply src/cpp/thread_manager/thread_manager.cc]: Thanks for putting up with my comments. I'd like to get this in.

Comment (chrisse74) [reply src/cpp/thread_manager/thread_manager.cc]: You're welcome - I also want to do this the right way... :)

**Comment by chrisse74** [comment]
@vjpai Referencing your comment:
> I think we could let this through if the tests pass and the changes that I requested are made, but I'm also interested in getting a testing strategy for this. I'm thinking of having a test-only implementation of grpc_core::Thread that can fail after hitting some environment limit and then using that in the existing thread_manager_test

Maybe this can be done with also having #20418 in mind. There is no solution to this one yet, but the principle for testing it should be the same: instead of hitting the thread-limit, the open-file file-limit is reached.

**Comment by vjpai** [comment]
@chrisse74 I was looking into that as well. The issue is that there is no ulimit on the # of threads per process, only on the number of threads per user (which will wreck our test infra, I think). I was wondering if we could do something by ulimiting the virtual memory usage of the process to be a small multiple of the virtual stack size of the threads but that seems ugly (slimy but satisfying, maybe?)

**Comment by vjpai** [comment]
I added a formatting commit to this PR that hopefully makes the sanity check pess.

**Comment by chrisse74** [comment]
Thanks for the formatting. :)

**Comment by vjpai** [comment]
@chrisse74 Sometimes it's all that I can contribute.

**Comment by chrisse74** [comment]
> @chrisse74 I was looking into that as well. The issue is that there is no ulimit on the # of threads per process, only on the number of threads per user (which will wreck our test infra, I think). I was wondering if we could do something by ulimiting the virtual memory usage of the process to be a small multiple of the virtual stack size of the threads but that seems ugly (slimy but satisfying, maybe?)

@vjpai you could start the server process in a new bash, as it controls only the resources available to the current shell...

**Comment by vjpai** [comment]
Ahh, yes, that only applies to the self and child processes, in which case we could muck with the ulimit in the test itself. I'll give that a try.

**Comment by vjpai** [comment]
@hcaseyal Can you please provide a secondary review? Thanks!

**Comment by vjpai** [comment]
@karthikravis - can you provide a secondary review?

**Comment by chrisse74** [comment]
Thanks! :)
