### PR TITLE
Switch to command-arg for Python split-codegen

### LINKED ISSUE #8753: grpcio-tools protoc binary behavior is different from vanilla protoc
Vanilla provides a `GenerateResponseContext` rather than a `CommandLineInterface::GeneratorContextImpl`. This means that `OpenForAppend` doesn't have an implementation and causes a segfault in all use-cases with vanilla `protoc`. This is probably because the generator context provided in `grpcio-tools`'s `protoc` is compiled in rather than created when invoking a separated plugin process.

### PR DESCRIPTION
**Pull request by soltanmm-google**
Almost fixes #8753 (which still needs a regression test).

### CODE REVIEW

File: src/compiler/python_generator.cc [hunk 1]
```diff
@@ -780,28 +806,12 @@ bool PythonGrpcGenerator::Generate(const FileDescriptor* file,
...
-  tie(success, pb2_code) = generator.GetGrpcServices();
-  if (success) {
-    generator.generate_in_pb2_grpc = true;
-    tie(success, grpc_code) = generator.GetGrpcServices();
-    if (success) {
-      pb2_coded_out.WriteRaw(pb2_code.data(), pb2_code.size());
-      grpc_coded_out.WriteRaw(grpc_code.data(), grpc_code.size());
-      return true;
-    }
+  if (parameter == "grpc2") {
```
Comment (nathanielmanistaatgoogle) [inline src/compiler/python_generator.cc]: This is where the flag is defined, right? What can we do to make it look like a flag? Can it have a name like `grpc_code_elements_in_separate_file`? Preferably something with the same meaning but as short as possible? `grpc2`, for all its brevity, does nothing to suggest its function.

File: src/compiler/python_generator.cc [hunk 2]
```diff
@@ -760,6 +760,32 @@ PythonGrpcGenerator::PythonGrpcGenerator(const GeneratorConfiguration& config)
 
 PythonGrpcGenerator::~PythonGrpcGenerator() {}
 
+static bool GenerateGrpc(GeneratorContext* context, PrivateGenerator& generator,
+                         grpc::string file_name, bool generate_in_pb2_grpc) {
+  bool success = false;
```
Comment (nathanielmanistaatgoogle) [inline src/compiler/python_generator.cc]: This may be a C++ thing I don't understand, but can we get away without assigning a value to this field at this point? The value assigned here is never read from the field before the field is reassigned, right?

Comment (soltanmm-google) [inline src/compiler/python_generator.cc]: Right, for some reason I was thinking about it in terms of assignment by reference, but `std::tie` is on the lhs.

File: src/compiler/python_generator.cc (hunk 1 above)
Comment (soltanmm-google) [inline src/compiler/python_generator.cc]: I was going with it suggesting gRPC 2.0 behavior, and I do have a slight preference towards that kind of an implication.

Comment (soltanmm-google) [inline src/compiler/python_generator.cc]: Renamed to not look like the `2` in `urllib2` or `http/2` but to instead look like a semver.

**Comment by soltanmm-google** [comment]
And I derped up the name change because I forgot to change the name used in the tests. Gonna let Jenkins have another pass then merge.
