### PR TITLE
Make the gem build on TruffleRuby

### LINKED ISSUE #23069: The grpc gem doesn't build with TruffleRuby on Mac OS
### What version of gRPC and what language are you using?

Ruby, latest version (1.28.0) & git master head.

### What operating system (Linux, Windows,...) and version?

Mac OS Catalina (10.15.4)

### What runtime / compiler are you using (e.g. python version or version of gcc)

Ruby: [TruffleRuby] (git head, dev for 20.2)
GCC: [Sulong] (dev for 20.2)

[TruffleRuby]: https://github.com/oracle/truffleruby
[Sulong]: https://github.com/oracle/graal/tree/master/sulong

### What did you do?

As part of our work on TruffleRuby, we are trying to get the grpc gem to build and run on TruffleRuby (cf. https://github.com/oracle/truffleruby/issues/1982).

TruffleRuby supports native Ruby extensions using [Sulong], which re-implement the LLVM toolchain on top of GraalVM.

grpc builds correctly with TruffleRuby/Sulong on Linux, but we ran into multiple build issues on Mac OS, which I managed to fix in the following way:

1. Remove out all lines ending with `if RUBY_PLATFORM =~ /darwin/` in [`extconf.rb](https://github.com/grpc/grpc/blob/master/src/ruby/ext/grpc/extconf.rb).
2. Add the path to our LLVM toolchain binaries on the path.

Regarding (1), this might be too broad a change, but many of those definitely have adverse effects. In particular, `ENV['ARCH_FLAGS'] = '-arch i386 -arch x86_64'` caused the `lipo` error reported by our user (https://github.com/oracle/truffleruby/issues/1982). `ENV['AR'] = 'libtool -o' if RUBY_PLATFORM =~ /darwin/` overwrites the `AR` variable set by TruffleRuby which points to Sulong's own `libtool`.

Regarding (2), this is necessary because the top-level makefile calls `ranlib` directly instead of indirecting through `$(RANLIB)`. Hopefully that's the only issue fixed by that, I will try to confirm this. Replacing `ranlib` to `$(RANLIB)`.

To reproduce: 
- install [TruffleRuby]
- (with TruffleRuby on path): `gem install grpc`

Note that even if you fix the `ranlib` issue, it won't work as of right now because we still have to define `RANLIB` in TruffleRuby's `RbConfig`. I'll get that merged ASAP and update when done.

Note that `grpc` currently *does not run* on TruffleRuby after installing (on any platform), but that is most likely due to a bug on our side which we have reported to the Sulong team.

### What did you expect to see?

The gem installing correctly.

### What did you see instead?

Detailed in https://github.com/oracle/truffleruby/issues/1982 :
- `lipo`issues
- `libtool` issues (after fixing the above)
- `ranlib` issues (after fixing the above)

### PR DESCRIPTION
**Pull request by eregon**
This set of changes makes it possible to install the `grpc` gem on TruffleRuby.
TruffleRuby as part of GraalVM ships with its own LLVM toolchain and as such some changes are needed to make it build.
This fixes #23069.
This is important as several TruffleRuby users including Shopify cannot install the grpc gem out of the box without this fix.
Replaces #24632.

@markdroth

### CODE REVIEW

**Comment by nirvdrum** [comment]
@ctiller Thanks for kicking off that CI process. I tried looking at the failures, but the logs are fairly sparse. Is there any way to see what failed? Is it just a matter of needing to be rebased against the _master_ branch?

**Comment by eregon** [comment]
@apolcyn @ctiller I just rebased, could you trigger the CI?

Rebasing is rather painful with the `templates/src/ruby/ext/grpc/extconf.rb.template` (which duplicates `src/ruby/ext/grpc/extconf.rb` in the repo), maybe the template could only define the version and just require a regular `.rb` file next to the extconf.rb, or the template could generate a `version.rb` file or something.
Would you be interested in a PR doing that?

I would love to have some feedback on this PR or for it getting merged, it's been many months and very little feedback.
AFAIK this PR does not affect building grpc on CRuby at all, so from that point of view it should be completely safe to merge.

**Comment by eregon** [comment]
cc @jtattermusch which I saw did some work in this area as well recently.

File: src/ruby/ext/grpc/extconf.rb [hunk 1]
```diff
@@ -112,7 +142,7 @@
 create_makefile(output)
 
 strip_tool = RbConfig::CONFIG['STRIP']
-strip_tool += ' -x' if darwin
+strip_tool = 'strip -x' if apple_toolchain?
```
[the remark this answers is not in the document]
Comment (eregon) [reply src/ruby/ext/grpc/extconf.rb]: This should be fixed now, could you retrigger the CI?

**Comment by jcoleman** [comment]
@eregon Is anything still remaining on this? Waiting on committers?

**Comment by eregon** [comment]
The CI is now fully green.
Could a grpc maintainer merge this PR? (cc @apolcyn)

**Comment by HannahShiSFB** [comment]
LGTM

**Comment by dennycd** [comment]
@eregon can you rebase on latest master and rerun the test ? thanks

**Comment by eregon** [comment]
Rebased, please merge it as soon as possible so it doesn't get conflicts yet another time.

**Comment by eregon** [comment]
Ping, please trigger CI and merge this PR.

**Comment by jcoleman** [comment]
@apolcyn @ctiller It's pretty frustrating to see @eregon repeatedly getting this properly updated only to have it ignored by the maintainers such that it's always awaiting another rebase by the time anyone looks at it. Could you please give this PR the attention it deserves and fix this gem on TruffleRuby?

**Comment by eregon** [comment]
Agreed. I've also never heard any reply regarding removing the template (suggested in https://github.com/grpc/grpc/pull/27660/#issuecomment-1018680201 ), so I went ahead and made a PR to remove it: https://github.com/grpc/grpc/pull/30017
That will make it so much easier for everyone to modify/maintain the extconf.rb, so please review and merge that soon.

**Comment by eregon** [comment]
Thank you for merging #30017, that makes it significantly easier to rebase and modify the `extconf.rb`.
@dennycd I have rebased on latest master, could you trigger a CI run? (unless it's already running maybe?)

**Comment by eregon** [comment]
I confirm the gem installation works on TruffleRuby with:
```
$ chruby 3.0.3
$ rake gem
$ chruby truffleruby-dev
$ gem i ./pkg/grpc-1.48.0.dev.gem
$ ruby -v -e 'require "grpc"; p GRPC'
truffleruby 22.2.0-dev-8839057f, like ruby 3.0.3, GraalVM CE Native [x86_64-linux]
GRPC

```

**Comment by eregon** [comment]
I've looked at the output of the failed CI jobs and it's unclear to me if it's related to changes in this PR or not (some clearly, some unclear). Could you rerun those failed jobs?

**Comment by dennycd** [comment]
thanks @eregon . ObjC/iOS tests are unrelated (https://github.com/grpc/grpc/pull/30037). Re-triggered Ruby basic test.

**Comment by eregon** [comment]
The CI is all green now, except `Distribution Tests PHP MacOS` which looks unrelated (and seems unlikely to be affected by changes in this PR). Ready to merge?

**Comment by eregon** [comment]
@dennycd @apolcyn @HannahShiSFB Hello, could you please merge this?
Or if there is anything preventing to merge it, could you write it here?

File: src/ruby/ext/grpc/extconf.rb [hunk 2]
```diff
@@ -101,7 +126,9 @@
 end
 
 $LDFLAGS << ' -Wl,-wrap,memcpy' if linux
-$LDFLAGS << ' -static-libgcc -static-libstdc++' if linux
+if linux && RUBY_ENGINE != 'truffleruby'
```
Comment (apolcyn) [inline src/ruby/ext/grpc/extconf.rb:129]: nit: can we please add a comment here why this can't work on truffleruby?

File: src/ruby/ext/grpc/extconf.rb [hunk 3]
```diff
@@ -20,49 +20,73 @@
...
+end
+
+if apple_toolchain && !cross_compiling
   ENV['AR'] = 'libtool'
   ENV['ARFLAGS'] = '-o'
 end
 
-ENV['EMBED_OPENSSL'] = 'true'
-ENV['EMBED_ZLIB'] = 'true'
+# Don't embed on Truffleruby (constant-time crypto is unsafe with Sulong, slow build times)
```
Comment (apolcyn) [inline src/ruby/ext/grpc/extconf.rb:70]: nit: can we separate this comment into OPENSSL and ZLIB parts?

E.g., one comment above openssl for why we don't embed openssl.

And another comment above zlib for why we don't embed zlib?

**Review by apolcyn — APPROVED** [review]
Some minor comments, otherwise approving.

Only general comment here is that we don't have a test to make sure that the library will continue to build, load, etc. on truffleruby. To address that, we could probably add a distribtest target to [here](https://github.com/grpc/grpc/blob/3a8e54b005f44a72623dcdd911ddd9419878f638/tools/run_tests/artifacts/distribtest_targets.py#L464), that would e.g. build grpc-ruby from [source](https://github.com/grpc/grpc/blob/3a8e54b005f44a72623dcdd911ddd9419878f638/test/distrib/ruby/run_distrib_test.sh#L30) on linux (we would need to add a dockerfile for that under [here](https://github.com/grpc/grpc/tree/master/tools/dockerfile/distribtest)).

If you could provide an example Dockerfile to run such a test in, we could probably help wire it up to our CI. Alternatively we could review a PR for it.

That said, we don't need such a test to block this PR (although it might help to prevent regressions).

**Comment by apolcyn** [comment]
@veblush can I get a second look?

File: src/ruby/ext/grpc/extconf.rb (hunk 2 above)
Comment (eregon) [reply src/ruby/ext/grpc/extconf.rb:131]: Done, and I checked it works with the current code and doesn't without (`External LLVMFunction _ZNKSt3__119__shared_weak_count13__get_deleterERKSt9type_info cannot be found. (RuntimeError)`)

File: src/ruby/ext/grpc/extconf.rb (hunk 3 above)
Comment (eregon) [reply src/ruby/ext/grpc/extconf.rb]: Done

**Comment by eregon** [comment]
Thank you for the review.
Indeed, adding a CI test would be best, I wasn't sure how to do that, thanks for the pointers. Ideally we'd test a known release of TruffleRuby on both Linux and macOS, because a large part of this PR is actually needed for macOS.
On macOS, Docker is not an option, but I see there are some distribtests on macOS, so I could try to follow those examples.
What's the command-line to run a single distribtest, to test it works locally?

> If you could provide an example Dockerfile to run such a test in, we could probably help wire it up to our CI.

These are the official Docker images of TruffleRuby:
https://github.com/graalvm/container/blob/master/truffleruby/README.md
Notably there is a Debian 10 image there, which is probably easiest given the existing Dockerfiles are based on Debian as well.
It's also fine to just use a plain `debian:10` image and copy the steps from https://github.com/graalvm/container/blob/master/truffleruby/Dockerfile.debian to just download truffleruby + run the `post_install_hook.sh` if needed.

I would prefer to merge this PR and then I follow up with another PR to add the CI tests if that is fine.
One advantage of that is to discuss on a separate smaller PR the details and how to wire up the tests.

**Review by veblush — APPROVED** [review]

**Comment by apolcyn** [comment]
Test failures are unrelated

**Comment by apolcyn** [comment]
@eregon 

> Indeed, adding a CI test would be best, I wasn't sure how to do that, thanks for the pointers. Ideally we'd test a known release of TruffleRuby on both Linux and macOS, because a large part of this PR is actually needed for macOS.
On macOS, Docker is not an option, but I see there are some distribtests on macOS, so I could try to follow those examples.
What's the command-line to run a single distribtest, to test it works locally?

I see. Setting up a macos distribtest would be, I think, a lot more involved. Adding a linux distribtest on the other hand would be fairly easy, just by adding a new dockerfile.

However, as written, these tests involve chaining between a couple of CI jobs. So I don't think I can give a single command to run them, that doesn't involve hacking other scripts.

Ultimately though, ruby distrib tests basically just run [this script](https://github.com/grpc/grpc/blob/master/test/distrib/ruby/run_distrib_test.sh) in whatever environment the test is interested in. The external git root env var points to a local directory where gems under test are.

> I would prefer to merge this PR and then I follow up with another PR to add the CI tests if that is fine.
One advantage of that is to discuss on a separate smaller PR the details and how to wire up the tests.

Thanks for the info. Agree this can be discussed outside this PR.
