### PR TITLE
Fix a Python spinlock bug

### LINKED ISSUE #9688: 100% CPU usage running greeter example?
[A user writes](https://groups.google.com/forum/#!topic/grpc-io/hzn6eKDSMlM):
```
I was trying out the greeter example in the repository and I
noticed that the server uses 100% CPU after the first request.
This only happens when started with Python 2, and not with
Python 3.

I'm using Python 2.7.13 on Arch Linux, grpc is installed with
pip in a fresh virtualenv. Does anyone experience the same
problem?
```

### PR DESCRIPTION
**Pull request by kpayson64**
Hopefully finally fixes #9688

There has been an issue where ```poll()``` calls spinlock in the Python implementation.  The strace looks as follows.

```
poll([{fd=3, events=POLLIN}, {fd=8, events=POLLIN}, {fd=5, events=POLLIN|POLLOUT}, {fd=11, events=0}], 4, 188) = 1 ([{fd=11, revents=POLLHUP}])
clock_gettime(CLOCK_MONOTONIC, {905930, 24155064}) = 0
poll([{fd=3, events=POLLIN}, {fd=8, events=POLLIN}, {fd=5, events=POLLIN|POLLOUT}, {fd=11, events=0}], 4, 188) = 1 ([{fd=11, revents=POLLHUP}])
clock_gettime(CLOCK_MONOTONIC, {905930, 24206581}) = 0
poll([{fd=3, events=POLLIN}, {fd=8, events=POLLIN}, {fd=5, events=POLLIN|POLLOUT}, {fd=11, events=0}], 4, 188) = 1 ([{fd=11, revents=POLLHUP}])
....
```

I've addressed several Python fd refcounting issues that could have possibly been the cause, but users are still reporting the issue.  This code ~~should~~ be uneeded, but given that users see this in production code but we don't have a reproduction case, I would like to solve this issue once and for all.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                           FILE SIZE
 ++++++++++++++ GROWING                             ++++++++++++++
  +0.3%     +32 src/core/lib/iomgr/ev_poll_posix.cc     +32  +0.3%
      +0.6%     +17 pollset_work                            +17  +0.6%
      +2.4%      +8 [Unmapped]                               +8  +2.4%
      +3.0%      +7 fd_create                                +7  +3.0%
  [ = ]       0 [None]                                   +8  +0.0%

  +0.0%     +32 TOTAL                                   +40  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

File: src/core/lib/iomgr/ev_poll_posix.cc [hunk 1]
```diff
@@ -1031,6 +1033,9 @@ static grpc_error* pollset_work(grpc_exec_ctx* exec_ctx, grpc_pollset* pollset,
                       pfds[i].fd, (pfds[i].revents & POLLIN_CHECK) != 0,
                       (pfds[i].revents & POLLOUT_CHECK) != 0, pfds[i].revents);
             }
+            if (pfds[i].revents & POLLHUP) {
```
Comment (sreecha) [inline src/core/lib/iomgr/ev_poll_posix.cc]: Please add a comment here that this is just a mitigation and add a reference to the PR.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                           FILE SIZE
 ++++++++++++++ GROWING                             ++++++++++++++
  +0.8%     +96 src/core/lib/iomgr/ev_poll_posix.cc     +96  +0.8%
      +1.7%     +49 pollset_work                            +49  +1.7%
      +9.0%     +32 fd_orphan                               +32  +9.0%
      +4.6%     +11 fd_create                               +11  +4.6%
      +1.2%      +4 [Unmapped]                               +4  +1.2%

 -------------- SHRINKING                           --------------
  [ = ]       0 [None]                                  -72  -0.0%

  +0.0%     +96 TOTAL                                   +24  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by kpayson64** [comment]
Something is pretty messed up here:  It looks like when remove fd's then end with pollhup they never end up getting freed...

**Comment by dhermes** [comment]
@kpayson64 FWIW I have a (Python) case that reliably gets into the `POLLHUP` spinlock, but it typically takes 65 minutes to trigger (one time it did after 44 minutes). I have backported this PR on the `v1.7.3` branch and am currently running my case with the modified `grpcio`.

The spinlock is **always** triggered by [this line][1], but the real culprit seems to be in the [C core][2]. In my reproducible case, there are `~54` threads that run `target=channel_spin` and the CPU thrashing doesn't happen until 40 or 41. In every case, **exactly one** of these threads kicks off a [thread to check metadata][3], and that exactly corresponds to the point where the thrashing starts.

[1]: https://github.com/grpc/grpc/blob/v1.8.0/src/python/grpcio/grpc/_channel.py#L695
[2]: https://github.com/grpc/grpc/blob/v1.8.0/src/python/grpcio/grpc/_cython/_cygrpc/completion_queue.pyx.pxi#L93-L94
[3]: https://github.com/grpc/grpc/blob/v1.8.0/src/python/grpcio/grpc/_cython/_cygrpc/credentials.pyx.pxi#L43

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                           FILE SIZE
 ++++++++++++++ GROWING                             ++++++++++++++
  [ = ]       0 [None]                                 +280  +0.0%
  +0.8%     +96 src/core/lib/iomgr/ev_poll_posix.cc     +96  +0.8%
      +1.7%     +48 pollset_work                            +48  +1.7%
      +9.0%     +32 fd_orphan                               +32  +9.0%
      +4.6%     +11 fd_create                               +11  +4.6%
      +1.5%      +5 [Unmapped]                               +5  +1.5%

  +0.0%     +96 TOTAL                                  +376  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by dhermes** [comment]
:tada:

**Comment by kpayson64** [comment]
I'll try to get a patch release out by tomorrow.

**Comment by kpayson64** [comment]
1.8.2 has been pushed

**Comment by nicolasnoble** [comment]
This is causing MacOS-specific issues in the poller now. Running the resource_quota_server test under mac will fail almost immediately with this PR in.

**Comment by nicolasnoble** [comment]
More specifically, the test results of this PR were already failing:
https://sponge.corp.google.com/invocation?id=080130e9-fc00-4cca-bf13-885dd553f344&searchFor
https://sponge.corp.google.com/target?id=080130e9-fc00-4cca-bf13-885dd553f344&target=github/grpc/c_macos_dbg_native&searchFor=&show=FAILED&sortBy=STATUS

**Comment by dhermes** [comment]
@kpayson64 @nathanielmanistaatgoogle Now that this has been reverted (#13898), will there be a new PR to track progress?

**Comment by kpayson64** [comment]
I've created #13918 to track the roll forward on master.  I'm currently looking into the issue.

**Comment by dhermes** [comment]
Thanks @kpayson64!
