### PR TITLE
PHP: change return type annotation of generated PHP methods

### LINKED ISSUE #23736: Wrong return types in php code
Hello. 

### What version of gRPC and what language are you using?
gRPC 1.30.2. 
PHP 7.3

### What operating system (Linux, Windows,...) and version?
Debian 10.5

### What did you do?
Today i've updated gprc-php-plugin and regenerated php code from my protofiles.After that PhpStorm and phpstan started to report type errors. After some research i've found this pr - #22671. It adds `return` phpdoc attribute to methods in generated client code. For example, let's generate `Math.proto`

Before this pr generated code for `Div` looked like this:
```php
/**
 * Div divides DivArgs.dividend by DivArgs.divisor and returns the quotient
 * and remainder.
 * @param \Math\DivArgs $argument input argument
 * @param array $metadata metadata
 * @param array $options call options
 */
public function Div(\Math\DivArgs $argument,
  $metadata = [], $options = []) {
    return $this->_simpleRequest('/math.Math/Div',
    $argument,
    ['\Math\DivReply', 'decode'],
    $metadata, $options);
}
```

After it looks like this:
```php
/**
 * Div divides DivArgs.dividend by DivArgs.divisor and returns the quotient
 * and remainder.
 * @param \Math\DivArgs $argument input argument
 * @param array $metadata metadata
 * @param array $options call options
 * @return \Math\DivReply
 */
public function Div(\Math\DivArgs $argument,
  $metadata = [], $options = []) {
    return $this->_simpleRequest('/math.Math/Div',
    $argument,
    ['\Math\DivReply', 'decode'],
    $metadata, $options);
}
```

Now, in code
```php
<?php

use Grpc\ChannelCredentials;

require_once 'vendor/autoload.php';

$client = new \Math\MathClient('localhost', [
    'credentials' => ChannelCredentials::createInsecure()
]);
$result = $client->Div(new \Math\DivArgs());

echo get_class($result) . PHP_EOL;

[$response, $status] = $result->wait();
```

IDE thinks that variable `$result` is of type `\Math\DivReply`:
image

But it is not, it is of type `Grpc\UnaryCall`:
image

And this is correct. But now, if we try to call `wait()` on result - there is ide error:
image

### What did you expect to see?
I think #22671 should be reverted or further improved. One way to improve is to replace 
```php
 * @return \Math\DivReply
```
with
```php
 * @return \Grpc\UnaryCall
```
or, to preserve result type, with additional comment:
```php
 * @return \Grpc\UnaryCall call with response type \Math\DivReply
```

I can provide PR if needed. Thanks.

### PR DESCRIPTION
**Pull request by HannahShiSFB**
Fixes #23736

### CODE REVIEW

File: src/compiler/php_generator.cc [hunk 1]
```diff
@@ -78,10 +78,16 @@ void PrintMethod(const MethodDescriptor* method, Printer* out) {
...
+      vars["return_type_id"] = "\\Grpc\\BidiStreamingCall";
+    } else {
+      vars["return_type_id"] = "\\Grpc\\ClientStreamingCall";
+    }
     out->Print(vars,
                " * @param array $$metadata metadata\n"
                " * @param array $$options call options\n"
-               " * @return \\$output_type_id$\n */\n"
+               " * @return $return_type_id$ with "
+               "response type \\$output_type_id$\n */\n"
```
Comment (stanley-cheung) [inline src/compiler/php_generator.cc:90]: Thanks for doing this. But there is probably no need for ` with response type ...`. You can remove it.

One day, if PHP has generics type perhaps we can add it back properly.

Comment (HannahShiSFB) [reply src/compiler/php_generator.cc]: comment addressed
