### PR TITLE
Fail decompression when the gzip trailer is missing

### LINKED ISSUE #20889: C core should verify gzipped messages are correctly terminated
.Gzip has a footer containing an adler32 (think CRC32). grpc-dotnet recently introduced a bug where this was missing (https://github.com/grpc/grpc/issues/20884). However, the C++ client did not fail. The gzip decoder should have failed noticing the checksum was missing/invalid.

(https://github.com/grpc/grpc-go/issues/3135 is the equivalent of this issue for Go.)

### PR DESCRIPTION
**Pull request by yashykt**
Fix #20889

### CODE REVIEW

File: test/core/compression/message_compress_test.cc [hunk 1]
```diff
@@ -196,6 +196,34 @@ static void test_bad_decompression_data_crc(void) {
...
+  grpc_slice_buffer_init(&corrupted);
+  grpc_slice_buffer_init(&output);
+  grpc_slice_buffer_add(&input, create_test_value(ONE_MB_A));
+
+  grpc_core::ExecCtx exec_ctx;
+  /* compress it */
+  grpc_msg_compress(GRPC_MESSAGE_COMPRESS_GZIP, &input, &corrupted);
+  /* corrupt the output by smashing the CRC */
+  GPR_ASSERT(corrupted.count > 1);
+  GPR_ASSERT(GRPC_SLICE_LENGTH(corrupted.slices[1]) > 8);
```
Comment (muxi) [inline test/core/compression/message_compress_test.cc:215]: Are you sure the compressed slice buffer will always contain 2 slices? Maybe worth some more sophisticated approach to remove the last 8 bytes of the buffer.

**Comment by muxi** [comment]
And note the error in ObjC build.

File: src/core/lib/compression/message_compress.cc [hunk 2]
```diff
@@ -34,7 +34,7 @@
 static int zlib_body(z_stream* zs, grpc_slice_buffer* input,
                      grpc_slice_buffer* output,
                      int (*flate)(z_stream* zs, int flush)) {
-  int r;
+  int r = Z_OK;
```
Comment (muxi) [inline src/core/lib/compression/message_compress.cc:37]: I wonder if it should be initialized as Z_STREAM_END instead. Otherwise compressing an empty string will end up in a failure?

Comment (yashykt) [reply src/core/lib/compression/message_compress.cc:37]: yes, and I think that should be right, since without the correct headers and footers, it makes no sense to call the message decompression a success

Comment (yashykt) [reply src/core/lib/compression/message_compress.cc:37]: thinking again, Z_STREAM_END should also be fine, since the compression/decompression semantics are in our control, and it would may be fine to call it a success on an empty message

File: test/core/compression/message_compress_test.cc [hunk 3]
```diff
@@ -210,12 +210,10 @@ static void test_bad_decompression_data_missing_trailer(void) {
   grpc_core::ExecCtx exec_ctx;
   /* compress it */
   grpc_msg_compress(GRPC_MESSAGE_COMPRESS_GZIP, &input, &corrupted);
-  /* corrupt the output by smashing the CRC */
-  GPR_ASSERT(corrupted.count > 1);
-  GPR_ASSERT(GRPC_SLICE_LENGTH(corrupted.slices[1]) > 8);
+  GPR_ASSERT(GRPC_SLICE_LENGTH(corrupted.slices[corrupted.count - 1]) > 8);
+  /* Remove the footer by manipulating the slice length */
```
Comment (muxi) [inline test/core/compression/message_compress_test.cc]: Hmm it's definitely better, but what if there are 3 slices or the length of the second slice is less than 8? Does core have any function to cut the tail of a slice buffer in a sophisticated way? Or alternatively, if you have reason to believe that the compressed slice buffer will always contain exactly 2 slices and the second slice will always be longer than 8, we can put the reason as comment here and move on.

File: src/core/lib/compression/message_compress.cc (hunk 2 above)
Comment (yashykt) [reply src/core/lib/compression/message_compress.cc]: done

File: test/core/compression/message_compress_test.cc (hunk 3 above)
Comment (yashykt) [reply test/core/compression/message_compress_test.cc]: The gzip footer is of 8 bytes so the last slice should have atleast 8 bytes, but I changed the code

Comment (muxi) [reply test/core/compression/message_compress_test.cc]: Cool thanks

**Comment by yashykt** [comment]
Issue : #22019

**Comment by yashykt** [comment]
Thanks for reviewing!
