### PR TITLE
Fix missing include for std::string

### LINKED ISSUE #23019: Build failure with MSVC 2019 16.6
### What version of gRPC and what language are you using?
C++ v1.29.0
C++ current master

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
MSVC 2019 16.6

### What did you do?
Follow ninja build instructions
```
mkdir cmake/build
cd cmake/build
cmake ../.. -GNinja -DCMAKE_BUILD_TYPE=Release
cmake --build .
```

### What did you expect to see?
grpc builds without errors

### What did you see instead?
Quite a few C7626 errors related to https://docs.microsoft.com/en-us/cpp/overview/cpp-conformance-improvements?view=vs-2019#unnamed-classes-in-typedef-declarations

### PR DESCRIPTION
**Pull request by rcleveng**
Fixes #23019 with default options (won't fix /permissive- or /std:latest)

@yashykt

### CODE REVIEW

File: src/core/lib/debug/stats.h [hunk 1]
```diff
@@ -25,6 +25,8 @@
 #include "src/core/lib/debug/stats_data.h"
 #include "src/core/lib/iomgr/exec_ctx.h"
 
+#include <string>
```
Comment (yashykt) [inline src/core/lib/debug/stats.h:28]: Please move this above line 24

Comment (rcleveng) [reply src/core/lib/debug/stats.h]: Done.

**Comment by yashykt** [comment]
Thanks for the PR! We should be able to merge this as soon as the second review is in and all the tests are done running
