### PR TITLE
{grpclb,client_lb}_end2end: Fix epoll1 flakes

### LINKED ISSUE #12290: Fix grpclb_end2_end_test's SingleBalancerTest.RepeatedServerlist under epoll1
The test makes assumptions about subchannel connection ordering that don't hold under epoll1.

### LINKED ISSUE #12315: Flaky: c++_linux_asan_native.bins/asan/client_lb_end2end_test --gtest_filter=ClientLbEnd2endTest.RoundRobinReresolve GRPC_POLL_STRATEGY=epoll1
### What version of gRPC and what language are you using?
 Master, C++
 
### What operating system (Linux, Windows, …) and version?
 Linux
 
```
I0828 23:13:44.653631554   51887 client_lb_end2end_test.cc:186] starting server on port 24798
I0828 23:13:44.654172475   51893 server_builder.cc:269]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I0828 23:13:44.662100195   51887 client_lb_end2end_test.cc:193] server startup complete
I0828 23:13:44.662221312   51887 client_lb_end2end_test.cc:186] starting server on port 27553
I0828 23:13:44.662550697   51895 server_builder.cc:269]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I0828 23:13:44.668686197   51887 client_lb_end2end_test.cc:193] server startup complete
I0828 23:13:44.668806542   51887 client_lb_end2end_test.cc:186] starting server on port 11412
I0828 23:13:44.669086532   51897 server_builder.cc:269]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I0828 23:13:44.674955892   51887 client_lb_end2end_test.cc:193] server startup complete
test/cpp/end2end/client_lb_end2end_test.cc:535: Failure
      Expected: 1
To be equal to: servers_[i]->service_.request_count()
      Which is: 0
for backend #0
I0828 23:13:44.687381587   51887 subchannel.c:683]           Connect failed: {"created":"@1503987224.687204205","description":"Failed to connect to remote host: OS Error","errno":111,"file":"src/core/lib/iomgr/tcp_client_posix.c","file_line":200,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:127.0.0.1:24798"}
I0828 23:13:44.687437159   51887 subchannel.c:479]           Retry in 1.999167553 seconds
I0828 23:13:44.687645265   51887 subchannel.c:683]           Connect failed: {"created":"@1503987224.687492505","description":"Failed to connect to remote host: OS Error","errno":111,"file":"src/core/lib/iomgr/tcp_client_posix.c","file_line":200,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:127.0.0.1:27553"}
I0828 23:13:44.687686071   51887 subchannel.c:479]           Retry in 1.999171300 seconds
I0828 23:13:44.687883639   51887 subchannel.c:683]           Connect failed: {"created":"@1503987224.687736227","description":"Failed to connect to remote host: OS Error","errno":111,"file":"src/core/lib/iomgr/tcp_client_posix.c","file_line":200,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:127.0.0.1:11412"}
I0828 23:13:44.687936972   51887 subchannel.c:479]           Retry in 1.999090318 seconds
I0828 23:13:44.688234020   51887 client_lb_end2end_test.cc:186] starting server on port 24798
I0828 23:13:44.688524519   51902 server_builder.cc:269]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I0828 23:13:44.693519695   51887 client_lb_end2end_test.cc:193] server startup complete
I0828 23:13:44.693605400   51887 client_lb_end2end_test.cc:186] starting server on port 27553
I0828 23:13:44.693823546   51904 server_builder.cc:269]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I0828 23:13:44.698658722   51887 client_lb_end2end_test.cc:193] server startup complete
I0828 23:13:44.698799356   51887 client_lb_end2end_test.cc:186] starting server on port 11412
I0828 23:13:44.699054358   51906 server_builder.cc:269]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I0828 23:13:44.703725752   51887 client_lb_end2end_test.cc:193] server startup complete
I0828 23:13:46.687034450   51889 subchannel.c:429]           Failed to connect to channel, retrying
I0828 23:13:46.688475406   51908 subchannel.c:429]           Failed to connect to channel, retrying
I0828 23:13:46.688822910   51908 subchannel.c:429]           Failed to connect to channel, retrying
```

### PR DESCRIPTION
**Pull request by dgquintas**
These tests were making assumptions about the order the subchannels would connect and become READY. We cannot make those. The epoll1 poller, with its different timings, exposed these shortcomings.

Fixes #12290 
Fixes #12315

### CODE REVIEW

File: test/cpp/end2end/grpclb_end2end_test.cc [hunk 1]
```diff
@@ -429,20 +441,29 @@ class GrpclbEnd2endTest : public ::testing::Test {
...
+    Status status = stub_->Echo(&context, request, response);
+    if (local_response) delete response;
+    return status;
+  }
+
+  void CheckRpcSendOk(const size_t times = 1) {
+    for (size_t i = 0; i < times; ++i) {
+      EchoResponse response;
+      const Status status = SendRpc(&response);
+      EXPECT_TRUE(status.ok());
```
Comment (markdroth) [inline test/cpp/end2end/grpclb_end2end_test.cc]: Suggest logging the code and message if this expectation fails, as was done in the original code.

File: test/cpp/end2end/grpclb_end2end_test.cc [hunk 2]
```diff
@@ -606,49 +612,28 @@ TEST_F(SingleBalancerTest, RepeatedServerlist) {
...
-          << "for backend #" << i;
-  }
-  EXPECT_EQ(statuses_and_responses.size(), num_backends_ / 2);
-  for (const auto& status_and_response : statuses_and_responses) {
-    const Status& status = status_and_response.first;
-    const EchoResponse& response = status_and_response.second;
-    EXPECT_TRUE(status.ok()) << "code=" << status.error_code()
-                             << " message=" << status.error_message();
-    EXPECT_EQ(response.message(), kMessage_);
+    num_requests += backend_servers_[i].service_->request_count();
```
Comment (markdroth) [inline test/cpp/end2end/grpclb_end2end_test.cc]: I'm not sure this check is actually telling us anything, since it doesn't say anything about the distribution of requests across backends.  And it can't possibly fail, because if we already sent N successful requests, then the total number of requests served by all backends must be N.

Stepping back a bit, what is the overall purpose of this test?  It seems like all we're really testing here is that if round_robin gets an update that is identical to its existing list of addresses, that it won't wind up changing anything.  Would it be better to just test that behavior in the round_robin test directly?

File: test/cpp/end2end/grpclb_end2end_test.cc [hunk 3]
```diff
@@ -664,16 +649,7 @@ TEST_F(SingleBalancerTest, BackendsRestart) {
       0);
   // Make sure that trying to connect works without a call.
   channel_->GetState(true /* try_to_connect */);
-  // Send 100 RPCs per server.
```
Comment (markdroth) [inline test/cpp/end2end/grpclb_end2end_test.cc]: Please keep this comment.

File: test/cpp/end2end/grpclb_end2end_test.cc [hunk 4]
```diff
@@ -521,17 +540,12 @@ TEST_F(SingleBalancerTest, Vanilla) {
...
-  for (const auto& status_and_response : statuses_and_responses) {
-    const Status& status = status_and_response.first;
-    const EchoResponse& response = status_and_response.second;
-    EXPECT_TRUE(status.ok()) << "code=" << status.error_code()
-                             << " message=" << status.error_message();
-    EXPECT_EQ(response.message(), kMessage_);
-  }
+
+  // We need to wait for all backends to come online.
+  for (size_t i = 0; i < num_backends_; ++i) WaitForBackend(i);
```
[the remark this answers is not in the document]
Comment (AspirinSJL) [reply test/cpp/end2end/grpclb_end2end_test.cc]: I don't quite understand why this can be more efficient. 

For the time side: the total waiting time is almost equal to the time for the slowest backend to become ready in both conditions.

For the space side: the total number of sent RPCs is like _the total waiting time * RPC sending rate_, which should also be the same in both conditions.

What am I missing?

[the remark this answers is not in the document]
Comment (markdroth) [reply test/cpp/end2end/grpclb_end2end_test.cc]: The approach I suggested minimizes the total number of RPCs sent.

There are two loops here.  The outer loop iterates over the backends in order.  For each backend in the outer loop, we invoke the inner loop, which keeps sending RPCs until the current backend from the outer loop receives a request.  Any time the inner loop sends more than one RPC, we have sent those excess RPCs to backends other than the current backend from the outer loop.  However, we then reset the counters before continuing the outer loop, which means that we forget that those other backends have already seen a request, so we will always send at least one RPC (and possibly more) in the inner loop for each subsequent iteration of the outer loop.

Let's take a very minimal example with only 2 backends, indexes 0 and 1, and that index 1 becomes ready first.  The current code will do the following:

- outer loop: try index 0
- (backend 1 becomes ready)
- inner loop: send RPC, which goes to backend 1
- (backend 0 becomes ready)
- inner loop: send RPC, which goes to backend 0
- we got a request for backend 0, so reset counters for both backends and break out of inner loop
- outer loop: try index 1
- inner loop: send RPC, which goes to index 1
- we got a request for backend 1, so reset counters for both backends and break out of inner loop

Note that the above sent 3 RPCs.  The main problem here is that we reset counters for all backends between iterations of the outer loop.  This means that after the first iteration of the outer loop, we forget that backend 1 has already seen a request, which is why we need to send another RPC for the second iteration of the outer loop.

My proposed change is to avoid resetting the counters until after all iterations of the outer loop, which avoids this problem.  We would thus send only 2 RPCs in the example above.

File: test/cpp/end2end/grpclb_end2end_test.cc [hunk 5]
```diff
@@ -386,6 +391,13 @@ class GrpclbEnd2endTest : public ::testing::Test {
     return client_stats;
   }
 
+  void WaitForBackend(size_t backend_idx) {
+    do {
```
[the remark this answers is not in the document]
Comment (AspirinSJL) [reply test/cpp/end2end/grpclb_end2end_test.cc]: NVM.. It won't save any RPCs, because we reset the counters after each waiting.

File: test/cpp/end2end/grpclb_end2end_test.cc (hunk 4 above)
[the remark this answers is not in the document]
Comment (AspirinSJL) [reply test/cpp/end2end/grpclb_end2end_test.cc]: Ah.. yes. It does reduce the number of sent RPCs because it only resets the counters after all the backends are ready. Thanks for the example.

File: test/cpp/end2end/grpclb_end2end_test.cc [hunk 6]
```diff
@@ -604,51 +626,23 @@ TEST_F(SingleBalancerTest, RepeatedServerlist) {
...
   EXPECT_EQ(2U, balancer_servers_[0].service_->response_count());
-
   // Some more calls to complete the total number of backends.
-  statuses_and_responses = SendRpc(
-      kMessage_,
-      num_backends_ / 2 + (num_backends_ & 0x1) /* extra one if num_bes odd */);
+  CheckRpcSendOk(num_backends_ / 2 + 1);
   // Because a duplicated serverlist should have no effect, all backends must
-  // have been hit once now.
+  // have been hit at least once now.
```
Comment (markdroth) [inline test/cpp/end2end/grpclb_end2end_test.cc]: How do we know that all backends have been hit?  We haven't verified that they've all become ready.

File: test/cpp/end2end/client_lb_end2end_test.cc [hunk 7]
```diff
@@ -367,13 +385,31 @@ TEST_F(ClientLbEnd2endTest, RoundRobin) {
...
+  // However, given an initial connection order and in the absence of
+  // disruptions, this order will be periodic.
+  std::vector<int> first_connection_order;
+  while (true) {
+    for (size_t i = 0; i < servers_.size(); ++i) {
+      CheckRpcSendOk();
+      UpdateConnectionOrder(servers_, &first_connection_order);
+    }
+    if (first_connection_order.size() == servers_.size()) break;
+    first_connection_order.clear();
```
[the remark this answers is not in the document]
Comment (markdroth) [reply test/cpp/end2end/client_lb_end2end_test.cc]: It's true that we're only using the size of `first_connection_order` to break out of this loop.  However, on line 412 below, we're comparing `first_connection_order` and `second_connection_order`.

Oh, wait, I think I see what's happening here.  We're basically forcing the order of `first_connection_order` to match the order of the backends and then verifying that, once all backends are ready, we will iterate over them in that same order.  This works, but it seems like a very convoluted way of expressing what we're trying to check here.  I suggest two changes to make the test clearer to the reader.

First, let's change this initial loop to reuse the `SeenAllBackends()` function from grpclb_end2end_test.cc.  The loop will then look like this:

```
// Wait until all backends are ready.
do {
  CheckRpcSendOk();
} while (!SeenAllBackends());
```

Second, change the check on line 412 to be something like this:

```
// Backends should be iterated over in the order in which the addresses were given.
EXPECT_EQ(std::vector<int>{0, 1, 2}, connection_order);
```

I think that makes the test much easier to understand.

File: test/cpp/end2end/client_lb_end2end_test.cc [hunk 8]
```diff
@@ -367,13 +385,31 @@ TEST_F(ClientLbEnd2endTest, RoundRobin) {
...
   }
-  // One request should have gone to each server.
+  // "first_connection_order" has unique elements by construction. If its length
+  // equals the number of servers, each server must have gotten a request.
+  EXPECT_EQ(first_connection_order.size(), servers_.size());
+  // Subsequent requests maintain the initial connection ordering.
+  ResetCounters();
```
Comment (markdroth) [inline test/cpp/end2end/client_lb_end2end_test.cc]: I think there's still a potential problem here.  Let's say that the backends become ready in the order 0, 2, 1.  If backend 1 doesn't become ready until after we've hit backend 2 for the first time, then the first loop above will hit the backends in the order 0, 2, 0, 1.  This means that after we exit the first loop, the next request will go to backend 2, not backend 0.  However, the second loop below assumes that the first request it sends will go to backend 0.

I think that right after this line, we need to do something like this to reset round_robin to the start of the backend list:

```
WaitForServer(servers_.size() - 1);
```

File: test/cpp/end2end/grpclb_end2end_test.cc (hunk 2 above)
Comment (markdroth) [reply test/cpp/end2end/grpclb_end2end_test.cc]: I'm fine with adding that new test in another PR, but then let's just delete this test in this PR.  As far as I can tell, this test is not proving anything -- as currently written, it would still pass, even if the grpclb code didn't do anything special to handle duplicate serverlists.

File: test/cpp/end2end/grpclb_end2end_test.cc (hunk 6 above)
Comment (markdroth) [reply test/cpp/end2end/grpclb_end2end_test.cc]: Where do we check that all backends have a count of at least 1?  I don't see that anywhere.

Note that in the loop above, we're setting `num_requests` to the total number of requests fielded by all backends, but we're not even bothering to check the resulting value.  And even if we did, that would only tell us that the right total number of requests was seen across all backends; it would not tell us anything about the distribution of those requests across the backends.

File: test/cpp/end2end/client_lb_end2end_test.cc (hunk 7 above)
[the remark this answers is not in the document]
Comment (dgquintas) [reply test/cpp/end2end/client_lb_end2end_test.cc]: We can't guarantee that backends will be iterated in the order they are given. This is the whole reason for this fix. Different polling engines will have different timings that'll result in callbacks being invoked with different orderings. While we process addresses in the order given by the resolver, when a subchannel becomes READY is outside of our control. This effect is even more dramatic is address 2 is 10 km away but address 1 is 1000 km away.

File: test/cpp/end2end/client_lb_end2end_test.cc (hunk 8 above)
Comment (dgquintas) [reply test/cpp/end2end/client_lb_end2end_test.cc]: Done

File: test/cpp/end2end/client_lb_end2end_test.cc (hunk 7 above)
[the remark this answers is not in the document]
Comment (dgquintas) [reply test/cpp/end2end/client_lb_end2end_test.cc]: Done
