### PR TITLE
Check retry timer before starting resolving

### LINKED ISSUE #15118: Assertion failure in resolver: assertion failed: !r->have_next_resolution_timer_
I'm often seeing this when all the backends go down. This seems to be happening both for grpclb (when all the loadbalancers go down) and for round_robin loadbalancing (when all the backends become unavailable).
The assertion failures are:
`E0416 15:46:16.490687 140116582803200 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc:337: assertion failed: !r->have_next_resolution_timer_`
and
`src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc:212: assertion failed: !r->have_next_resolution_timer_`

c-ares case:
```
D0416 15:46:16.490146 140116582803200 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc:332: dns resolution failed: {"created":"@1523893576.489965351","description":"C-ares status is not ARES_SUCCESS: Domain name not found","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc","file_line":201,"referenced_errors":[{"created":"@1523893576.489959893","description":"C-ares status is not ARES_SUCCESS: Domain name not found","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc","file_line":201,"referenced_errors":[{"created":"@1523893576.488115974","description":"C-ares TXT lookup status is not ARES_SUCCESS: Domain name not found","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc","file_line":305,"referenced_errors":[{"created":"@1523893576.467928225","description":"C-ares status is not ARES_SUCCESS: Domain name not found","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc","file_line":246}]}]}]}
I0416 15:46:16.490189 140116582803200 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc:335: dns resolution failed (will retry): {"created":"@1523893576.489965351","description":"C-ares status is not ARES_SUCCESS: Domain name not found","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc","file_line":201,"referenced_errors":[{"created":"@1523893576.489959893","description":"C-ares status is not ARES_SUCCESS: Domain name not found","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc","file_line":201,"referenced_errors":[{"created":"@1523893576.488115974","description":"C-ares TXT lookup status is not ARES_SUCCESS: Domain name not found","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc","file_line":305,"referenced_errors":[{"created":"@1523893576.467928225","description":"C-ares status is not ARES_SUCCESS: Domain name not found","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc","file_line":246}]}]}]}
E0416 15:46:16.490687 140116582803200 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc:337: assertion failed: !r->have_next_resolution_timer_
```

default DNS resolver case:
```
D0419 15:19:52.425631 140004085827392 src/core/ext/filters/client_channel/client_channel.cc:1396: chand=0xe4bd20 calld=0xe5e190: entering client_channel combiner
D0419 15:19:52.425690 140004085827392 src/core/ext/filters/client_channel/client_channel.cc:1097: chand=0xe4bd20 calld=0xe5e190: starting pick on lb_policy=0x7f54940090a0
D0419 15:19:52.425708 140004085827392 src/core/ext/filters/client_channel/client_channel.cc:965: chand=0xe4bd20 calld=0xe5e190: applying service config to call
I0419 15:19:56.435703 140001318262528 src/core/ext/filters/client_channel/subchannel.cc:643: Connect failed: {"created":"@1524151196.435546206","description":"Failed to connect to remote host: OS Error","errno":113,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":203,"os_error":"No route to host","syscall":"getsockopt(SO_ERROR)","target_address":"ipv4:10.0.1.28:8000"}
I0419 15:19:56.435783 140001318262528 src/core/ext/filters/client_channel/subchannel.cc:465: Subchannel 0x7f549400baf0: Retry immediately
I0419 15:19:56.435801 140001318262528 src/core/ext/filters/client_channel/subchannel.cc:422: Failed to connect to channel, retrying
D0419 15:19:56.436000 140001318262528 src/core/ext/filters/client_channel/client_channel.cc:378: chand=0xe4bd20: started name re-resolving
I0419 15:19:56.442994 140001343440640 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc:210: dns resolution failed (will retry): {"created":"@1524151196.442925221","description":"OS Error","errno":-2,"file":"src/core/lib/iomgr/resolve_address_posix.cc","file_line":106,"os_error":"Name or service not known","syscall":"getaddrinfo","target_address":"greeter-server.default.svc.cluster.local:8000"}
E0419 15:19:56.443506 140001343440640 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc:212: assertion failed: !r->have_next_resolution_timer_
```

### PR DESCRIPTION
**Pull request by AspirinSJL**
This should fix #15118, but @jtattermusch can verify. 

By adding this check, we will always honor the retry backoff.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.0%      +8 [None]                                                                               +1.12Ki  +0.0%
  +0.4%     +16 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc             +16  +0.4%
      [NEW]    +184 grpc_core::(anonymous namespace)::AresDnsResolver::MaybeStartResolvingLocked() [clon    +184  [NEW]
       +16%     +25 grpc_core::(anonymous namespace)::AresDnsResolver::NextLocked                            +25   +16%
       +38%      +8 grpc_core::(anonymous namespace)::AresDnsResolver::RequestReresolutionLocked              +8   +38%
  +0.6%     +16 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc                  +16  +0.6%
      [NEW]    +184 grpc_core::(anonymous namespace)::NativeDnsResolver::MaybeStartResolvingLocked() [cl    +184  [NEW]
       +23%     +22 grpc_core::(anonymous namespace)::NativeDnsResolver::NextLocked                          +22   +23%
       +38%      +8 grpc_core::(anonymous namespace)::NativeDnsResolver::RequestReresolutionLocked            +8   +38%

  +0.0%     +40 TOTAL                                                                                +1.15Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by jtattermusch** [comment]
Failure in Basic Windows tests `cmake/build/Debug/dns_resolver_cooldown_test.exe`:

https://source.cloud.google.com/results/invocations/9e4349b3-78f4-4724-a391-d0527c0046cf/targets/github%2Fgrpc%2Fc_windows_dbg_native/tests
```
D0423 14:41:09.086000000  3284 test_config.cc:391] test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
D0423 14:41:09.086000000  3284 dns_resolver.cc:330] Using native dns resolver
D0423 14:41:09.086000000  3284 dns_resolver_cooldown_test.cc:242] test: 'dns:127.0.0.1' should be valid for 'dns'
D0423 14:41:09.102000000  2732 dns_resolver.cc:248] In cooldown from last resolution (from 7 ms ago). Will resolve again in 993 ms
I0423 14:41:09.102000000  2732 dns_resolver_cooldown_test.cc:220] 1st: g_on_resolution_invocations_count: 1, g_resolution_count: 1
I0423 14:41:09.102000000  2732 dns_resolver_cooldown_test.cc:188] 2nd: g_on_resolution_invocations_count: 2, g_resolution_count: 1
E0423 14:41:09.102000000  3284 dns_resolver_cooldown_test.cc:312] assertion failed: g_all_callbacks_invoked
Abort handler called.
*** 0: 0000000001405FCF print_current_stack - 0000000001405F30
*** 1: 000000000140653B abort_handler - 0000000001406510
*** 2: 000000007054F0CB raise - 000000007054ED60
*** 3: 0000000070550622 abort - 00000000705505F0
*** 4: 0000000001322275 main - 0000000001322170
*** 5: 000000000156325E invoke_main - 0000000001563240
*** 6: 00000000015630C0 __scrt_common_main_seh - 0000000001562F70
*** 7: 0000000001562F5D __scrt_common_main - 0000000001562F50
*** 8: 0000000001563278 mainCRTStartup - 0000000001563270
*** 9: 000000007592336A BaseThreadInitThunk - 0000000075923358
*** 10: 0000000077089902 RtlInitializeExceptionChain - 000000007708989F
*** 11: 00000000770898D5 RtlInitializeExceptionChain - 000000007708989F
```

**Comment by jtattermusch** [comment]
@AspirinSJL 
- I tested the change locally and it seems to be fixing the issue (I'm no longer able to reproduce). From that's perspective it's LGTM, but I'd prefer someone with more knowledge of the resolver code to review.
- `cmake/build/Debug/dns_resolver_cooldown_test.exe` now fails and needs to be fixed

File: src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc [hunk 1]
```diff
@@ -363,6 +363,7 @@ void AresDnsResolver::OnResolvedLocked(void* arg, grpc_error* error) {
 }
 
 void AresDnsResolver::MaybeStartResolvingLocked() {
+  if (have_next_resolution_timer_) return;
```
Comment (markdroth) [inline src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc]: I don't think this is the right fix.  This will cause us to fail to immediately return results when `RequestReresolutionLocked()` is called, which we currently need to do due to deficiencies in the pick_first code (see TODO on line 388).

I think a better fix would be to change `OnResolvedLocked()` to only schedule the timer if `have_next_resolution_timer_` is false.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                    FILE SIZE
 ++++++++++++++ GROWING                                                                      ++++++++++++++

 -------------- SHRINKING                                                                    --------------
  -0.8%     -32 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc     -32  -0.8%
      -2.0%     -37 grpc_core::(anonymous namespace)::AresDnsResolver::OnResolvedLocked              -37  -2.0%
  -1.2%     -32 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc          -32  -1.2%
      -5.0%     -36 grpc_core::(anonymous namespace)::NativeDnsResolver::OnResolvedLocked            -36  -5.0%

 -+-+-+-+-+-+-+ MIXED                                                                        +-+-+-+-+-+-+-
  -0.0%     -32 [None]                                                                            +8  +0.0%

  -0.0%     -96 TOTAL                                                                            -56  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by AspirinSJL** [comment]
@jtattermusch I've pushed a new fix. The issue you were seeing should be fixed since this is removing the assertion. 

I will check whether this introduce new test failures.

File: src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc (hunk 1 above)
Comment (AspirinSJL) [reply src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc]: Done.

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

File: src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc [hunk 2]
```diff
@@ -338,20 +338,21 @@ void AresDnsResolver::OnResolvedLocked(void* arg, grpc_error* error) {
...
-    } else {
-      gpr_log(GPR_DEBUG, "retrying immediately");
+    if (!r->have_next_resolution_timer_) {
+      // TODO(roth): We currently deal with this ref manually.  Once the
+      // new closure API is done, find a way to track this ref with the timer
+      // callback as part of the type system.
+      RefCountedPtr<Resolver> self = r->Ref(DEBUG_LOCATION, "retry-timer");
+      self.release();
+      if (timeout > 0) {
+        gpr_log(GPR_DEBUG, "retrying in %" PRIdPTR " milliseconds", timeout);
```
Comment (markdroth) [inline src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc]: Please add a log message for the case where we are not scheduling a timer due to one already being pending.

Same thing in both implementations.

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

File: src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc (hunk 2 above)
Comment (AspirinSJL) [reply src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc]: Done.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                    FILE SIZE
 ++++++++++++++ GROWING                                                                      ++++++++++++++
  +0.0%     +16 [None]                                                                          +144  +0.0%
  +0.4%     +16 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc     +16  +0.4%
       +11%     +14 [Unmapped]                                                                       +14   +11%
      +0.1%      +2 grpc_core::(anonymous namespace)::AresDnsResolver::OnResolvedLocked               +2  +0.1%

  +0.0%     +32 TOTAL                                                                           +160  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

File: src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc (hunk 1 above)
Comment (AspirinSJL) [reply src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc]: I prefer either of the following methods to fix the conflict of an incoming re-resolution and the existing timer.

1.  We can choose to keep the existing timer.
The re-resolution request will be immediately fed the cached results. But we don't start resolving until the existing timer fires.

2. We can choose to service the re-resolution request as soon as possible.
If we are not in cooldown, just cancel the existing timer and start resolving.
If we are in cooldown, cancel the existing timer and start a new timer according to the cooldown ending point. This will always make the timer fire earlier because the cooldown interval is 1s and the initial backoff interval is also 1s. 

With the current fix, we will still start resolving as long as we are not in cooldown, no matter there is a pending timer or not. But my opinion is that there is no need for the pending timer to exist if we have already start resolving. 

But I'm fine with the current fix if we need to address the issue quickly.

Comment (markdroth) [reply src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc]: I think that we never want to send a DNS request immediately if there is already a timer pending.  The whole point of the timer is to ensure that we limit the rate at which we sent DNS requests, and we lose that safety if we start choosing to issue requests immediately instead of waiting for the timer.

However, having thought about this a bit more, I think you're right that it would be better to just ignore the re-resolution request if there is already a timer pending.  So let's go ahead and do it that way (your option 1).

Comment (AspirinSJL) [reply src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc]: Understood.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                          FILE SIZE
 ++++++++++++++ GROWING                                                                            ++++++++++++++
  +0.0%     +16 [None]                                                                                +232  +0.0%
  +0.4%     +16 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc           +16  +0.4%
       +12%     +24 grpc_core::(anonymous namespace)::AresDnsResolver::MaybeStartResolvingLocked           +24   +12%
  +0.6%     +16 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc                +16  +0.6%
       +11%     +21 grpc_core::(anonymous namespace)::NativeDnsResolver::MaybeStartResolvingLocked         +21   +11%

  +0.0%     +48 TOTAL                                                                                 +264  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
@mehrdada after this is merged, let's backport to v1.11.x  and release v1.11.1 (along with the two other resolver fixes that have been backported before).

Also, let's merge this before cutting the v1.12.x branch.

**Comment by jtattermusch** [comment]
@AspirinSJL  looks like all the test failures are the same issue
```
I0426 00:04:49.759711728    3472 dns_resolver_cooldown_test.cc:220] 1st: g_on_resolution_invocations_count: 1, g_resolution_count: 1
I0426 00:04:49.759735022    3472 dns_resolver_cooldown_test.cc:188] 2nd: g_on_resolution_invocations_count: 2, g_resolution_count: 1
I0426 00:04:49.759741733    3472 dns_resolver_cooldown_test.cc:163] 3rd: g_on_resolution_invocations_count: 3, g_resolution_count: 1
E0426 00:04:49.759745681    3472 dns_resolver_cooldown_test.cc:170] assertion failed: g_resolution_count == 2
```

**Comment by mehrdada** [comment]
Please target this at 1.11.x branch so we can easily upmerge.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                          FILE SIZE
 ++++++++++++++ GROWING                                                                            ++++++++++++++
  +0.0%     +16 [None]                                                                                +232  +0.0%
  +0.4%     +16 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc           +16  +0.4%
       +12%     +24 grpc_core::(anonymous namespace)::AresDnsResolver::MaybeStartResolvingLocked           +24   +12%
  +0.6%     +16 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc                +16  +0.6%
       +11%     +21 grpc_core::(anonymous namespace)::NativeDnsResolver::MaybeStartResolvingLocked         +21   +11%

  +0.0%     +48 TOTAL                                                                                 +264  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                          FILE SIZE
 ++++++++++++++ GROWING                                                                            ++++++++++++++
  +0.0%     +16 [None]                                                                                +232  +0.0%
  +0.4%     +16 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc           +16  +0.4%
       +12%     +24 grpc_core::(anonymous namespace)::AresDnsResolver::MaybeStartResolvingLocked           +24   +12%
  +0.6%     +16 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc                +16  +0.6%
       +11%     +21 grpc_core::(anonymous namespace)::NativeDnsResolver::MaybeStartResolvingLocked         +21   +11%

  +0.0%     +48 TOTAL                                                                                 +264  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                          FILE SIZE
 ++++++++++++++ GROWING                                                                            ++++++++++++++
  +0.0%     +16 [None]                                                                                +232  +0.0%
  +0.4%     +16 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc           +16  +0.4%
       +12%     +24 grpc_core::(anonymous namespace)::AresDnsResolver::MaybeStartResolvingLocked           +24   +12%
  +0.6%     +16 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc                +16  +0.6%
       +11%     +21 grpc_core::(anonymous namespace)::NativeDnsResolver::MaybeStartResolvingLocked         +21   +11%

  +0.0%     +48 TOTAL                                                                                 +264  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by AspirinSJL** [comment]
The cooldown test on Windows keeps failing. It seems that we will jump to the end of the test before the cooldown timer fires.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                          FILE SIZE
 ++++++++++++++ GROWING                                                                            ++++++++++++++
  +0.0%     +16 [None]                                                                                +232  +0.0%
  +0.4%     +16 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc           +16  +0.4%
       +12%     +24 grpc_core::(anonymous namespace)::AresDnsResolver::MaybeStartResolvingLocked           +24   +12%
  +0.6%     +16 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc                +16  +0.6%
       +11%     +21 grpc_core::(anonymous namespace)::NativeDnsResolver::MaybeStartResolvingLocked         +21   +11%

  +0.0%     +48 TOTAL                                                                                 +264  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                          FILE SIZE
 ++++++++++++++ GROWING                                                                            ++++++++++++++
  +0.0%     +48 [None]                                                                                +168  +0.0%
  +1.2%     +48 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc           +48  +1.2%
       +16%     +32 grpc_core::(anonymous namespace)::AresDnsResolver::StartResolvingLocked                +32   +16%
       +12%     +24 grpc_core::(anonymous namespace)::AresDnsResolver::MaybeStartResolvingLocked           +24   +12%
  +1.2%     +32 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc                +32  +1.2%
       +16%     +24 grpc_core::(anonymous namespace)::NativeDnsResolver::StartResolvingLocked              +24   +16%
       +11%     +21 grpc_core::(anonymous namespace)::NativeDnsResolver::MaybeStartResolvingLocked         +21   +11%

  +0.0%    +128 TOTAL                                                                                 +248  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                                                                cpu_time    real_time
---------------------------------------------------------------------------------------  ----------  -----------
BM_StreamingPingPongMsgs<MinInProcess, NoOpMutator, NoOpMutator>/262144                  +7%         +7%
BM_StreamingPingPongWithCoalescingApi<InProcess, NoOpMutator, NoOpMutator>/262144/1/0    +5%         +5%
BM_StreamingPingPongWithCoalescingApi<MinInProcess, NoOpMutator, NoOpMutator>/32768/2/1  +4%         +4%
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                          FILE SIZE
 ++++++++++++++ GROWING                                                                            ++++++++++++++
  +0.0%     +48 [None]                                                                                +176  +0.0%
  +1.2%     +48 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc           +48  +1.2%
       +16%     +32 grpc_core::(anonymous namespace)::AresDnsResolver::StartResolvingLocked                +32   +16%
       +12%     +24 grpc_core::(anonymous namespace)::AresDnsResolver::MaybeStartResolvingLocked           +24   +12%
  +1.2%     +32 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc                +32  +1.2%
       +16%     +24 grpc_core::(anonymous namespace)::NativeDnsResolver::StartResolvingLocked              +24   +16%
       +11%     +21 grpc_core::(anonymous namespace)::NativeDnsResolver::MaybeStartResolvingLocked         +21   +11%

  +0.0%    +128 TOTAL                                                                                 +256  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by mehrdada** [comment]
What's the timeline for this PR getting in?

**Comment by AspirinSJL** [comment]
@mehrdada I don't have clear idea why the Windows tests are failing. I will keep trying today, but I don't have an ETA to get it fixed :/

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                          FILE SIZE
 ++++++++++++++ GROWING                                                                            ++++++++++++++
  +0.0%     +16 [None]                                                                                +176  +0.0%
  +1.2%     +48 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc           +48  +1.2%
       +16%     +32 grpc_core::(anonymous namespace)::AresDnsResolver::StartResolvingLocked                +32   +16%
       +12%     +24 grpc_core::(anonymous namespace)::AresDnsResolver::MaybeStartResolvingLocked           +24   +12%
  +1.2%     +32 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc                +32  +1.2%
       +16%     +24 grpc_core::(anonymous namespace)::NativeDnsResolver::StartResolvingLocked              +24   +16%
       +11%     +21 grpc_core::(anonymous namespace)::NativeDnsResolver::MaybeStartResolvingLocked         +21   +11%

  +0.0%     +96 TOTAL                                                                                 +256  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                          FILE SIZE
 ++++++++++++++ GROWING                                                                            ++++++++++++++
  +0.0%     +16 [None]                                                                                +176  +0.0%
  +1.2%     +48 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc           +48  +1.2%
       +16%     +32 grpc_core::(anonymous namespace)::AresDnsResolver::StartResolvingLocked                +32   +16%
       +12%     +24 grpc_core::(anonymous namespace)::AresDnsResolver::MaybeStartResolvingLocked           +24   +12%
  +1.2%     +32 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc                +32  +1.2%
       +16%     +24 grpc_core::(anonymous namespace)::NativeDnsResolver::StartResolvingLocked              +24   +16%
       +11%     +21 grpc_core::(anonymous namespace)::NativeDnsResolver::MaybeStartResolvingLocked         +21   +11%

  +0.0%     +96 TOTAL                                                                                 +256  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by AspirinSJL** [comment]
After enabling polling even when cares is not used, the test failure on Windows (where cares is not used) disappears. This makes sense to me because we need `poll_pollset_until_request_done()` and `grpc_pollset_kick()` to make progress. 

What I don't understand is that before this PR we don't need to call `poll_pollset_until_request_done()` or `grpc_pollset_kick()` to pass the test on Windows. @dgquintas I wonder the reason of adding the `using_cares` check?

Anyways, removing the check and doing polling don't seem harmful. So I will merge the PR now.

**Comment by AspirinSJL** [comment]
Interop Cloud-to-Prod Tests (internal CI): #14969

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                          FILE SIZE
 ++++++++++++++ GROWING                                                                            ++++++++++++++
  +0.0%     +16 [None]                                                                                +176  +0.0%
  +1.2%     +48 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc           +48  +1.2%
       +16%     +32 grpc_core::(anonymous namespace)::AresDnsResolver::StartResolvingLocked                +32   +16%
       +12%     +24 grpc_core::(anonymous namespace)::AresDnsResolver::MaybeStartResolvingLocked           +24   +12%
  +1.2%     +32 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc                +32  +1.2%
       +16%     +24 grpc_core::(anonymous namespace)::NativeDnsResolver::StartResolvingLocked              +24   +16%
       +11%     +21 grpc_core::(anonymous namespace)::NativeDnsResolver::MaybeStartResolvingLocked         +21   +11%

  +0.0%     +96 TOTAL                                                                                 +256  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                                            cpu_time    real_time
-------------------------------------------------------------------  ----------  -----------
BM_UnaryPingPong<InProcess, NoOpMutator, NoOpMutator>/0/262144       -5%         -5%
BM_UnaryPingPong<InProcess, NoOpMutator, NoOpMutator>/262144/262144  -5%         -5%
```

File: test/core/client_channel/resolvers/dns_resolver_cooldown_test.cc [hunk 3]
```diff
@@ -155,81 +154,100 @@ static int g_on_resolution_invocations_count;
...
+  gpr_mu_lock(g_iomgr_args.mu);
+  GRPC_LOG_IF_ERROR("pollset_kick",
+                    grpc_pollset_kick(g_iomgr_args.pollset, nullptr));
+  gpr_mu_unlock(g_iomgr_args.mu);
   grpc_core::Delete(cb_arg);
   g_all_callbacks_invoked = true;
 }
 
-void on_second_resolution(void* arg, grpc_error* error) {
+void on_third_resolution(void* arg, grpc_error* error) {
```
[the remark this answers is not in the document]
Comment (AspirinSJL) [reply test/core/client_channel/resolvers/dns_resolver_cooldown_test.cc]: In short, it is to wait until the resolution timer has fired.

After the second resolution request, there will be a resolution timer set up. Prior to this PR, we can just use `TestOnlySetNow()` to simulate the cooldown completion and test the next resolution request, because `MaybeStartResolvingLocked()` doesn't check whether there is a timer. But with our change to `MaybeStartResolvingLocked()`, such a request will always fail because of the existing timer. To test the resolution behavior after the cooldown completion, we should first make sure there is no pending timer. So the extra callback is to be called when the timer fires and a real resolution is done, at which point we can use `TestOnlySetNow()` to simulate the cooldown completion and have the new resolution request succeed.
