### PR TITLE
bug: remove racy code to detect GCE on Windows

### LINKED ISSUE #16872: GCE detection on windows crashes with multiple processes.
### What version of gRPC and what language are you using?

1.14.1 with C++, but the problem is present on `master`  
 
### What operating system (Linux, Windows, …) and version?
 
 Windows.

### What runtime / compiler are you using (e.g. python version or version of gcc)

MSVC 2017. 
 
### What did you do?

This is hard to reproduce. You need to run two (or more) gRPC clients more or less at the same time. One of the clients will crash.
 
### What did you expect to see?
 
The programs should all run as normal.
 
### What did you see instead?

The program crashes with:

```
E1013 00:19:57.764000000  4380 check_gcp_environment.cc:60] BIOS data file cannot be opened.
unknown file: error: SEH exception with code 0xc0000005 thrown in the test body.
[  FAILED  ] ClientOptionsTest.ClientOptionsDefaultSettings (2001 ms)
[ RUN      ] ClientOptionsTest.EditDataEndpoint
E1013 00:19:57.778000000  4380 sync_windows.cc:38] assertion failed: !mu->locked
        Start  13: cluster_config_test
```

### Anything else we should know about your project / environment?

I think the problem is here:

https://github.com/grpc/grpc/blob/07eecd8421314d62e8df33b14a33203864f91bee/src/core/lib/security/credentials/alts/check_gcp_environment_windows.cc#L106

gRPC is using powershell to create a file (`windows.data`), note that if multiple programs start concurrently they will all create the same file.  After the file is created and parsed it is deleted. If one of the programs deletes the file before another concurrent program gets to read it the second would crash.

Probably the easiest fix is to read the stdout from `CreateProcess` directly:

https://docs.microsoft.com/en-us/windows/desktop/ProcThread/creating-a-child-process-with-redirected-input-and-output
https://stackoverflow.com/questions/35969730/how-to-read-output-from-cmd-exe-using-createprocess-and-createpipe

### PR DESCRIPTION
**Pull request by coryan**
The code used to detect if a program was running on Windows by launching
a powershell script (which requires powershell to be installed), writing
the output to a file with a fixed name (which requires write permissions
in the local directory), and then reading the file (which may have
changed), and then deleting it (which may fail and introduces a race
with any other program running in the same directory).

This version reads a key from the Windows registry. That could fail if
the application does not have permissions to read the registry, but at
least does not crash when it does, and it is not inherently racy.

Fixes #16872 

Routing to the bug owner: @jiangtaoli2016

### CODE REVIEW

**Comment by coryan** [comment]
@AspirinSJL FYI.

**Comment by coryan** [comment]
Ping, any thoughts?

**Comment by jiangtaoli2016** [comment]
@coryan Thanks for the PR. Indeed, storing powershell result in a temporary file could be racy. Although we have a mutex to prevent concurrent run in the same app, but two gRPC apps can cause racy condition.

File: src/core/lib/security/credentials/alts/check_gcp_environment_windows.cc [hunk 1]
```diff
@@ -31,80 +31,70 @@
...
 namespace grpc_core {
 namespace internal {
 
-bool check_bios_data(const char* bios_data_file) {
-  char* bios_data = read_bios_file(bios_data_file);
-  bool result = !strcmp(bios_data, GRPC_ALTS_EXPECT_NAME_GOOGLE);
-  remove(GRPC_ALTS_WINDOWS_CHECK_BIOS_FILE);
-  gpr_free(bios_data);
-  return result;
+bool check_bios_data(const char*) {
```
Comment (jiangtaoli2016) [inline src/core/lib/security/credentials/alts/check_gcp_environment_windows.cc]: Do we still need this function?

Comment (coryan) [reply src/core/lib/security/credentials/alts/check_gcp_environment_windows.cc]: Maybe not, I can remove it.  But it is declared here:

https://github.com/grpc/grpc/blob/2b06d76cc06e2fa4016713c1cabec510a4f89e87/src/core/lib/security/credentials/alts/check_gcp_environment.h#L36-L45

Which would leave a dangling declaration, and that cannot be removed because it is used in the Linux test:

https://github.com/grpc/grpc/blob/2b06d76cc06e2fa4016713c1cabec510a4f89e87/test/core/security/check_gcp_environment_linux_test.cc#L41

Thoughts?  I think it might be better to have a future PR remove the declaration and *only* declare it on the Linux test and not the header file.

Comment (jiangtaoli2016) [reply src/core/lib/security/credentials/alts/check_gcp_environment_windows.cc]: You are right, we cannot remove it yet. 
Let me or my teammates have a separate PR to move check_bios_data() to Linux only implementation.

**Comment by jiangtaoli2016** [comment]
@coryan Could you please run clang format? We have sanity check error.

`CLANG_FORMAT_ROOT=~/grpc tools/dockerfile/grpc_clang_format/clang_format_all_the_things.sh`

**Comment by coryan** [comment]
PTAL.

**Comment by jiangtaoli2016** [comment]
Known issue https://github.com/grpc/grpc/issues/20436
