### PR TITLE
Scale Back Concurrency of arena_test

### LINKED ISSUE #14513: Bazel test failure: arena test fails under TSAN and MSAN
https://source.cloud.google.com/results/invocations/45571f80-62f2-4e33-a601-03975b652456/targets/%2F%2Ftest%2Fcore%2Fgpr:arena_test@poller%3Depoll1/log

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
+ export GRPC_POLL_STRATEGY=epoll1
+ shift
+ test/core/gpr/arena_test
D0223 17:11:44.616693676      19 test_config.cc:390]         test slowdown factor: sanitizer=5, fixture=1, poller=1, total=5
I0223 17:11:44.619815802      19 arena_test.cc:49]           test '0_1': 0 <- {1,}
I0223 17:11:44.620922908      19 arena_test.cc:49]           test '1_1': 1 <- {1,}
I0223 17:11:44.620969642      19 arena_test.cc:49]           test '1_2': 1 <- {2,}
I0223 17:11:44.621075068      19 arena_test.cc:49]           test '1_3': 1 <- {3,}
I0223 17:11:44.622938466      19 arena_test.cc:49]           test '1_inc': 1 <- {1,2,3,4,5,6,7,8,9,10,11,}
I0223 17:11:44.624796252      19 arena_test.cc:49]           test '6_123': 6 <- {1,2,3,}
D0223 17:11:44.624828389      19 arena_test.cc:94]           concurrent_test
Killed
```

### PR DESCRIPTION
**Pull request by ncteisen**
Fixes #14513 

Looks like this test was too resource heavy for extra overhead needed by TSAN.

I was able to reproduce the timeout locally, and this change fixes it

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

File: test/core/gpr/arena_test.cc [hunk 1]
```diff
@@ -86,7 +81,7 @@ typedef struct {
 static void concurrent_test_body(void* arg) {
   concurrent_test_args* a = static_cast<concurrent_test_args*>(arg);
   gpr_event_wait(&a->ev_start, gpr_inf_future(GPR_CLOCK_REALTIME));
-  for (size_t i = 0; i < concurrent_test_iterations(); i++) {
+  for (size_t i = 0; i < 1000; i++) {
```
Comment (jtattermusch) [inline test/core/gpr/arena_test.cc]: I am actually not sure what would be the right constant to use here.  1000 was chosen for 32bit platforms.  Have you tried if things still pass with remote bazel at 10000 iterations? (to me it seems that the main thing that would influence memory consumption is the number of threads.

Comment (ncteisen) [reply test/core/gpr/arena_test.cc]: Yes, it looks like only scaling back threads is enough to prevent the timeout (at least on my machine)

**Comment by ncteisen** [comment]
TESTED= bazel test  --copt=-gmlt --strip=never --copt=-fsanitize=thread --linkopt=-fsanitize=thread  test/core/gpr/arena_test@poller=epoll1 --runs_per_test 100

That command would deterministically timeout (and really screw up my machine) before this change

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```
